use crate::mysql::binder::Binder;
use crate::mysql::catalog::DbState;
use crate::mysql::error::MySqlError;
use crate::mysql::exec::Executor;
use crate::mysql::plan::{self, Plan};
use crate::mysql::types::Value;
use sqlparser::ast::{ShowStatementFilter, Statement};
use sqlparser::dialect::MySqlDialect;
use sqlparser::parser::Parser;
use std::sync::{Arc, Mutex};

#[derive(Clone)]
pub struct Engine {
    pub db: Arc<Mutex<DbState>>,
    pub current_db: Option<String>,
    /// Rows affected by the most recent `INSERT`/`UPDATE`/`DELETE`, so
    /// `server.rs` can put a real count in the OK packet.
    pub last_affected_rows: u64,
    /// The AUTO_INCREMENT value generated by the most recently executed
    /// statement, 0 if it didn't generate one. This backs the OK packet's
    /// own `last_insert_id` field (what `mysqli_insert_id()` and
    /// `mysql_async::Conn::last_insert_id()` read), which real MySQL
    /// reports per-statement, not as a persisted session value -- unlike
    /// the `LAST_INSERT_ID()` SQL function (not yet implemented), which
    /// *does* persist across intervening statements.
    pub last_insert_id: u64,
    /// The real column names of the most recent statement's result set
    /// (empty for a statement that doesn't return rows), so `server.rs`
    /// can report them in the wire column-definition packets instead of
    /// placeholders. See `plan::column_names`.
    pub last_column_names: Vec<String>,
    /// The row count `SQL_CALC_FOUND_ROWS` computed (before `LIMIT`
    /// truncation) for the most recent query that used it, so a later
    /// `FOUND_ROWS()` call can read it. Unlike `last_insert_id`'s wire
    /// field, this *does* persist across intervening statements, matching
    /// real MySQL and `LAST_INSERT_ID()` (`session_insert_id`) -- see
    /// `Executor::last_found_rows`.
    pub last_found_rows: u64,
    /// What `LAST_INSERT_ID()` returns: the most recent id an INSERT on this
    /// connection generated, kept across later statements.
    pub session_insert_id: u64,
    /// This connection's id, keying its undo log in `DbState::open_txns`.
    pub conn_id: u64,
    /// The session's `autocommit` (on by default). With it off, the first
    /// write implicitly opens a transaction that lasts until COMMIT or
    /// ROLLBACK -- how pymysql, mysqlclient, SQLAlchemy and Django's
    /// `atomic()` run transactions (they never send BEGIN).
    pub autocommit: bool,
    /// Whether a transaction is open (explicit BEGIN, or implicit).
    pub in_tx: bool,
}

static NEXT_CONN_ID: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);

impl Default for Engine {
    fn default() -> Self {
        Self {
            db: Arc::new(Mutex::new(DbState::default())),
            current_db: None,
            last_affected_rows: 0,
            last_insert_id: 0,
            last_column_names: Vec::new(),
            last_found_rows: 0,
            session_insert_id: 0,
            conn_id: NEXT_CONN_ID.fetch_add(1, std::sync::atomic::Ordering::Relaxed),
            autocommit: true,
            in_tx: false,
        }
    }
}

impl Engine {
    pub fn new() -> Self {
        Self::default()
    }

    /// Clones out the shared database state for an on-disk snapshot. Only
    /// `db` is persisted -- see the persistence spec, §4.4, for why every
    /// other field here is per-connection/per-statement and deliberately
    /// excluded.
    ///
    /// If an uncommitted transaction is in progress, the pre-transaction base
    /// state (`tx_base`) is saved instead, ensuring uncommitted writes are
    /// never made durable across a restart.
    pub fn snapshot(&self) -> DbState {
        let state = self.db.lock().unwrap();
        let mut clean = state.clone();
        clean.open_txns.clear();
        for undo in state.open_txns.values() {
            clean.undo(undo);
        }
        clean
    }

    /// Builds an `Engine` whose shared database state is `db` (loaded from
    /// an on-disk snapshot), with every per-connection field at its
    /// ordinary just-connected default -- same as `Engine::new()`, just
    /// with real data instead of an empty `DbState`.
    pub fn new_persistent(db: DbState) -> Self {
        Self { db: Arc::new(Mutex::new(db)), ..Self::default() }
    }

    /// The MySQL protocol status flags for this session's next OK/EOF
    /// packet: `SERVER_STATUS_IN_TRANS` (1) and `SERVER_STATUS_AUTOCOMMIT`
    /// (2). pymysql decides whether to send `SET autocommit` from these.
    /// A new connection's session over the same shared database: its own
    /// id and fresh session state.
    pub fn new_connection(&self) -> Engine {
        Engine { db: self.db.clone(), ..Engine::default() }
    }

    /// Rolls back this connection's open transaction, if any (on
    /// disconnect, as MySQL does).
    pub fn rollback(&mut self) {
        let mut state = self.db.lock().unwrap();
        if let Some(undo) = state.open_txns.remove(&self.conn_id) {
            state.undo(&undo);
        }
        self.in_tx = false;
    }

    pub fn status_flags(&self) -> u16 {
        u16::from(self.in_tx) | if self.autocommit { 2 } else { 0 }
    }

    /// Ends this connection's transaction, keeping its writes.
    pub fn commit(&mut self) {
        if self.in_tx {
            self.db.lock().unwrap().open_txns.remove(&self.conn_id);
        }
        self.in_tx = false;
    }

    /// Transaction bookkeeping before a plan runs (shared with the
    /// prepared-statement path in `server.rs`): DDL commits an open
    /// transaction first (MySQL's implicit commit); a write opens one when
    /// `autocommit` is off and records the table's pre-image. Returns the
    /// table a write targets, for `after_plan`.
    pub fn before_plan(&mut self, plan: &Plan) -> Option<(String, String)> {
        match plan {
            Plan::CreateTable { .. }
            | Plan::DropTable { .. }
            | Plan::Truncate { .. }
            | Plan::CreateDatabase { .. }
            | Plan::CreateIndex { .. } => {
                self.commit();
                None
            }
            Plan::Insert { db, table, .. }
            | Plan::Update { db, table, .. }
            | Plan::Delete { db, table, .. } => {
                if !self.in_tx && !self.autocommit {
                    self.in_tx = true;
                }
                if !self.in_tx {
                    return None;
                }
                let key = (db.clone(), table.clone());
                let mut state = self.db.lock().unwrap();
                let current = state.schemas.get(db).and_then(|s| s.tables.get(table)).cloned();
                let undo = state.open_txns.entry(self.conn_id).or_default();
                if let Some(t) = current {
                    undo.tables.entry(key.clone()).or_insert_with(|| (t.clone(), t));
                }
                Some(key)
            }
            _ => None,
        }
    }

    /// Records the table a transactional write left behind (see `before_plan`).
    pub fn after_plan(&mut self, written: Option<(String, String)>) {
        let Some((db, table)) = written else { return };
        let mut state = self.db.lock().unwrap();
        let Some(now) = state.schemas.get(&db).and_then(|s| s.tables.get(&table)).cloned() else {
            return;
        };
        if let Some(entry) =
            state.open_txns.get_mut(&self.conn_id).and_then(|u| u.tables.get_mut(&(db, table)))
        {
            entry.1 = now;
        }
    }

    pub fn execute(&mut self, sql: &str) -> Result<Vec<Vec<Value>>, MySqlError> {
        let dialect = MySqlDialect {};
        let mut asts = Parser::parse_sql(&dialect, sql)
            .map_err(|e| MySqlError::syntax_error(&e.to_string()))?;

        if asts.is_empty() {
            return Ok(vec![]);
        }

        let stmt = asts.remove(0);

        // Transaction control statements are handled here, at the
        // session/engine level, rather than as a `Plan` variant: they need
        // state (`tx_snapshot`) that lives across separate `execute` calls,
        // which `Executor` (built fresh per statement) doesn't have.
        match &stmt {
            Statement::StartTransaction { .. } => {
                // BEGIN inside a transaction commits it first, as in MySQL.
                self.commit();
                self.in_tx = true;
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::Commit { .. } => {
                self.commit();
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            // Connection-setup statements every real driver/framework sends
            // before its first query (pymysql/mysqlclient: `SET NAMES`;
            // Laravel/Rails/Django: `SET NAMES ... COLLATE`, `SET SESSION
            // sql_mode`, `SET SESSION TRANSACTION ISOLATION LEVEL`; JDBC:
            // `SHOW VARIABLES`, `SET character_set_results`). Found via
            // testing before a public release: every one of these used to
            // fail as "unsupported statement", so pymysql (and anything on
            // top of it: SQLAlchemy, Django) couldn't even connect. `SET` is
            // an accepted no-op: the connection is already utf8mb4 and this
            // engine has no per-session mode/charset/isolation state for it
            // to change.
            Statement::Set(set) => {
                // `SET autocommit = 0|1` is the one setting with an effect:
                // turning it back on commits an open transaction.
                if let Some(on) = autocommit_assignment(set) {
                    if on && !self.autocommit {
                        self.commit();
                    }
                    self.autocommit = on;
                }
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::ShowVariables { filter, .. } => {
                self.last_affected_rows = 0;
                self.last_column_names = vec!["Variable_name".into(), "Value".into()];
                return Ok(show_filtered(SESSION_VARIABLES, filter.as_ref()));
            }
            Statement::ShowStatus { filter, .. } => {
                self.last_affected_rows = 0;
                self.last_column_names = vec!["Variable_name".into(), "Value".into()];
                return Ok(show_filtered(STATUS_VARIABLES, filter.as_ref()));
            }
            Statement::ShowCollation { filter } => {
                self.last_affected_rows = 0;
                self.last_column_names =
                    ["Collation", "Charset", "Id", "Default", "Compiled", "Sortlen"]
                        .map(String::from)
                        .to_vec();
                let all = show_filtered(COLLATIONS, filter.as_ref());
                // `show_filtered` yields (name, charset) pairs; widen to the
                // real six-column SHOW COLLATION shape.
                return Ok(all
                    .into_iter()
                    .enumerate()
                    .map(|(i, mut r)| {
                        r.push(Value::Int(255 - i as i64));
                        r.push(Value::Text(if i == 0 { "Yes" } else { "" }.into()));
                        r.push(Value::Text("Yes".into()));
                        r.push(Value::Int(0));
                        r
                    })
                    .collect());
            }
            // `SHOW {INDEX|INDEXES|KEYS} {FROM|IN} t [{FROM|IN} db]`, which
            // sqlparser's MySQL dialect leaves as a bare word list.
            Statement::ShowVariable { variable }
                if variable.len() >= 3
                    && ["INDEX", "INDEXES", "KEYS"]
                        .iter()
                        .any(|w| variable[0].value.eq_ignore_ascii_case(w)) =>
            {
                let words: Vec<&str> = variable.iter().map(|i| i.value.as_str()).collect();
                let table = words[2];
                let db = match words.get(4) {
                    Some(d) => d.to_string(),
                    None => self
                        .current_db
                        .clone()
                        .ok_or_else(|| MySqlError::new(1046, "3D000", "No database selected"))?,
                };
                let t = {
                    let state = self.db.lock().unwrap();
                    crate::mysql::infoschema::lookup_table(&state, &db, table)
                }
                .ok_or_else(|| {
                    MySqlError::new(1146, "42S02", format!("Table '{db}.{table}' doesn't exist"))
                })?;
                self.last_affected_rows = 0;
                self.last_column_names =
                    crate::mysql::infoschema::SHOW_INDEX_COLUMNS.map(String::from).to_vec();
                return Ok(crate::mysql::infoschema::show_index(&t));
            }
            // `SHOW <word>` forms sqlparser has no dedicated node for.
            // Only the ones real clients actually send get an answer; any
            // other one still falls through to "unsupported" rather than a
            // made-up empty result.
            Statement::ShowVariable { variable }
                if variable.len() == 1
                    && ["WARNINGS", "ERRORS", "ENGINES"]
                        .iter()
                        .any(|w| variable[0].value.eq_ignore_ascii_case(w)) =>
            {
                self.last_affected_rows = 0;
                let word = variable[0].value.to_ascii_uppercase();
                if word == "ENGINES" {
                    self.last_column_names =
                        ["Engine", "Support", "Comment", "Transactions", "XA", "Savepoints"]
                            .map(String::from)
                            .to_vec();
                    return Ok(vec![
                        ["InnoDB", "DEFAULT", "noida-db in-memory engine", "YES", "NO", "NO"]
                            .map(|s| Value::Text(s.into()))
                            .to_vec(),
                    ]);
                }
                // No warnings channel exists, so there are never any to show.
                self.last_column_names = ["Level", "Code", "Message"].map(String::from).to_vec();
                return Ok(vec![]);
            }
            Statement::Rollback { .. } => {
                {
                    let mut state = self.db.lock().unwrap();
                    if let Some(undo) = state.open_txns.remove(&self.conn_id) {
                        state.undo(&undo);
                    }
                }
                self.in_tx = false;
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            _ => {}
        }

        let mut binder = Binder::new(self.current_db.clone()).with_sql(sql);
        let plan = binder.bind_statement(stmt)?;
        self.last_column_names = {
            let state = self.db.lock().unwrap();
            plan::column_names(&plan, &state)
        };

        let mut executor = Executor::new(self.db.clone(), self.current_db.clone());
        executor.last_found_rows = self.last_found_rows;
        executor.session_insert_id = self.session_insert_id;
        let written = self.before_plan(&plan);
        let res = executor.execute_plan(plan)?;
        self.after_plan(written);
        self.last_affected_rows = executor.last_affected_rows;
        self.last_insert_id = executor.last_insert_id;
        if executor.last_insert_id != 0 {
            self.session_insert_id = executor.last_insert_id;
        }
        self.last_found_rows = executor.last_found_rows;

        // Update current DB if USE was called
        if let Some(db) = executor.current_db {
            self.current_db = Some(db);
        }

        Ok(res)
    }

    pub fn use_db(&mut self, db: &str) {
        self.current_db = Some(db.to_string());
    }
}

/// What `SHOW [SESSION|GLOBAL] VARIABLES` reports. Values agree with what
/// `SELECT @@var` already returns for the names `Executor` knows (version
/// `8.0.33`, `max_allowed_packet`, `wait_timeout`, ...), so a driver that
/// reads the same setting both ways sees one consistent answer.
pub(crate) const SESSION_VARIABLES: &[(&str, &str)] = &[
    ("auto_increment_increment", "1"),
    ("auto_increment_offset", "1"),
    ("autocommit", "ON"),
    ("character_set_client", "utf8mb4"),
    ("character_set_connection", "utf8mb4"),
    ("character_set_database", "utf8mb4"),
    ("character_set_results", "utf8mb4"),
    ("character_set_server", "utf8mb4"),
    ("collation_connection", "utf8mb4_0900_ai_ci"),
    ("collation_database", "utf8mb4_0900_ai_ci"),
    ("collation_server", "utf8mb4_0900_ai_ci"),
    ("have_ssl", "DISABLED"),
    ("init_connect", ""),
    ("interactive_timeout", "28800"),
    ("license", "GPL"),
    ("lower_case_table_names", "0"),
    ("max_allowed_packet", "67108864"),
    ("net_buffer_length", "16384"),
    ("net_write_timeout", "60"),
    ("performance_schema", "OFF"),
    ("port", "3306"),
    ("socket", "/tmp/mysql.sock"),
    (
        "sql_mode",
        "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
    ),
    ("system_time_zone", "UTC"),
    ("time_zone", "SYSTEM"),
    ("transaction_isolation", "REPEATABLE-READ"),
    ("tx_isolation", "REPEATABLE-READ"),
    ("version", "8.0.33"),
    ("version_comment", "noida-db MySQL 8.0"),
    ("wait_timeout", "28800"),
];

const STATUS_VARIABLES: &[(&str, &str)] = &[("Threads_connected", "1"), ("Uptime", "1")];

/// `(collation, charset)` pairs for `SHOW COLLATION`; the first is the default.
const COLLATIONS: &[(&str, &str)] = &[
    ("utf8mb4_0900_ai_ci", "utf8mb4"),
    ("utf8mb4_general_ci", "utf8mb4"),
    ("utf8mb4_unicode_ci", "utf8mb4"),
    ("utf8mb4_bin", "utf8mb4"),
];

/// Applies a `SHOW ... LIKE 'pattern'` filter to a two-column name/value
/// table (MySQL's `LIKE` here matches the first column, case-insensitively).
/// A `WHERE` filter isn't evaluated -- every row is returned, which only
/// ever over-reports to clients that look values up by name (JDBC's old
/// `SHOW VARIABLES WHERE Variable_name = ...` probe), never drops one.
fn show_filtered(table: &[(&str, &str)], filter: Option<&ShowStatementFilter>) -> Vec<Vec<Value>> {
    let pattern = match filter {
        Some(ShowStatementFilter::Like(p)) | Some(ShowStatementFilter::NoKeyword(p)) => {
            Some(p.as_str())
        }
        _ => None,
    };
    table
        .iter()
        .filter(|(name, _)| {
            pattern.is_none_or(|p| crate::mysql::exec::mysql_like(name, p, Some('\\')))
        })
        .map(|(n, v)| vec![Value::Text((*n).into()), Value::Text((*v).into())])
        .collect()
}

/// `Some(on)` if `set` assigns `autocommit` (`SET autocommit = 0`,
/// `SET @@autocommit = 1`, `SET SESSION autocommit = OFF`, ...).
fn autocommit_assignment(set: &sqlparser::ast::Set) -> Option<bool> {
    use sqlparser::ast::{Expr as E, Set, Value as V};
    let pairs: Vec<(String, &E)> = match set {
        Set::SingleAssignment { variable, values, .. } => {
            values.first().map(|v| vec![(variable.to_string(), v)]).unwrap_or_default()
        }
        Set::MultipleAssignments { assignments } => {
            assignments.iter().map(|a| (a.name.to_string(), &a.value)).collect()
        }
        _ => vec![],
    };
    let mut out = None;
    for (name, value) in pairs {
        let name = name.trim_start_matches('@').to_ascii_lowercase();
        if name.rsplit('.').next() != Some("autocommit") {
            continue;
        }
        out = match value {
            E::Value(v) => match &v.value {
                V::Number(n, _) => Some(n != "0"),
                V::Boolean(b) => Some(*b),
                V::SingleQuotedString(s) => Some(!s.eq_ignore_ascii_case("off") && s != "0"),
                _ => None,
            },
            E::Identifier(i) => {
                Some(i.value.eq_ignore_ascii_case("on") || i.value.eq_ignore_ascii_case("true"))
            }
            _ => None,
        }
        .or(out);
    }
    out
}
