use crate::mysql::binder::Binder;
use crate::mysql::catalog::{DbState, Table, TxUndo};
use crate::mysql::error::MySqlError;
use crate::mysql::exec::Executor;
use crate::mysql::plan::{self, Plan};
use crate::mysql::types::Value;
use sqlparser::ast::{ShowStatementFilter, Statement};
use sqlparser::dialect::MySqlDialect;
use sqlparser::parser::Parser;
use std::collections::BTreeMap;
use std::sync::{Arc, Mutex};

#[derive(Clone)]
pub struct Engine {
    pub db: Arc<Mutex<DbState>>,
    pub current_db: Option<String>,
    /// Rows affected by the most recent `INSERT`/`UPDATE`/`DELETE`, so
    /// `server.rs` can put a real count in the OK packet.
    pub last_affected_rows: u64,
    /// The AUTO_INCREMENT value generated by the most recently executed
    /// statement, 0 if it didn't generate one. This backs the OK packet's
    /// own `last_insert_id` field (what `mysqli_insert_id()` and
    /// `mysql_async::Conn::last_insert_id()` read), which real MySQL
    /// reports per-statement, not as a persisted session value -- unlike
    /// the `LAST_INSERT_ID()` SQL function (not yet implemented), which
    /// *does* persist across intervening statements.
    pub last_insert_id: u64,
    /// The real column names of the most recent statement's result set
    /// (empty for a statement that doesn't return rows), so `server.rs`
    /// can report them in the wire column-definition packets instead of
    /// placeholders. See `plan::column_names`.
    pub last_column_names: Vec<String>,
    /// The row count `SQL_CALC_FOUND_ROWS` computed (before `LIMIT`
    /// truncation) for the most recent query that used it, so a later
    /// `FOUND_ROWS()` call can read it. Unlike `last_insert_id`'s wire
    /// field, this *does* persist across intervening statements, matching
    /// real MySQL and `LAST_INSERT_ID()` (`session_insert_id`) -- see
    /// `Executor::last_found_rows`.
    pub last_found_rows: u64,
    /// What `LAST_INSERT_ID()` returns: the most recent id an INSERT on this
    /// connection generated, kept across later statements.
    pub session_insert_id: u64,
    /// This connection's id, keying its undo log in `DbState::open_txns`.
    pub conn_id: u64,
    /// The session's `autocommit` (on by default). With it off, the first
    /// write implicitly opens a transaction that lasts until COMMIT or
    /// ROLLBACK -- how pymysql, mysqlclient, SQLAlchemy and Django's
    /// `atomic()` run transactions (they never send BEGIN).
    pub autocommit: bool,
    /// The session's `sql_mode` (MySQL 8's strict default until a
    /// `SET sql_mode = '...'`, which WordPress sends on every connection).
    pub sql_mode: crate::mysql::sqlmode::SqlMode,
    /// `foreign_key_checks` (on by default; dump files and migrations turn
    /// it off while loading tables in any order).
    pub fk_checks: bool,
    /// `innodb_lock_wait_timeout`: how long a statement waits for a row
    /// another transaction holds before error 1205.
    pub lock_wait_timeout: u64,
    /// The client connected with `CLIENT_FOUND_ROWS` (see `Executor`).
    pub found_rows: bool,
    /// Whether a transaction is open (explicit BEGIN, or implicit).
    pub in_tx: bool,
    /// Open savepoints, oldest first: each name with the tables the
    /// transaction had written by then, as they stood at the savepoint.
    savepoints: Vec<(String, TableImages)>,
}

/// Tables as they stood at a savepoint, by (database, table).
type TableImages = BTreeMap<(String, String), Arc<Table>>;

static NEXT_CONN_ID: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);

impl Default for Engine {
    fn default() -> Self {
        Self {
            db: Arc::new(Mutex::new(DbState::default())),
            current_db: None,
            last_affected_rows: 0,
            last_insert_id: 0,
            last_column_names: Vec::new(),
            last_found_rows: 0,
            session_insert_id: 0,
            conn_id: NEXT_CONN_ID.fetch_add(1, std::sync::atomic::Ordering::Relaxed),
            autocommit: true,
            sql_mode: crate::mysql::sqlmode::SqlMode::default(),
            found_rows: false,
            fk_checks: true,
            lock_wait_timeout: 50,
            in_tx: false,
            savepoints: Vec::new(),
        }
    }
}

impl Engine {
    pub fn new() -> Self {
        Self::default()
    }

    /// Clones out the shared database state for an on-disk snapshot. Only
    /// `db` is persisted -- see the persistence spec, §4.4, for why every
    /// other field here is per-connection/per-statement and deliberately
    /// excluded.
    ///
    /// If an uncommitted transaction is in progress, the pre-transaction base
    /// state (`tx_base`) is saved instead, ensuring uncommitted writes are
    /// never made durable across a restart.
    pub fn snapshot(&self) -> DbState {
        let state = self.db.lock().unwrap();
        let mut clean = state.clone();
        clean.open_txns.clear();
        for undo in state.open_txns.values() {
            clean.undo(undo);
        }
        clean
    }

    /// Builds an `Engine` whose shared database state is `db` (loaded from
    /// an on-disk snapshot), with every per-connection field at its
    /// ordinary just-connected default -- same as `Engine::new()`, just
    /// with real data instead of an empty `DbState`.
    pub fn new_persistent(db: DbState) -> Self {
        Self { db: Arc::new(Mutex::new(db)), ..Self::default() }
    }

    /// The MySQL protocol status flags for this session's next OK/EOF
    /// packet: `SERVER_STATUS_IN_TRANS` (1) and `SERVER_STATUS_AUTOCOMMIT`
    /// (2). pymysql decides whether to send `SET autocommit` from these.
    /// A new connection's session over the same shared database: its own
    /// id and fresh session state.
    pub fn new_connection(&self) -> Engine {
        Engine { db: self.db.clone(), ..Engine::default() }
    }

    /// Rolls back this connection's open transaction, if any (on
    /// disconnect, as MySQL does).
    pub fn rollback(&mut self) {
        let mut state = self.db.lock().unwrap();
        if let Some(undo) = state.open_txns.remove(&self.conn_id) {
            state.undo(&undo);
        }
        self.in_tx = false;
    }

    pub fn status_flags(&self) -> u16 {
        u16::from(self.in_tx) | if self.autocommit { 2 } else { 0 }
    }

    /// Ends this connection's transaction, keeping its writes.
    pub fn commit(&mut self) {
        if self.in_tx {
            self.db.lock().unwrap().open_txns.remove(&self.conn_id);
        }
        self.in_tx = false;
        self.savepoints.clear();
    }

    /// `SAVEPOINT name`: remembers how every table the transaction has
    /// written so far stands now (a table first written later is undone
    /// back to its own pre-image). Django's nested `atomic()` uses these.
    fn savepoint(&mut self, name: &str) {
        if !self.in_tx && !self.autocommit {
            self.in_tx = true;
        }
        if !self.in_tx {
            return;
        }
        let state = self.db.lock().unwrap();
        let tables: BTreeMap<_, _> = state
            .open_txns
            .get(&self.conn_id)
            .map(|u| {
                u.tables
                    .keys()
                    .filter_map(|(db, t)| {
                        let cur = state.schemas.get(db)?.tables.get(t)?.clone();
                        Some(((db.clone(), t.clone()), cur))
                    })
                    .collect()
            })
            .unwrap_or_default();
        drop(state);
        self.savepoints.retain(|(n, _)| !n.eq_ignore_ascii_case(name));
        self.savepoints.push((name.to_string(), tables));
    }

    /// `ROLLBACK TO SAVEPOINT name`: undoes the writes made since it.
    fn rollback_to(&mut self, name: &str) -> Result<(), MySqlError> {
        let Some(pos) = self.savepoints.iter().rposition(|(n, _)| n.eq_ignore_ascii_case(name))
        else {
            return Err(MySqlError::new(1305, "42000", format!("SAVEPOINT {name} does not exist")));
        };
        self.savepoints.truncate(pos + 1);
        let at = self.savepoints[pos].1.clone();
        let mut state = self.db.lock().unwrap();
        let Some(undo) = state.open_txns.get(&self.conn_id).cloned() else { return Ok(()) };
        // Tables written before the savepoint go back to how they stood
        // then; tables first written after it, to their pre-transaction
        // image (and leave the undo log).
        let partial = TxUndo {
            locks: Vec::new(),
            tables: undo
                .tables
                .iter()
                .map(|(k, (before, ours))| {
                    (
                        k.clone(),
                        (at.get(k).cloned().unwrap_or_else(|| before.clone()), ours.clone()),
                    )
                })
                .collect(),
        };
        state.undo(&partial);
        let mut kept = undo;
        kept.tables.retain(|k, _| at.contains_key(k));
        for (k, entry) in kept.tables.iter_mut() {
            if let Some(now) = state.schemas.get(&k.0).and_then(|s| s.tables.get(&k.1)) {
                entry.1 = now.clone();
            }
        }
        state.open_txns.insert(self.conn_id, kept);
        Ok(())
    }

    /// Transaction bookkeeping before a plan runs (shared with the
    /// prepared-statement path in `server.rs`): DDL commits an open
    /// transaction first (MySQL's implicit commit); a write opens one when
    /// `autocommit` is off and records the table's pre-image. Returns the
    /// table a write targets, for `after_plan`.
    pub fn before_plan(&mut self, plan: &Plan) -> Vec<(String, String)> {
        match plan {
            Plan::InsertSelect { insert, .. } => self.before_plan(insert),
            // A locking read inside a transaction holds its locks until the
            // transaction ends.
            Plan::Locking { .. } => {
                if !self.in_tx && !self.autocommit {
                    self.in_tx = true;
                }
                if self.in_tx {
                    self.db.lock().unwrap().open_txns.entry(self.conn_id).or_default();
                }
                vec![]
            }
            Plan::CreateTable { .. }
            | Plan::DropTable { .. }
            | Plan::Truncate { .. }
            | Plan::CreateDatabase { .. }
            | Plan::AlterTable { .. }
            | Plan::DropDatabase { .. }
            | Plan::CreateIndex { .. } => {
                self.commit();
                vec![]
            }
            Plan::Insert { db, table, .. }
            | Plan::Update { db, table, .. }
            | Plan::Delete { db, table, .. } => {
                if !self.in_tx && !self.autocommit {
                    self.in_tx = true;
                }
                if !self.in_tx {
                    return vec![];
                }
                // A write can cascade (ON DELETE/UPDATE CASCADE, SET NULL)
                // into every table referencing this one.
                let mut state = self.db.lock().unwrap();
                let keys = state.cascade_reach(db, table);
                for key in &keys {
                    let current =
                        state.schemas.get(&key.0).and_then(|s| s.tables.get(&key.1)).cloned();
                    let undo = state.open_txns.entry(self.conn_id).or_default();
                    if let Some(t) = current {
                        undo.tables.entry(key.clone()).or_insert_with(|| (t.clone(), t));
                    }
                }
                keys
            }
            _ => vec![],
        }
    }

    /// Records the table a transactional write left behind (see `before_plan`).
    pub fn after_plan(&mut self, written: Vec<(String, String)>) {
        let mut state = self.db.lock().unwrap();
        for (db, table) in written {
            let Some(now) = state.schemas.get(&db).and_then(|s| s.tables.get(&table)).cloned()
            else {
                continue;
            };
            if let Some(entry) =
                state.open_txns.get_mut(&self.conn_id).and_then(|u| u.tables.get_mut(&(db, table)))
            {
                entry.1 = now;
            }
        }
    }

    pub fn execute(&mut self, sql: &str) -> Result<Vec<Vec<Value>>, MySqlError> {
        let dialect = MySqlDialect {};
        let mut asts = Parser::parse_sql(&dialect, sql)
            .map_err(|e| MySqlError::syntax_error(&e.to_string()))?;

        if asts.is_empty() {
            return Ok(vec![]);
        }

        let stmt = asts.remove(0);

        // Transaction control statements are handled here, at the
        // session/engine level, rather than as a `Plan` variant: they need
        // state (`tx_snapshot`) that lives across separate `execute` calls,
        // which `Executor` (built fresh per statement) doesn't have.
        match &stmt {
            Statement::StartTransaction { .. } => {
                // BEGIN inside a transaction commits it first, as in MySQL.
                self.commit();
                self.in_tx = true;
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::Commit { .. } => {
                self.commit();
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            // Connection-setup statements every real driver/framework sends
            // before its first query (pymysql/mysqlclient: `SET NAMES`;
            // Laravel/Rails/Django: `SET NAMES ... COLLATE`, `SET SESSION
            // sql_mode`, `SET SESSION TRANSACTION ISOLATION LEVEL`; JDBC:
            // `SHOW VARIABLES`, `SET character_set_results`). Found via
            // testing before a public release: every one of these used to
            // fail as "unsupported statement", so pymysql (and anything on
            // top of it: SQLAlchemy, Django) couldn't even connect. `SET` is
            // an accepted no-op: the connection is already utf8mb4 and this
            // engine has no per-session mode/charset/isolation state for it
            // to change.
            Statement::Set(set) => {
                // `SET autocommit = 0|1` is the one setting with an effect:
                // turning it back on commits an open transaction.
                if let Some(on) = bool_assignment(set, "autocommit") {
                    if on && !self.autocommit {
                        self.commit();
                    }
                    self.autocommit = on;
                }
                if let Some(n) = int_assignment(set, "innodb_lock_wait_timeout") {
                    self.lock_wait_timeout = n.max(1) as u64;
                }
                if let Some(on) = bool_assignment(set, "foreign_key_checks") {
                    self.fk_checks = on;
                }
                if let Some(mode) = sql_mode_assignment(set) {
                    self.sql_mode = mode;
                }
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::ShowVariables { filter, .. } => {
                self.last_affected_rows = 0;
                self.last_column_names = vec!["Variable_name".into(), "Value".into()];
                let mode = self.sql_mode.as_str();
                let autocommit = if self.autocommit { "ON" } else { "OFF" };
                let mut rows = show_filtered(SESSION_VARIABLES, filter.as_ref());
                for row in &mut rows {
                    match &row[0] {
                        Value::Text(n) if n == "sql_mode" => row[1] = Value::Text(mode.clone()),
                        Value::Text(n) if n == "autocommit" => {
                            row[1] = Value::Text(autocommit.into())
                        }
                        Value::Text(n) if n == "foreign_key_checks" => {
                            row[1] = Value::Text(if self.fk_checks { "ON" } else { "OFF" }.into())
                        }
                        _ => {}
                    }
                }
                return Ok(rows);
            }
            Statement::ShowStatus { filter, .. } => {
                self.last_affected_rows = 0;
                self.last_column_names = vec!["Variable_name".into(), "Value".into()];
                return Ok(show_filtered(STATUS_VARIABLES, filter.as_ref()));
            }
            Statement::ShowCollation { filter } => {
                self.last_affected_rows = 0;
                self.last_column_names =
                    ["Collation", "Charset", "Id", "Default", "Compiled", "Sortlen"]
                        .map(String::from)
                        .to_vec();
                let all = show_filtered(COLLATIONS, filter.as_ref());
                // `show_filtered` yields (name, charset) pairs; widen to the
                // real six-column SHOW COLLATION shape.
                return Ok(all
                    .into_iter()
                    .enumerate()
                    .map(|(i, mut r)| {
                        r.push(Value::Int(255 - i as i64));
                        r.push(Value::Text(if i == 0 { "Yes" } else { "" }.into()));
                        r.push(Value::Text("Yes".into()));
                        r.push(Value::Int(0));
                        r
                    })
                    .collect());
            }
            // `SHOW {INDEX|INDEXES|KEYS} {FROM|IN} t [{FROM|IN} db]`, which
            // sqlparser's MySQL dialect leaves as a bare word list.
            Statement::ShowVariable { variable }
                if variable.len() >= 3
                    && ["INDEX", "INDEXES", "KEYS"]
                        .iter()
                        .any(|w| variable[0].value.eq_ignore_ascii_case(w)) =>
            {
                let words: Vec<&str> = variable.iter().map(|i| i.value.as_str()).collect();
                let table = words[2];
                let db = match words.get(4) {
                    Some(d) => d.to_string(),
                    None => self
                        .current_db
                        .clone()
                        .ok_or_else(|| MySqlError::new(1046, "3D000", "No database selected"))?,
                };
                let t = {
                    let state = self.db.lock().unwrap();
                    crate::mysql::infoschema::lookup_table(&state, &db, table)
                }
                .ok_or_else(|| {
                    MySqlError::new(1146, "42S02", format!("Table '{db}.{table}' doesn't exist"))
                })?;
                self.last_affected_rows = 0;
                self.last_column_names =
                    crate::mysql::infoschema::SHOW_INDEX_COLUMNS.map(String::from).to_vec();
                return Ok(crate::mysql::infoschema::show_index(&t));
            }
            // `SHOW <word>` forms sqlparser has no dedicated node for.
            // Only the ones real clients actually send get an answer; any
            // other one still falls through to "unsupported" rather than a
            // made-up empty result.
            Statement::ShowVariable { variable }
                if variable.len() == 1
                    && ["WARNINGS", "ERRORS", "ENGINES"]
                        .iter()
                        .any(|w| variable[0].value.eq_ignore_ascii_case(w)) =>
            {
                self.last_affected_rows = 0;
                let word = variable[0].value.to_ascii_uppercase();
                if word == "ENGINES" {
                    self.last_column_names =
                        ["Engine", "Support", "Comment", "Transactions", "XA", "Savepoints"]
                            .map(String::from)
                            .to_vec();
                    return Ok(vec![
                        ["InnoDB", "DEFAULT", "noida-db in-memory engine", "YES", "NO", "NO"]
                            .map(|s| Value::Text(s.into()))
                            .to_vec(),
                    ]);
                }
                // No warnings channel exists, so there are never any to show.
                self.last_column_names = ["Level", "Code", "Message"].map(String::from).to_vec();
                return Ok(vec![]);
            }
            Statement::Savepoint { name } => {
                self.savepoint(&name.value);
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::ReleaseSavepoint { name } => {
                let Some(pos) =
                    self.savepoints.iter().rposition(|(n, _)| n.eq_ignore_ascii_case(&name.value))
                else {
                    return Err(MySqlError::new(
                        1305,
                        "42000",
                        format!("SAVEPOINT {} does not exist", name.value),
                    ));
                };
                self.savepoints.truncate(pos);
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::Rollback { savepoint: Some(name), .. } => {
                self.rollback_to(&name.value)?;
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            Statement::Rollback { .. } => {
                self.savepoints.clear();
                {
                    let mut state = self.db.lock().unwrap();
                    if let Some(undo) = state.open_txns.remove(&self.conn_id) {
                        state.undo(&undo);
                    }
                }
                self.in_tx = false;
                self.last_affected_rows = 0;
                self.last_column_names = Vec::new();
                return Ok(vec![]);
            }
            _ => {}
        }

        let mut binder = Binder::new(self.current_db.clone()).with_sql(sql);
        let plan = binder.bind_statement(stmt)?;
        self.last_column_names = {
            let state = self.db.lock().unwrap();
            plan::column_names(&plan, &state)
        };

        let (res, executor) = self.run_plan(plan, Vec::new());
        let res = res?;
        self.last_affected_rows = executor.last_affected_rows;
        self.last_insert_id = executor.last_insert_id;
        if executor.last_insert_id != 0 {
            self.session_insert_id = executor.last_insert_id;
        }
        self.last_found_rows = executor.last_found_rows;

        // USE changes the database; DROP DATABASE of the current one
        // clears it (DATABASE() is then NULL, as in MySQL).
        self.current_db = executor.current_db;

        Ok(res)
    }

    /// A new executor carrying this session's settings.
    pub fn executor(&self) -> Executor {
        let mut executor = Executor::new(self.db.clone(), self.current_db.clone());
        executor.last_found_rows = self.last_found_rows;
        executor.session_insert_id = self.session_insert_id;
        executor.sql_mode = self.sql_mode.clone();
        executor.autocommit = self.autocommit;
        executor.found_rows = self.found_rows;
        executor.fk_checks = self.fk_checks;
        executor.conn_id = self.conn_id;
        executor
    }

    /// Runs a bound statement (with `params` for a prepared one). A
    /// statement that needs a row another transaction holds waits for it,
    /// as InnoDB does: until that transaction ends, error 1205 after
    /// `innodb_lock_wait_timeout` seconds, or error 1213 (rolling this
    /// transaction back) if the two are waiting for each other.
    pub fn run_plan(
        &mut self,
        plan: Plan,
        params: Vec<Value>,
    ) -> (Result<Vec<Vec<Value>>, MySqlError>, Executor) {
        let written = self.before_plan(&plan);
        let started = std::time::Instant::now();
        loop {
            let mut executor = self.executor();
            executor.params = params.clone();
            let res = executor.execute_plan(plan.clone());
            let Some(holder) = res.as_ref().err().and_then(|e| e.lock_holder()) else {
                self.db.lock().unwrap().waits.remove(&self.conn_id);
                if res.is_ok() {
                    self.after_plan(written);
                }
                return (res, executor);
            };
            let deadlock = {
                let mut state = self.db.lock().unwrap();
                state.waits.insert(self.conn_id, holder);
                // Follow who the holder is waiting for, and so on.
                let mut at = holder;
                let mut cycle = false;
                for _ in 0..state.waits.len() + 1 {
                    match state.waits.get(&at) {
                        Some(&next) if next == self.conn_id => {
                            cycle = true;
                            break;
                        }
                        Some(&next) => at = next,
                        None => break,
                    }
                }
                if cycle {
                    state.waits.remove(&self.conn_id);
                }
                cycle
            };
            if deadlock {
                self.rollback();
                self.savepoints.clear();
                return (
                    Err(MySqlError::new(
                        1213,
                        "40001",
                        "Deadlock found when trying to get lock; try restarting transaction",
                    )),
                    executor,
                );
            }
            if started.elapsed().as_secs() >= self.lock_wait_timeout {
                self.db.lock().unwrap().waits.remove(&self.conn_id);
                return (
                    Err(MySqlError::new(
                        1205,
                        "HY000",
                        "Lock wait timeout exceeded; try restarting transaction",
                    )),
                    executor,
                );
            }
            std::thread::sleep(std::time::Duration::from_millis(5));
        }
    }

    pub fn use_db(&mut self, db: &str) {
        self.current_db = Some(db.to_string());
    }
}

/// What `SHOW [SESSION|GLOBAL] VARIABLES` reports. Values agree with what
/// `SELECT @@var` already returns for the names `Executor` knows (version
/// `8.0.33`, `max_allowed_packet`, `wait_timeout`, ...), so a driver that
/// reads the same setting both ways sees one consistent answer.
pub(crate) const SESSION_VARIABLES: &[(&str, &str)] = &[
    ("auto_increment_increment", "1"),
    ("auto_increment_offset", "1"),
    ("autocommit", "ON"),
    ("character_set_client", "utf8mb4"),
    ("character_set_connection", "utf8mb4"),
    ("character_set_database", "utf8mb4"),
    ("character_set_results", "utf8mb4"),
    ("character_set_server", "utf8mb4"),
    ("collation_connection", "utf8mb4_0900_ai_ci"),
    ("collation_database", "utf8mb4_0900_ai_ci"),
    ("collation_server", "utf8mb4_0900_ai_ci"),
    ("foreign_key_checks", "ON"),
    ("have_ssl", "DISABLED"),
    ("init_connect", ""),
    ("interactive_timeout", "28800"),
    ("license", "GPL"),
    ("lower_case_table_names", "0"),
    ("max_allowed_packet", "67108864"),
    ("net_buffer_length", "16384"),
    ("net_write_timeout", "60"),
    ("performance_schema", "OFF"),
    ("port", "3306"),
    ("socket", "/tmp/mysql.sock"),
    (
        "sql_mode",
        "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
    ),
    ("system_time_zone", "UTC"),
    ("time_zone", "SYSTEM"),
    ("transaction_isolation", "REPEATABLE-READ"),
    ("tx_isolation", "REPEATABLE-READ"),
    ("version", "8.0.33"),
    ("version_comment", "noida-db MySQL 8.0"),
    ("wait_timeout", "28800"),
];

const STATUS_VARIABLES: &[(&str, &str)] = &[("Threads_connected", "1"), ("Uptime", "1")];

/// `(collation, charset)` pairs for `SHOW COLLATION`; the first is the default.
const COLLATIONS: &[(&str, &str)] = &[
    ("utf8mb4_0900_ai_ci", "utf8mb4"),
    ("utf8mb4_general_ci", "utf8mb4"),
    ("utf8mb4_unicode_ci", "utf8mb4"),
    ("utf8mb4_bin", "utf8mb4"),
];

/// Applies a `SHOW ... LIKE 'pattern'` filter to a two-column name/value
/// table (MySQL's `LIKE` here matches the first column, case-insensitively).
/// A `WHERE` filter isn't evaluated -- every row is returned, which only
/// ever over-reports to clients that look values up by name (JDBC's old
/// `SHOW VARIABLES WHERE Variable_name = ...` probe), never drops one.
fn show_filtered(table: &[(&str, &str)], filter: Option<&ShowStatementFilter>) -> Vec<Vec<Value>> {
    let pattern = match filter {
        Some(ShowStatementFilter::Like(p)) | Some(ShowStatementFilter::NoKeyword(p)) => {
            Some(p.as_str())
        }
        _ => None,
    };
    table
        .iter()
        .filter(|(name, _)| {
            pattern.is_none_or(|p| crate::mysql::exec::mysql_like(name, p, Some('\\')))
        })
        .map(|(n, v)| vec![Value::Text((*n).into()), Value::Text((*v).into())])
        .collect()
}

/// `Some(mode)` if `set` assigns `sql_mode` (`SET sql_mode = '...'`,
/// `SET SESSION sql_mode = ...`, `SET @@sql_mode = DEFAULT`, ...).
fn sql_mode_assignment(set: &sqlparser::ast::Set) -> Option<crate::mysql::sqlmode::SqlMode> {
    use crate::mysql::sqlmode::SqlMode;
    use sqlparser::ast::{Expr as E, Set, Value as V};
    let pairs: Vec<(String, &E)> = match set {
        Set::SingleAssignment { variable, values, .. } => {
            values.first().map(|v| vec![(variable.to_string(), v)]).unwrap_or_default()
        }
        Set::MultipleAssignments { assignments } => {
            assignments.iter().map(|a| (a.name.to_string(), &a.value)).collect()
        }
        _ => vec![],
    };
    let mut out = None;
    for (name, value) in pairs {
        let name = name.trim_start_matches('@').to_ascii_lowercase();
        if name.rsplit('.').next() != Some("sql_mode") {
            continue;
        }
        out = match value {
            E::Value(v) => match &v.value {
                V::SingleQuotedString(s) | V::DoubleQuotedString(s) => Some(SqlMode::parse(s)),
                _ => None,
            },
            E::Identifier(i) if i.value.eq_ignore_ascii_case("default") => Some(SqlMode::default()),
            E::Identifier(i) => Some(SqlMode::parse(&i.value)),
            _ => None,
        }
        .or(out);
    }
    out
}

/// `Some(on)` if `set` assigns `autocommit` (`SET autocommit = 0`,
/// `SET @@autocommit = 1`, `SET SESSION autocommit = OFF`, ...).
/// `Some(n)` if `set` assigns the integer variable `var`.
fn int_assignment(set: &sqlparser::ast::Set, var: &str) -> Option<i64> {
    use sqlparser::ast::{Expr as E, Set, Value as V};
    let pairs: Vec<(String, &E)> = match set {
        Set::SingleAssignment { variable, values, .. } => {
            values.first().map(|v| vec![(variable.to_string(), v)]).unwrap_or_default()
        }
        Set::MultipleAssignments { assignments } => {
            assignments.iter().map(|a| (a.name.to_string(), &a.value)).collect()
        }
        _ => vec![],
    };
    pairs.into_iter().rev().find_map(|(name, value)| {
        let name = name.trim_start_matches('@').to_ascii_lowercase();
        if name.rsplit('.').next() != Some(var) {
            return None;
        }
        match value {
            E::Value(v) => match &v.value {
                V::Number(n, _) => n.parse().ok(),
                _ => None,
            },
            _ => None,
        }
    })
}

fn bool_assignment(set: &sqlparser::ast::Set, var: &str) -> Option<bool> {
    use sqlparser::ast::{Expr as E, Set, Value as V};
    let pairs: Vec<(String, &E)> = match set {
        Set::SingleAssignment { variable, values, .. } => {
            values.first().map(|v| vec![(variable.to_string(), v)]).unwrap_or_default()
        }
        Set::MultipleAssignments { assignments } => {
            assignments.iter().map(|a| (a.name.to_string(), &a.value)).collect()
        }
        _ => vec![],
    };
    let mut out = None;
    for (name, value) in pairs {
        let name = name.trim_start_matches('@').to_ascii_lowercase();
        if name.rsplit('.').next() != Some(var) {
            continue;
        }
        out = match value {
            E::Value(v) => match &v.value {
                V::Number(n, _) => Some(n != "0"),
                V::Boolean(b) => Some(*b),
                V::SingleQuotedString(s) => Some(!s.eq_ignore_ascii_case("off") && s != "0"),
                _ => None,
            },
            E::Identifier(i) => {
                Some(i.value.eq_ignore_ascii_case("on") || i.value.eq_ignore_ascii_case("true"))
            }
            _ => None,
        }
        .or(out);
    }
    out
}
