use crate::mysql::catalog::{Column, DbState, Table};
use crate::mysql::error::MySqlError;
use crate::mysql::plan::{AggFunc, ArithOp, CmpOp, Expr, JoinOp, Plan};
use crate::mysql::types::Value;
use std::cmp::Ordering;
use std::sync::{Arc, Mutex};

pub struct Executor {
    pub db: Arc<Mutex<DbState>>,
    pub current_db: Option<String>,
    /// Values bound to `Expr::Param(i)` placeholders for this execution
    /// (from `COM_STMT_EXECUTE`'s parameter section), indexed the same way
    /// `Binder::param_counter` assigned them. Empty for a plain `COM_QUERY`
    /// or a parameterless prepared statement.
    pub params: Vec<Value>,
    /// Rows actually affected by the last `INSERT`/`UPDATE`/`DELETE` this
    /// executor ran, so the caller can report a real count in the OK
    /// packet instead of always claiming 0.
    pub last_affected_rows: u64,
    /// The AUTO_INCREMENT value generated by the last `INSERT`, if any --
    /// real MySQL's `LAST_INSERT_ID()` (and the OK packet's own field)
    /// report the *first* generated id of a multi-row INSERT, not the
    /// last, so that's what this tracks. 0 if the last statement wasn't an
    /// INSERT that generated one.
    pub last_insert_id: u64,
    /// The row count `SQL_CALC_FOUND_ROWS` computed (before `LIMIT`
    /// truncation) for the most recent query that used it, for a later
    /// `FOUND_ROWS()` call to read. Unlike `last_insert_id`/
    /// `last_affected_rows`, callers seed this from the connection's
    /// previous value before executing a statement (see `Engine::execute`
    /// and the `COM_STMT_EXECUTE` handler), since -- matching real
    /// MySQL -- it persists across intervening statements rather than
    /// resetting to 0 each time.
    pub last_found_rows: u64,
}

impl Executor {
    pub fn new(db: Arc<Mutex<DbState>>, current_db: Option<String>) -> Self {
        Self {
            db,
            current_db,
            params: Vec::new(),
            last_affected_rows: 0,
            last_insert_id: 0,
            last_found_rows: 0,
        }
    }

    /// Finds the `Table` a plan's rows ultimately come from, for resolving
    /// `Expr::ColName` by name in `Filter`/`Project`. Looks through any
    /// chain of single-source wrapper nodes (`Filter`, `Project`) down to
    /// the underlying `Scan` — a bare `match` on `Plan::Scan` alone missed
    /// this for anything with a `WHERE` clause, since that wraps the scan
    /// in `Plan::Filter` first, silently resolving every column reference
    /// to `Value::Null` instead of erroring or working.
    fn resolve_table_context(&self, plan: &Plan) -> Result<Option<Table>, MySqlError> {
        match plan {
            Plan::Scan { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema.tables.get(table).ok_or_else(|| MySqlError::unknown_table(table))?;
                Ok(Some((**t).clone()))
            }
            Plan::Filter { source, .. } => self.resolve_table_context(source),
            Plan::Project { source, .. } => self.resolve_table_context(source),
            Plan::Sort { source, .. } => self.resolve_table_context(source),
            Plan::Join { left, right, .. } => {
                let l = self.resolve_table_context(left)?;
                let r = self.resolve_table_context(right)?;
                Ok(merge_table_contexts(l, r))
            }
            _ => Ok(None),
        }
    }

    pub fn execute_plan(&mut self, plan: Plan) -> Result<Vec<Vec<Value>>, MySqlError> {
        match plan {
            Plan::Dummy => Ok(vec![vec![]]),
            Plan::ShowDatabases => Ok(vec![
                vec![Value::Text("information_schema".to_string())],
                vec![Value::Text("mysql".to_string())],
                vec![Value::Text("performance_schema".to_string())],
                vec![Value::Text("sys".to_string())],
                vec![Value::Text("test".to_string())],
            ]),
            Plan::Use(db) => {
                let state = self.db.lock().unwrap();
                if !state.schemas.contains_key(&db) {
                    return Err(MySqlError::new(
                        1049,
                        "42000",
                        format!("Unknown database '{}'", db),
                    ));
                }
                self.current_db = Some(db);
                Ok(vec![])
            }
            Plan::ShowTables(db) => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let mut rows = Vec::new();
                for table_name in schema.tables.keys() {
                    rows.push(vec![Value::Text(table_name.clone())]);
                }
                Ok(rows)
            }
            Plan::ShowColumns { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t =
                    schema.tables.get(&table).ok_or_else(|| MySqlError::unknown_table(&table))?;
                let mut rows = Vec::new();
                for col in &t.columns {
                    rows.push(vec![
                        Value::Text(col.name.clone()),
                        Value::Text(format!("{:?}", col.ty)),
                        Value::Text(if col.not_null {
                            "NO".to_string()
                        } else {
                            "YES".to_string()
                        }),
                        Value::Text(if col.primary_key {
                            "PRI".to_string()
                        } else {
                            "".to_string()
                        }),
                        col.default.clone().unwrap_or(Value::Null),
                        Value::Text(if col.auto_increment {
                            "auto_increment".to_string()
                        } else {
                            "".to_string()
                        }),
                    ]);
                }
                Ok(rows)
            }
            Plan::ShowCreateTable { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t =
                    schema.tables.get(&table).ok_or_else(|| MySqlError::unknown_table(&table))?;

                let mut sql = format!("CREATE TABLE `{}` (\n", t.name);
                let mut cols_sql = Vec::new();
                for col in &t.columns {
                    let mut col_sql = format!("  `{}` {:?}", col.name, col.ty);
                    if col.not_null {
                        col_sql.push_str(" NOT NULL");
                    }
                    if col.auto_increment {
                        col_sql.push_str(" AUTO_INCREMENT");
                    }
                    if col.primary_key {
                        col_sql.push_str(" PRIMARY KEY");
                    }
                    cols_sql.push(col_sql);
                }
                sql.push_str(&cols_sql.join(",\n"));
                sql.push_str("\n) ENGINE=InnoDB");

                Ok(vec![vec![Value::Text(t.name.clone()), Value::Text(sql)]])
            }
            Plan::CreateTable { db, table, columns } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                if schema.tables.contains_key(&table) {
                    return Err(MySqlError::new(
                        1050,
                        "42S01",
                        format!("Table '{}' already exists", table),
                    ));
                }
                schema.tables.insert(table.clone(), Arc::new(Table::new(table, columns)));
                Ok(vec![])
            }
            Plan::CreateDatabase { name, if_not_exists } => {
                let mut state = self.db.lock().unwrap();
                if state.schemas.contains_key(&name) {
                    if if_not_exists {
                        return Ok(vec![]);
                    }
                    return Err(MySqlError::new(
                        1007,
                        "HY000",
                        format!("Can't create database '{name}'; database exists"),
                    ));
                }
                state.schemas.insert(name, crate::mysql::catalog::Schema::default());
                Ok(vec![])
            }
            Plan::CreateIndex { db, table, columns, if_not_exists } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = match schema.tables.get(&table) {
                    Some(t) => t,
                    None if if_not_exists => return Ok(vec![]),
                    None => return Err(MySqlError::unknown_table(&table)),
                };
                for col in &columns {
                    if !t.columns.iter().any(|c| c.name == *col) {
                        return Err(MySqlError::new(
                            1072,
                            "42000",
                            format!("Key column '{col}' doesn't exist in table"),
                        ));
                    }
                }
                Ok(vec![])
            }
            Plan::Insert { db, table, columns, rows } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema
                    .tables
                    .get_mut(&table)
                    .ok_or_else(|| MySqlError::unknown_table(&table))?;
                let t_mut = Arc::make_mut(t);
                let affected = rows.len() as u64;
                let mut first_generated_id: Option<i64> = None;

                for row_exprs in rows {
                    let mut new_row = vec![Value::Null; t_mut.columns.len()];

                    let mut col_indices = Vec::new();
                    if columns.is_empty() {
                        for i in 0..t_mut.columns.len() {
                            col_indices.push(i);
                        }
                    } else {
                        for col_name in &columns {
                            let idx = t_mut
                                .columns
                                .iter()
                                .position(|c| c.name == *col_name)
                                .ok_or_else(|| MySqlError::unknown_column(col_name))?;
                            col_indices.push(idx);
                        }
                    }

                    if row_exprs.len() != col_indices.len() {
                        return Err(MySqlError::new(
                            1136,
                            "21S01",
                            "Column count doesn't match value count at row 1",
                        ));
                    }

                    for (i, expr) in row_exprs.iter().enumerate() {
                        let val = self.eval_expr(expr, &[], None)?;
                        new_row[col_indices[i]] = val;
                    }

                    for (i, col) in t_mut.columns.iter().enumerate() {
                        if new_row[i].is_null() {
                            if col.auto_increment {
                                new_row[i] = Value::Int(t_mut.next_auto_increment);
                                first_generated_id.get_or_insert(t_mut.next_auto_increment);
                                t_mut.next_auto_increment += 1;
                            } else if let Some(def) = &col.default {
                                new_row[i] = def.clone();
                            } else if col.not_null {
                                return Err(MySqlError::new(
                                    1364,
                                    "HY000",
                                    format!("Field '{}' doesn't have a default value", col.name),
                                ));
                            }
                        }
                    }

                    t_mut.rows.push(new_row);
                }

                self.last_affected_rows = affected;
                self.last_insert_id = first_generated_id.map(|v| v as u64).unwrap_or(0);
                Ok(vec![])
            }
            Plan::Update { db, table, assignments, selection } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema
                    .tables
                    .get_mut(&table)
                    .ok_or_else(|| MySqlError::unknown_table(&table))?;
                let t_mut = Arc::make_mut(t);
                let mut affected = 0u64;

                for i in 0..t_mut.rows.len() {
                    let mut matches = true;
                    if let Some(sel) = &selection {
                        let val = self.eval_expr(sel, &t_mut.rows[i], Some(&*t_mut))?;
                        if val.is_null() || val == Value::Int(0) {
                            matches = false;
                        }
                    }

                    if matches {
                        affected += 1;
                        for (col_name, expr) in &assignments {
                            let idx = t_mut
                                .columns
                                .iter()
                                .position(|c| c.name == *col_name)
                                .ok_or_else(|| MySqlError::unknown_column(col_name))?;
                            let val = self.eval_expr(expr, &t_mut.rows[i], Some(&*t_mut))?;
                            t_mut.rows[i][idx] = val;
                        }
                    }
                }

                self.last_affected_rows = affected;
                Ok(vec![])
            }
            Plan::Delete { db, table, selection } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema
                    .tables
                    .get_mut(&table)
                    .ok_or_else(|| MySqlError::unknown_table(&table))?;
                let t_mut = Arc::make_mut(t);

                let mut new_rows = Vec::new();
                for row in &t_mut.rows {
                    let mut matches = true;
                    if let Some(sel) = &selection {
                        let val = self.eval_expr(sel, row, Some(&*t_mut))?;
                        if val.is_null() || val == Value::Int(0) {
                            matches = false;
                        }
                    }

                    if !matches {
                        new_rows.push(row.clone());
                    }
                }
                self.last_affected_rows = (t_mut.rows.len() - new_rows.len()) as u64;
                t_mut.rows = new_rows;

                Ok(vec![])
            }
            Plan::Scan { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t =
                    schema.tables.get(&table).ok_or_else(|| MySqlError::unknown_table(&table))?;
                Ok(t.rows.clone())
            }
            Plan::Filter { source, predicate } => {
                let table_context = self.resolve_table_context(&source)?;

                let rows = self.execute_plan(*source)?;
                let mut out_rows = Vec::new();
                for row in rows {
                    let val = self.eval_expr(&predicate, &row, table_context.as_ref())?;
                    if !val.is_null() && val != Value::Int(0) {
                        out_rows.push(row);
                    }
                }
                Ok(out_rows)
            }
            Plan::Project { source, exprs, .. } => {
                let table_context = self.resolve_table_context(&source)?;

                let rows = self.execute_plan(*source)?;
                let mut out_rows = Vec::new();
                for row in rows {
                    let mut out_row = Vec::new();
                    for expr in &exprs {
                        if matches!(expr, Expr::Wildcard) {
                            // Expands to every column of the current row,
                            // not one value -- see `Expr::Wildcard`'s own
                            // doc comment.
                            out_row.extend(row.iter().cloned());
                        } else {
                            out_row.push(self.eval_expr(expr, &row, table_context.as_ref())?);
                        }
                    }
                    out_rows.push(out_row);
                }
                Ok(out_rows)
            }
            Plan::Aggregate { source, group_exprs, exprs, having, .. } => {
                let table_context = self.resolve_table_context(&source)?;
                let rows = self.execute_plan(*source)?;

                // Group rows by the evaluated GROUP BY key. `Value`'s
                // `PartialEq` (via `Vec<Value>`) is enough to compare keys
                // here — linear search per row is fine at this project's
                // "simple over performant, local-use only" scale. No
                // GROUP BY clause but an aggregate in the projection means
                // the whole input is a single implicit group (possibly
                // empty, e.g. `SELECT COUNT(*) FROM t` on an empty table).
                let mut groups: Vec<(Vec<Value>, Vec<Vec<Value>>)> = Vec::new();
                if group_exprs.is_empty() {
                    groups.push((Vec::new(), rows));
                } else {
                    for row in rows {
                        let key = group_exprs
                            .iter()
                            .map(|e| self.eval_expr(e, &row, table_context.as_ref()))
                            .collect::<Result<Vec<_>, _>>()?;
                        if let Some(g) = groups.iter_mut().find(|(k, _)| *k == key) {
                            g.1.push(row);
                        } else {
                            groups.push((key, vec![row]));
                        }
                    }
                }

                let mut out_rows = Vec::new();
                for (_key, group_rows) in &groups {
                    if let Some(having) = &having {
                        let val =
                            self.eval_group_expr(having, group_rows, table_context.as_ref())?;
                        if val.is_null() || val == Value::Int(0) {
                            continue;
                        }
                    }
                    let mut out_row = Vec::new();
                    for expr in &exprs {
                        out_row.push(self.eval_group_expr(
                            expr,
                            group_rows,
                            table_context.as_ref(),
                        )?);
                    }
                    out_rows.push(out_row);
                }
                Ok(out_rows)
            }
            Plan::Sort { source, keys, limit, offset, calc_found_rows } => {
                let table_context = self.resolve_table_context(&source)?;
                let mut rows = self.execute_plan(*source)?;

                if calc_found_rows {
                    self.last_found_rows = rows.len() as u64;
                }

                if !keys.is_empty() {
                    // Evaluate every sort key once per row up front rather
                    // than re-evaluating expressions on every comparison
                    // during the sort.
                    let mut keyed: Vec<(Vec<Value>, Vec<Value>)> = Vec::with_capacity(rows.len());
                    for row in rows {
                        let key = keys
                            .iter()
                            .map(|(e, _)| self.eval_expr(e, &row, table_context.as_ref()))
                            .collect::<Result<Vec<_>, _>>()?;
                        keyed.push((key, row));
                    }
                    keyed.sort_by(|(ka, _), (kb, _)| {
                        for (i, (_, asc)) in keys.iter().enumerate() {
                            let ord = sort_cmp(&ka[i], &kb[i]);
                            let ord = if *asc { ord } else { ord.reverse() };
                            if ord != Ordering::Equal {
                                return ord;
                            }
                        }
                        Ordering::Equal
                    });
                    rows = keyed.into_iter().map(|(_, row)| row).collect();
                }

                let start = offset.unwrap_or(0) as usize;
                rows = rows.into_iter().skip(start).collect();
                if let Some(limit) = limit {
                    rows.truncate(limit as usize);
                }
                Ok(rows)
            }
            Plan::Join { left, right, op } => {
                // Found via testing before a public release: every join's
                // ON condition used to be evaluated with no table context
                // at all (`eval_expr(&cond, &row, None)`), so every column
                // reference inside it resolved to NULL unconditionally --
                // meaning the condition was always NULL, never true, and
                // every single JOIN (of any kind) silently returned the
                // wrong result (INNER: always empty; LEFT: always every
                // left row with the right side all-NULL) with no error at
                // all. Resolving column names needs *both* sides' columns
                // in scope, concatenated the same way the row itself is
                // (`left columns ++ right columns`), not just one table's.
                let l_table = self.resolve_table_context(&left)?;
                let r_table = self.resolve_table_context(&right)?;
                let join_table = merge_table_contexts(l_table, r_table);
                let l_rows = self.execute_plan(*left)?;
                let r_rows = self.execute_plan(*right)?;
                let mut out_rows = Vec::new();

                match op {
                    JoinOp::Cross => {
                        for l in &l_rows {
                            for r in &r_rows {
                                let mut row = l.clone();
                                row.extend(r.clone());
                                out_rows.push(row);
                            }
                        }
                    }
                    JoinOp::Inner(cond) => {
                        for l in &l_rows {
                            for r in &r_rows {
                                let mut row = l.clone();
                                row.extend(r.clone());
                                let val = self.eval_expr(&cond, &row, join_table.as_ref())?;
                                if !val.is_null() && val != Value::Int(0) {
                                    out_rows.push(row);
                                }
                            }
                        }
                    }
                    JoinOp::Left(cond) => {
                        let r_len = if r_rows.is_empty() { 0 } else { r_rows[0].len() };
                        for l in &l_rows {
                            let mut matched = false;
                            for r in &r_rows {
                                let mut row = l.clone();
                                row.extend(r.clone());
                                let val = self.eval_expr(&cond, &row, join_table.as_ref())?;
                                if !val.is_null() && val != Value::Int(0) {
                                    out_rows.push(row);
                                    matched = true;
                                }
                            }
                            if !matched {
                                let mut row = l.clone();
                                row.extend(vec![Value::Null; r_len]);
                                out_rows.push(row);
                            }
                        }
                    }
                }
                Ok(out_rows)
            }
        }
    }

    fn eval_expr(
        &self,
        expr: &Expr,
        row: &[Value],
        table: Option<&Table>,
    ) -> Result<Value, MySqlError> {
        match expr {
            Expr::Const(v) => Ok(v.clone()),
            Expr::Param(i) => Ok(self.params.get(*i).cloned().unwrap_or(Value::Null)),
            Expr::Col(i) => Ok(row.get(*i).cloned().unwrap_or(Value::Null)),
            Expr::FoundRows => Ok(Value::Int(self.last_found_rows as i64)),
            Expr::ColName(name) => {
                if let Some(t) = table
                    && let Some(idx) = resolve_column_index(&t.columns, name)
                {
                    return Ok(row.get(idx).cloned().unwrap_or(Value::Null));
                }
                Ok(Value::Null) // For simplicity, return Null if column not found or no table context
            }
            Expr::And(exprs) => {
                let mut res = Value::Int(1);
                for e in exprs {
                    let v = self.eval_expr(e, row, table)?;
                    if v.is_null() {
                        res = Value::Null;
                    } else if v == Value::Int(0) {
                        return Ok(Value::Int(0));
                    }
                }
                Ok(res)
            }
            Expr::Or(exprs) => {
                let mut res = Value::Int(0);
                for e in exprs {
                    let v = self.eval_expr(e, row, table)?;
                    if v == Value::Int(1) {
                        return Ok(Value::Int(1));
                    } else if v.is_null() {
                        res = Value::Null;
                    }
                }
                Ok(res)
            }
            Expr::Arith { op, left, right } => {
                let l = self.eval_expr(left, row, table)?;
                let r = self.eval_expr(right, row, table)?;
                eval_arith(*op, l, r)
            }
            Expr::Compare { op, left, right } => {
                let l = self.eval_expr(left, row, table)?;
                let r = self.eval_expr(right, row, table)?;
                eval_compare(*op, l, r)
            }
            Expr::InList { expr, list, negated } => {
                let l = self.eval_expr(expr, row, table)?;
                let mut items = Vec::with_capacity(list.len());
                for item in list {
                    items.push(self.eval_expr(item, row, table)?);
                }
                eval_in_list(l, &items, *negated)
            }
            Expr::SysVar(name) => {
                if name.eq_ignore_ascii_case("version") {
                    Ok(Value::Text("8.0.33".to_string()))
                } else if name.eq_ignore_ascii_case("version_comment") {
                    Ok(Value::Text("noida-db MySQL 8.0".to_string()))
                } else if name.eq_ignore_ascii_case("max_allowed_packet") {
                    Ok(Value::Int(67108864))
                } else if name.eq_ignore_ascii_case("lower_case_table_names") {
                    Ok(Value::Int(0))
                } else if name.eq_ignore_ascii_case("wait_timeout")
                    || name.eq_ignore_ascii_case("interactive_timeout")
                {
                    // Real MySQL default (seconds); client pools (e.g.
                    // mysql_async's connection setup probe) parse this as
                    // a number, so it can't be the empty-text fallback.
                    Ok(Value::Int(28800))
                } else if name.eq_ignore_ascii_case("socket") {
                    Ok(Value::Text("/tmp/mysql.sock".to_string()))
                } else {
                    Ok(Value::Text("".to_string()))
                }
            }
            Expr::Not(e) => {
                let v = self.eval_expr(e, row, table)?;
                if v.is_null() {
                    Ok(Value::Null)
                } else if v == Value::Int(0) {
                    Ok(Value::Int(1))
                } else {
                    Ok(Value::Int(0))
                }
            }
            Expr::IsNull(e, negated) => {
                let v = self.eval_expr(e, row, table)?;
                let is_null = v.is_null();
                Ok(Value::Int((is_null != *negated) as i64))
            }
            Expr::Like { expr, pattern, escape, negated } => {
                let v = self.eval_expr(expr, row, table)?;
                let p = self.eval_expr(pattern, row, table)?;
                let esc = self.eval_expr(escape, row, table)?;
                if v.is_null() || p.is_null() {
                    return Ok(Value::Null);
                }
                let (Some(s), Some(pat)) = (value_as_text(&v), value_as_text(&p)) else {
                    return Ok(Value::Null);
                };
                let esc_char = value_as_text(&esc).and_then(|e| e.chars().next());
                let m = mysql_like(&s, &pat, esc_char);
                Ok(Value::Int((m != *negated) as i64))
            }
            Expr::Case { conditions, else_result } => {
                for (cond, result) in conditions {
                    let c = self.eval_expr(cond, row, table)?;
                    if !c.is_null() && c != Value::Int(0) {
                        return self.eval_expr(result, row, table);
                    }
                }
                match else_result {
                    Some(e) => self.eval_expr(e, row, table),
                    None => Ok(Value::Null),
                }
            }
            Expr::Call { name, args } => {
                let vals: Vec<Value> =
                    args.iter().map(|a| self.eval_expr(a, row, table)).collect::<Result<_, _>>()?;
                eval_call(name, &vals)
            }
            _ => Err(MySqlError::unsupported("expr in execution")),
        }
    }

    /// Evaluates a projection expression against one group of rows
    /// (`Plan::Aggregate`'s output). Any `Expr::Agg` found — including
    /// nested inside arithmetic/boolean combinators, e.g. `COUNT(x) + 1`
    /// — is computed over the whole group; every other leaf expression
    /// (a bare grouped column, a literal, `?`, `@@var`) is evaluated
    /// against the group's first row, since a non-aggregated column in a
    /// `GROUP BY` query is only meaningful when it's constant within the
    /// group (matching every real column reference this binder produces:
    /// the `GROUP BY` key columns themselves).
    fn eval_group_expr(
        &self,
        expr: &Expr,
        rows: &[Vec<Value>],
        table: Option<&Table>,
    ) -> Result<Value, MySqlError> {
        match expr {
            Expr::Agg { func, arg } => {
                if matches!(func, AggFunc::CountStar) {
                    return Ok(Value::Int(rows.len() as i64));
                }
                let arg = arg
                    .as_ref()
                    .ok_or_else(|| MySqlError::unsupported("aggregate without argument"))?;
                let vals: Vec<Value> =
                    rows.iter().map(|r| self.eval_expr(arg, r, table)).collect::<Result<_, _>>()?;
                Ok(compute_agg(*func, &vals))
            }
            Expr::Arith { op, left, right } => {
                let l = self.eval_group_expr(left, rows, table)?;
                let r = self.eval_group_expr(right, rows, table)?;
                eval_arith(*op, l, r)
            }
            Expr::Compare { op, left, right } => {
                let l = self.eval_group_expr(left, rows, table)?;
                let r = self.eval_group_expr(right, rows, table)?;
                eval_compare(*op, l, r)
            }
            Expr::And(exprs) => {
                let mut res = Value::Int(1);
                for e in exprs {
                    let v = self.eval_group_expr(e, rows, table)?;
                    if v.is_null() {
                        res = Value::Null;
                    } else if v == Value::Int(0) {
                        return Ok(Value::Int(0));
                    }
                }
                Ok(res)
            }
            Expr::Or(exprs) => {
                let mut res = Value::Int(0);
                for e in exprs {
                    let v = self.eval_group_expr(e, rows, table)?;
                    if v == Value::Int(1) {
                        return Ok(Value::Int(1));
                    } else if v.is_null() {
                        res = Value::Null;
                    }
                }
                Ok(res)
            }
            _ => {
                if let Some(row) = rows.first() {
                    self.eval_expr(expr, row, table)
                } else {
                    Ok(Value::Null)
                }
            }
        }
    }
}

/// `ORDER BY`'s own comparator: unlike `value_partial_cmp` (used by
/// `MIN`/`MAX`, which skip NULLs entirely), a sort has to place every row
/// somewhere, so NULL sorts first in ascending order (real MySQL's rule;
/// `Plan::Sort`'s execution reverses the whole comparison for `DESC`, which
/// correctly puts NULLs last in that case too, matching MySQL). Two
/// otherwise-incomparable values (e.g. text vs. a number) are treated as
/// equal rather than panicking or being arbitrarily ordered.
fn sort_cmp(a: &Value, b: &Value) -> Ordering {
    match (a.is_null(), b.is_null()) {
        (true, true) => return Ordering::Equal,
        (true, false) => return Ordering::Less,
        (false, true) => return Ordering::Greater,
        (false, false) => {}
    }
    value_partial_cmp(a, b).unwrap_or(Ordering::Equal)
}

/// Ordering used by `MIN`/`MAX`: numeric values compare numerically, text
/// compares lexically, matching `eval_compare`'s own rules. `None` (e.g.
/// comparing a number against text) means the two aren't ordered against
/// each other — the caller treats that as "keep the earlier value".
fn value_partial_cmp(a: &Value, b: &Value) -> Option<Ordering> {
    match (a, b) {
        (Value::Text(x), Value::Text(y)) => x.partial_cmp(y),
        _ => {
            let as_f64 = |v: &Value| match v {
                Value::Int(i) => Some(*i as f64),
                Value::Float(f) => Some(*f),
                _ => None,
            };
            match (as_f64(a), as_f64(b)) {
                (Some(x), Some(y)) => x.partial_cmp(&y),
                _ => None,
            }
        }
    }
}

/// `COUNT`/`SUM`/`AVG`/`MIN`/`MAX` over one group's evaluated values.
/// `COUNT(*)` is handled by the caller before reaching here (it needs the
/// row count, not evaluated values). NULLs are skipped, matching MySQL;
/// an all-NULL (or empty) group's `SUM`/`AVG`/`MIN`/`MAX` is NULL.
fn compute_agg(func: AggFunc, vals: &[Value]) -> Value {
    let non_null: Vec<&Value> = vals.iter().filter(|v| !v.is_null()).collect();
    match func {
        AggFunc::CountStar => Value::Int(vals.len() as i64),
        AggFunc::Count => Value::Int(non_null.len() as i64),
        AggFunc::Sum => {
            if non_null.is_empty() {
                return Value::Null;
            }
            let all_int = non_null.iter().all(|v| matches!(v, Value::Int(_)));
            let sum: f64 = non_null
                .iter()
                .map(|v| match v {
                    Value::Int(i) => *i as f64,
                    Value::Float(f) => *f,
                    _ => 0.0,
                })
                .sum();
            if all_int { Value::Int(sum as i64) } else { Value::Float(sum) }
        }
        AggFunc::Avg => {
            if non_null.is_empty() {
                return Value::Null;
            }
            let sum: f64 = non_null
                .iter()
                .map(|v| match v {
                    Value::Int(i) => *i as f64,
                    Value::Float(f) => *f,
                    _ => 0.0,
                })
                .sum();
            Value::Float(sum / non_null.len() as f64)
        }
        AggFunc::Min => non_null
            .into_iter()
            .cloned()
            .min_by(|a, b| value_partial_cmp(a, b).unwrap_or(Ordering::Equal))
            .unwrap_or(Value::Null),
        AggFunc::Max => non_null
            .into_iter()
            .cloned()
            .max_by(|a, b| value_partial_cmp(a, b).unwrap_or(Ordering::Equal))
            .unwrap_or(Value::Null),
    }
}

/// MySQL's lenient string-to-number coercion for a mixed-type comparison
/// or arithmetic operand: parses the longest leading prefix of `s` that
/// looks like a number (optional sign, digits, optional decimal point and
/// more digits) and falls back to 0.0 for anything else, including empty
/// input (e.g. `wp_posts.post_parent = 4` compared against a `Text`-typed
/// "0"/"4" -- a real, common shape for WordPress's own generated SQL).
/// Real MySQL only ever warns about this ("Truncated incorrect DOUBLE
/// value"), it never aborts the query; this engine has no warnings
/// channel to surface that softer signal through, so dropping the
/// warning silently is the closest faithful behavior, not erroring
/// outright.
fn mysql_text_to_f64(s: &str) -> f64 {
    let s = s.trim_start();
    let mut end = 0;
    for (i, c) in s.char_indices() {
        let ok = c.is_ascii_digit()
            || (i == 0 && (c == '+' || c == '-'))
            || (c == '.' && !s[..i].contains('.'));
        if !ok {
            break;
        }
        end = i + c.len_utf8();
    }
    s[..end].parse::<f64>().unwrap_or(0.0)
}

/// Builds the combined column list a joined row's `ColName` lookups
/// resolve against: the left side's real columns followed by the right
/// side's, in the same order `Plan::Join`'s own execution concatenates the
/// two rows (`left_row ++ right_row`) -- so a column's position in this
/// synthetic `Table` always matches its position in the actual row data.
/// Only the `columns` field is ever read back off the result (`rows` and
/// `next_auto_increment` are meaningless for it), so those are left at
/// `Table::new`'s own empty defaults.
///
/// Each merged column is renamed to `"<source table>.<column>"` (using
/// the real table each side's `Table::name` carries), *not* left as its
/// own bare name -- found via testing before a public release:
/// `cust.id`/`orders.id` across a join both resolving by bare name to
/// whichever table's `id` happened to come first, regardless of which one
/// was actually named, silently returned the wrong table's value. Because
/// `resolve_column_index` tries an exact match against the sought name
/// before ever falling back to a bare-suffix match, a genuinely qualified
/// reference (which the binder now always preserves in full, see its own
/// `AstExpr::CompoundIdentifier` comment) matches its real column exactly;
/// only a genuinely unqualified, genuinely ambiguous bare reference
/// (uncommon, and real MySQL itself rejects it as ambiguous rather than
/// picking one) still falls back to "whichever comes first".
fn merge_table_contexts(left: Option<Table>, right: Option<Table>) -> Option<Table> {
    match (left, right) {
        (Some(l), Some(r)) => {
            // A three-or-more-way join merges incrementally (this join's
            // own left/right context may itself already be a previously
            // merged, already-qualified "__join__" table) -- skip
            // re-qualifying a column whose name is already qualified, so
            // a chain of merges never produces a doubly-qualified name
            // like `"__join__.a.x"` that would silently stop matching
            // its own exact-qualified lookup.
            let qualify = |t: Table| -> Vec<Column> {
                t.columns
                    .into_iter()
                    .map(|mut c| {
                        if !c.name.contains('.') {
                            c.name = format!("{}.{}", t.name, c.name);
                        }
                        c
                    })
                    .collect()
            };
            let mut columns = qualify(l);
            columns.extend(qualify(r));
            Some(Table::new("__join__".to_string(), columns))
        }
        _ => None,
    }
}

/// Resolves a (possibly qualified, e.g. `"orders.amount"`) column name
/// against `columns`. Tries an exact match first -- the only way a
/// reference to one specific side of a join (whose merged column list has
/// every name qualified, see `merge_table_contexts`) finds *that* table's
/// column instead of silently aliasing to whichever table's
/// same-named column happens to come first. Falls back to matching by the
/// last dot-separated component on both sides, so a plain unqualified
/// reference (`"amount"`) still finds a qualified column (`"orders.amount"`)
/// and a qualified reference against an ordinary single-table context
/// (whose columns are never qualified) still finds its bare column.
fn resolve_column_index(columns: &[Column], sought: &str) -> Option<usize> {
    if let Some(idx) = columns.iter().position(|c| c.name == sought) {
        return Some(idx);
    }
    let sought_last = sought.rsplit('.').next().unwrap_or(sought);
    columns.iter().position(|c| c.name.rsplit('.').next().unwrap_or(&c.name) == sought_last)
}

/// Coerces a `Value` to a plain string the way `CONCAT`/`UPPER`/`LOWER`/
/// `SUBSTRING`/`LIKE` need it, mirroring the leniency `mysql_text_to_f64`
/// already applies on the numeric side: `NULL` has no text form (the
/// caller decides how to propagate that), and the handful of variants this
/// scalar-function library doesn't have a defined textual form for yet
/// (`Bytes`/`Date`/`Time`/`Ts`/`Json`) return `None` rather than guessing.
fn value_as_text(v: &Value) -> Option<String> {
    match v {
        Value::Text(s) => Some(s.clone()),
        Value::Int(i) => Some(i.to_string()),
        Value::Float(f) => Some(f.to_string()),
        Value::Bool(b) => Some(if *b { "1".to_string() } else { "0".to_string() }),
        Value::Num(n) => Some(n.to_string()),
        _ => None,
    }
}

/// `pattern [ESCAPE esc]` matching for `LIKE`: `%` matches any run of
/// characters (including none), `_` matches exactly one, and `esc`
/// (when given) makes the character right after it literal instead of a
/// wildcard. Case-insensitive, matching MySQL's default `_ci` collations.
/// Same tokenize-then-backtrack algorithm as `postgres::funcs::like`
/// (not shared code -- `mysql` and `postgres` are independent Cargo
/// features, so mysql's own executor can't depend on postgres's module).
fn mysql_like(s: &str, pattern: &str, esc: Option<char>) -> bool {
    enum Tok {
        Lit(char),
        One,
        Any,
    }
    let s: Vec<char> = s.to_lowercase().chars().collect();
    let pattern: Vec<char> = pattern.to_lowercase().chars().collect();
    let esc = esc.map(|c| c.to_ascii_lowercase());

    let mut toks = Vec::with_capacity(pattern.len());
    let mut i = 0;
    while i < pattern.len() {
        let c = pattern[i];
        if Some(c) == esc && i + 1 < pattern.len() {
            toks.push(Tok::Lit(pattern[i + 1]));
            i += 2;
            continue;
        }
        toks.push(match c {
            '%' => Tok::Any,
            '_' => Tok::One,
            c => Tok::Lit(c),
        });
        i += 1;
    }

    let (mut si, mut ti) = (0usize, 0usize);
    let mut star: Option<(usize, usize)> = None;
    while si < s.len() {
        if ti < toks.len() {
            match toks[ti] {
                Tok::Any => {
                    star = Some((ti, si));
                    ti += 1;
                    continue;
                }
                Tok::One => {
                    si += 1;
                    ti += 1;
                    continue;
                }
                Tok::Lit(c) if c == s[si] => {
                    si += 1;
                    ti += 1;
                    continue;
                }
                _ => {}
            }
        }
        match star {
            Some((st, ss)) => {
                ti = st + 1;
                si = ss + 1;
                star = Some((st, ss + 1));
            }
            None => return false,
        }
    }
    while ti < toks.len() && matches!(toks[ti], Tok::Any) {
        ti += 1;
    }
    ti == toks.len()
}

/// The fixed scalar-function library `Expr::Call` dispatches to -- see the
/// comment on that variant. Any argument that can't be coerced to text
/// (`value_as_text` returning `None`, which includes `NULL`) makes the
/// whole call `NULL`, matching real MySQL's own NULL-propagation for
/// these functions.
fn eval_call(name: &str, args: &[Value]) -> Result<Value, MySqlError> {
    match name {
        "CONCAT" => {
            let mut out = String::new();
            for a in args {
                match value_as_text(a) {
                    Some(s) => out.push_str(&s),
                    None => return Ok(Value::Null),
                }
            }
            Ok(Value::Text(out))
        }
        "UPPER" => match args.first().and_then(value_as_text) {
            Some(s) => Ok(Value::Text(s.to_uppercase())),
            None => Ok(Value::Null),
        },
        "LOWER" => match args.first().and_then(value_as_text) {
            Some(s) => Ok(Value::Text(s.to_lowercase())),
            None => Ok(Value::Null),
        },
        "LENGTH" => match args.first().and_then(value_as_text) {
            Some(s) => Ok(Value::Int(s.len() as i64)),
            None => Ok(Value::Null),
        },
        "SUBSTRING" | "SUBSTR" => {
            let Some(s) = args.first().and_then(value_as_text) else {
                return Ok(Value::Null);
            };
            let chars: Vec<char> = s.chars().collect();
            let len = chars.len() as i64;
            // MySQL's `SUBSTRING` is 1-indexed, and a negative start
            // counts from the end of the string (`SUBSTRING('hello', -3)`
            // is `"llo"`).
            let Some(Value::Int(start)) = args.get(1) else { return Ok(Value::Null) };
            let start0 = if *start > 0 {
                start - 1
            } else if *start < 0 {
                (len + start).max(0)
            } else {
                0
            };
            let count = match args.get(2) {
                Some(Value::Int(n)) => (*n).max(0),
                Some(_) => return Ok(Value::Null),
                None => len,
            };
            let begin = start0.clamp(0, len) as usize;
            let end = (start0 + count).clamp(0, len) as usize;
            Ok(Value::Text(chars[begin..end.max(begin)].iter().collect()))
        }
        "COALESCE" => {
            for a in args {
                if !a.is_null() {
                    return Ok(a.clone());
                }
            }
            Ok(Value::Null)
        }
        "IFNULL" => {
            let Some(a) = args.first() else { return Ok(Value::Null) };
            if !a.is_null() {
                Ok(a.clone())
            } else {
                Ok(args.get(1).cloned().unwrap_or(Value::Null))
            }
        }
        _ => Err(MySqlError::unsupported(&format!("function {name}"))),
    }
}

/// Basic integer/float arithmetic. Only defined for the two numeric
/// `Value` variants this engine's literal parser actually produces
/// (`Int`/`Float`) — mixing in a float promotes the result to float,
/// matching MySQL's own numeric-promotion rule for `+ - * /`.
fn eval_arith(op: ArithOp, l: Value, r: Value) -> Result<Value, MySqlError> {
    let as_f64 = |v: &Value| match v {
        Value::Int(i) => Some(*i as f64),
        Value::Float(f) => Some(*f),
        Value::Text(s) => Some(mysql_text_to_f64(s)),
        _ => None,
    };
    match (&l, &r) {
        (Value::Int(a), Value::Int(b)) => match op {
            ArithOp::Add => Ok(Value::Int(a + b)),
            ArithOp::Sub => Ok(Value::Int(a - b)),
            ArithOp::Mul => Ok(Value::Int(a * b)),
            // MySQL's `/` on two integers returns a DECIMAL, scaled by
            // `div_precision_increment` (default 4) beyond the operands'
            // scale (0 for an integer) — i.e. always exactly 4 decimal
            // places, not a bare float's shortest representation
            // (`10/4` is "2.5000", never "2.5").
            ArithOp::Div => {
                if *b == 0 {
                    Ok(Value::Null)
                } else {
                    Ok(Value::Text(format!("{:.4}", *a as f64 / *b as f64)))
                }
            }
            // Unlike `/`, MySQL's `%`/`MOD` on two integers stays an
            // integer (no DECIMAL promotion) and, like real MySQL,
            // `x % 0` is NULL rather than a division-by-zero error.
            ArithOp::Mod => {
                if *b == 0 {
                    Ok(Value::Null)
                } else {
                    Ok(Value::Int(a % b))
                }
            }
        },
        _ => {
            let (Some(a), Some(b)) = (as_f64(&l), as_f64(&r)) else {
                return Err(MySqlError::new(
                    1292,
                    "22007",
                    format!("Truncated incorrect DOUBLE value: {:?}", l),
                ));
            };
            match op {
                ArithOp::Add => Ok(Value::Float(a + b)),
                ArithOp::Sub => Ok(Value::Float(a - b)),
                ArithOp::Mul => Ok(Value::Float(a * b)),
                ArithOp::Div => {
                    if b == 0.0 {
                        Ok(Value::Null)
                    } else {
                        Ok(Value::Float(a / b))
                    }
                }
                ArithOp::Mod => {
                    if b == 0.0 {
                        Ok(Value::Null)
                    } else {
                        Ok(Value::Float(a % b))
                    }
                }
            }
        }
    }
}

/// MySQL's three-valued comparison logic: NULL on either side always
/// yields NULL (never true or false), never an error. Result is 0/1,
/// matching how MySQL represents boolean results.
fn eval_compare(op: CmpOp, l: Value, r: Value) -> Result<Value, MySqlError> {
    if l.is_null() || r.is_null() {
        return Ok(Value::Null);
    }
    let ordering = match (&l, &r) {
        (Value::Text(a), Value::Text(b)) => a.partial_cmp(b),
        _ => {
            let as_f64 = |v: &Value| match v {
                Value::Int(i) => Some(*i as f64),
                Value::Float(f) => Some(*f),
                Value::Text(s) => Some(mysql_text_to_f64(s)),
                _ => None,
            };
            match (as_f64(&l), as_f64(&r)) {
                (Some(a), Some(b)) => a.partial_cmp(&b),
                _ => {
                    return Err(MySqlError::new(
                        1292,
                        "22007",
                        format!("Truncated incorrect DOUBLE value: {:?}", l),
                    ));
                }
            }
        }
    };
    let Some(ordering) = ordering else {
        return Ok(Value::Null);
    };
    let result = match op {
        CmpOp::Eq => ordering == Ordering::Equal,
        CmpOp::Ne => ordering != Ordering::Equal,
        CmpOp::Lt => ordering == Ordering::Less,
        CmpOp::Le => ordering != Ordering::Greater,
        CmpOp::Gt => ordering == Ordering::Greater,
        CmpOp::Ge => ordering != Ordering::Less,
    };
    Ok(Value::Int(result as i64))
}

/// `l [NOT] IN (items...)`, matching real MySQL's three-valued semantics:
/// true if `l` equals any non-NULL item (via `eval_compare`'s own
/// equality, so the same type-coercion/ordering rules apply), else NULL
/// if `l` or any item is NULL, else false. `negated` flips true/false but
/// leaves NULL as NULL, the same way `NOT NULL` (the boolean operator, not
/// the column constraint) does.
fn eval_in_list(l: Value, items: &[Value], negated: bool) -> Result<Value, MySqlError> {
    let mut any_null = l.is_null();
    let mut found = false;
    for item in items {
        if item.is_null() {
            any_null = true;
            continue;
        }
        if eval_compare(CmpOp::Eq, l.clone(), item.clone())? == Value::Int(1) {
            found = true;
        }
    }
    if any_null && !found {
        return Ok(Value::Null); // NOT NULL is still NULL
    }
    Ok(Value::Int((found != negated) as i64))
}
