use crate::mysql::catalog::{DbState, Table};
use crate::mysql::error::MySqlError;
use crate::mysql::plan::{AggFunc, ArithOp, CmpOp, Expr, JoinOp, Plan};
use crate::mysql::types::Value;
use std::cmp::Ordering;
use std::sync::{Arc, Mutex};

pub struct Executor {
    pub db: Arc<Mutex<DbState>>,
    pub current_db: Option<String>,
    /// Values bound to `Expr::Param(i)` placeholders for this execution
    /// (from `COM_STMT_EXECUTE`'s parameter section), indexed the same way
    /// `Binder::param_counter` assigned them. Empty for a plain `COM_QUERY`
    /// or a parameterless prepared statement.
    pub params: Vec<Value>,
    /// Rows actually affected by the last `INSERT`/`UPDATE`/`DELETE` this
    /// executor ran, so the caller can report a real count in the OK
    /// packet instead of always claiming 0.
    pub last_affected_rows: u64,
    /// The AUTO_INCREMENT value generated by the last `INSERT`, if any --
    /// real MySQL's `LAST_INSERT_ID()` (and the OK packet's own field)
    /// report the *first* generated id of a multi-row INSERT, not the
    /// last, so that's what this tracks. 0 if the last statement wasn't an
    /// INSERT that generated one.
    pub last_insert_id: u64,
}

impl Executor {
    pub fn new(db: Arc<Mutex<DbState>>, current_db: Option<String>) -> Self {
        Self { db, current_db, params: Vec::new(), last_affected_rows: 0, last_insert_id: 0 }
    }

    /// Finds the `Table` a plan's rows ultimately come from, for resolving
    /// `Expr::ColName` by name in `Filter`/`Project`. Looks through any
    /// chain of single-source wrapper nodes (`Filter`, `Project`) down to
    /// the underlying `Scan` — a bare `match` on `Plan::Scan` alone missed
    /// this for anything with a `WHERE` clause, since that wraps the scan
    /// in `Plan::Filter` first, silently resolving every column reference
    /// to `Value::Null` instead of erroring or working.
    fn resolve_table_context(&self, plan: &Plan) -> Result<Option<Table>, MySqlError> {
        match plan {
            Plan::Scan { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema.tables.get(table).ok_or_else(|| MySqlError::unknown_table(table))?;
                Ok(Some((**t).clone()))
            }
            Plan::Filter { source, .. } => self.resolve_table_context(source),
            Plan::Project { source, .. } => self.resolve_table_context(source),
            _ => Ok(None),
        }
    }

    pub fn execute_plan(&mut self, plan: Plan) -> Result<Vec<Vec<Value>>, MySqlError> {
        match plan {
            Plan::Dummy => Ok(vec![vec![]]),
            Plan::ShowDatabases => Ok(vec![
                vec![Value::Text("information_schema".to_string())],
                vec![Value::Text("mysql".to_string())],
                vec![Value::Text("performance_schema".to_string())],
                vec![Value::Text("sys".to_string())],
                vec![Value::Text("test".to_string())],
            ]),
            Plan::Use(db) => {
                let state = self.db.lock().unwrap();
                if !state.schemas.contains_key(&db) {
                    return Err(MySqlError::new(
                        1049,
                        "42000",
                        format!("Unknown database '{}'", db),
                    ));
                }
                self.current_db = Some(db);
                Ok(vec![])
            }
            Plan::ShowTables(db) => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let mut rows = Vec::new();
                for table_name in schema.tables.keys() {
                    rows.push(vec![Value::Text(table_name.clone())]);
                }
                Ok(rows)
            }
            Plan::ShowColumns { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t =
                    schema.tables.get(&table).ok_or_else(|| MySqlError::unknown_table(&table))?;
                let mut rows = Vec::new();
                for col in &t.columns {
                    rows.push(vec![
                        Value::Text(col.name.clone()),
                        Value::Text(format!("{:?}", col.ty)),
                        Value::Text(if col.not_null {
                            "NO".to_string()
                        } else {
                            "YES".to_string()
                        }),
                        Value::Text(if col.primary_key {
                            "PRI".to_string()
                        } else {
                            "".to_string()
                        }),
                        col.default.clone().unwrap_or(Value::Null),
                        Value::Text(if col.auto_increment {
                            "auto_increment".to_string()
                        } else {
                            "".to_string()
                        }),
                    ]);
                }
                Ok(rows)
            }
            Plan::ShowCreateTable { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t =
                    schema.tables.get(&table).ok_or_else(|| MySqlError::unknown_table(&table))?;

                let mut sql = format!("CREATE TABLE `{}` (\n", t.name);
                let mut cols_sql = Vec::new();
                for col in &t.columns {
                    let mut col_sql = format!("  `{}` {:?}", col.name, col.ty);
                    if col.not_null {
                        col_sql.push_str(" NOT NULL");
                    }
                    if col.auto_increment {
                        col_sql.push_str(" AUTO_INCREMENT");
                    }
                    if col.primary_key {
                        col_sql.push_str(" PRIMARY KEY");
                    }
                    cols_sql.push(col_sql);
                }
                sql.push_str(&cols_sql.join(",\n"));
                sql.push_str("\n) ENGINE=InnoDB");

                Ok(vec![vec![Value::Text(t.name.clone()), Value::Text(sql)]])
            }
            Plan::CreateTable { db, table, columns } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                if schema.tables.contains_key(&table) {
                    return Err(MySqlError::new(
                        1050,
                        "42S01",
                        format!("Table '{}' already exists", table),
                    ));
                }
                schema.tables.insert(table.clone(), Arc::new(Table::new(table, columns)));
                Ok(vec![])
            }
            Plan::Insert { db, table, columns, rows } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema
                    .tables
                    .get_mut(&table)
                    .ok_or_else(|| MySqlError::unknown_table(&table))?;
                let t_mut = Arc::make_mut(t);
                let affected = rows.len() as u64;
                let mut first_generated_id: Option<i64> = None;

                for row_exprs in rows {
                    let mut new_row = vec![Value::Null; t_mut.columns.len()];

                    let mut col_indices = Vec::new();
                    if columns.is_empty() {
                        for i in 0..t_mut.columns.len() {
                            col_indices.push(i);
                        }
                    } else {
                        for col_name in &columns {
                            let idx = t_mut
                                .columns
                                .iter()
                                .position(|c| c.name == *col_name)
                                .ok_or_else(|| MySqlError::unknown_column(col_name))?;
                            col_indices.push(idx);
                        }
                    }

                    if row_exprs.len() != col_indices.len() {
                        return Err(MySqlError::new(
                            1136,
                            "21S01",
                            "Column count doesn't match value count at row 1",
                        ));
                    }

                    for (i, expr) in row_exprs.iter().enumerate() {
                        let val = self.eval_expr(expr, &[], None)?;
                        new_row[col_indices[i]] = val;
                    }

                    for (i, col) in t_mut.columns.iter().enumerate() {
                        if new_row[i].is_null() {
                            if col.auto_increment {
                                new_row[i] = Value::Int(t_mut.next_auto_increment);
                                first_generated_id.get_or_insert(t_mut.next_auto_increment);
                                t_mut.next_auto_increment += 1;
                            } else if let Some(def) = &col.default {
                                new_row[i] = def.clone();
                            } else if col.not_null {
                                return Err(MySqlError::new(
                                    1364,
                                    "HY000",
                                    format!("Field '{}' doesn't have a default value", col.name),
                                ));
                            }
                        }
                    }

                    t_mut.rows.push(new_row);
                }

                self.last_affected_rows = affected;
                self.last_insert_id = first_generated_id.map(|v| v as u64).unwrap_or(0);
                Ok(vec![])
            }
            Plan::Update { db, table, assignments, selection } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema
                    .tables
                    .get_mut(&table)
                    .ok_or_else(|| MySqlError::unknown_table(&table))?;
                let t_mut = Arc::make_mut(t);
                let mut affected = 0u64;

                for i in 0..t_mut.rows.len() {
                    let mut matches = true;
                    if let Some(sel) = &selection {
                        let val = self.eval_expr(sel, &t_mut.rows[i], Some(&*t_mut))?;
                        if val.is_null() || val == Value::Int(0) {
                            matches = false;
                        }
                    }

                    if matches {
                        affected += 1;
                        for (col_name, expr) in &assignments {
                            let idx = t_mut
                                .columns
                                .iter()
                                .position(|c| c.name == *col_name)
                                .ok_or_else(|| MySqlError::unknown_column(col_name))?;
                            let val = self.eval_expr(expr, &t_mut.rows[i], Some(&*t_mut))?;
                            t_mut.rows[i][idx] = val;
                        }
                    }
                }

                self.last_affected_rows = affected;
                Ok(vec![])
            }
            Plan::Delete { db, table, selection } => {
                let mut state = self.db.lock().unwrap();
                let schema = state.schemas.get_mut(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t = schema
                    .tables
                    .get_mut(&table)
                    .ok_or_else(|| MySqlError::unknown_table(&table))?;
                let t_mut = Arc::make_mut(t);

                let mut new_rows = Vec::new();
                for row in &t_mut.rows {
                    let mut matches = true;
                    if let Some(sel) = &selection {
                        let val = self.eval_expr(sel, row, Some(&*t_mut))?;
                        if val.is_null() || val == Value::Int(0) {
                            matches = false;
                        }
                    }

                    if !matches {
                        new_rows.push(row.clone());
                    }
                }
                self.last_affected_rows = (t_mut.rows.len() - new_rows.len()) as u64;
                t_mut.rows = new_rows;

                Ok(vec![])
            }
            Plan::Scan { db, table } => {
                let state = self.db.lock().unwrap();
                let schema = state.schemas.get(&db).ok_or_else(|| {
                    MySqlError::new(1049, "42000", format!("Unknown database '{}'", db))
                })?;
                let t =
                    schema.tables.get(&table).ok_or_else(|| MySqlError::unknown_table(&table))?;
                Ok(t.rows.clone())
            }
            Plan::Filter { source, predicate } => {
                let table_context = self.resolve_table_context(&source)?;

                let rows = self.execute_plan(*source)?;
                let mut out_rows = Vec::new();
                for row in rows {
                    let val = self.eval_expr(&predicate, &row, table_context.as_ref())?;
                    if !val.is_null() && val != Value::Int(0) {
                        out_rows.push(row);
                    }
                }
                Ok(out_rows)
            }
            Plan::Project { source, exprs, .. } => {
                let table_context = self.resolve_table_context(&source)?;

                let rows = self.execute_plan(*source)?;
                let mut out_rows = Vec::new();
                for row in rows {
                    let mut out_row = Vec::new();
                    for expr in &exprs {
                        out_row.push(self.eval_expr(expr, &row, table_context.as_ref())?);
                    }
                    out_rows.push(out_row);
                }
                Ok(out_rows)
            }
            Plan::Aggregate { source, group_exprs, exprs, .. } => {
                let table_context = self.resolve_table_context(&source)?;
                let rows = self.execute_plan(*source)?;

                // Group rows by the evaluated GROUP BY key. `Value`'s
                // `PartialEq` (via `Vec<Value>`) is enough to compare keys
                // here — linear search per row is fine at this project's
                // "simple over performant, local-use only" scale. No
                // GROUP BY clause but an aggregate in the projection means
                // the whole input is a single implicit group (possibly
                // empty, e.g. `SELECT COUNT(*) FROM t` on an empty table).
                let mut groups: Vec<(Vec<Value>, Vec<Vec<Value>>)> = Vec::new();
                if group_exprs.is_empty() {
                    groups.push((Vec::new(), rows));
                } else {
                    for row in rows {
                        let key = group_exprs
                            .iter()
                            .map(|e| self.eval_expr(e, &row, table_context.as_ref()))
                            .collect::<Result<Vec<_>, _>>()?;
                        if let Some(g) = groups.iter_mut().find(|(k, _)| *k == key) {
                            g.1.push(row);
                        } else {
                            groups.push((key, vec![row]));
                        }
                    }
                }

                let mut out_rows = Vec::new();
                for (_key, group_rows) in &groups {
                    let mut out_row = Vec::new();
                    for expr in &exprs {
                        out_row.push(self.eval_group_expr(
                            expr,
                            group_rows,
                            table_context.as_ref(),
                        )?);
                    }
                    out_rows.push(out_row);
                }
                Ok(out_rows)
            }
            Plan::Join { left, right, op } => {
                let l_rows = self.execute_plan(*left)?;
                let r_rows = self.execute_plan(*right)?;
                let mut out_rows = Vec::new();

                match op {
                    JoinOp::Cross => {
                        for l in &l_rows {
                            for r in &r_rows {
                                let mut row = l.clone();
                                row.extend(r.clone());
                                out_rows.push(row);
                            }
                        }
                    }
                    JoinOp::Inner(cond) => {
                        for l in &l_rows {
                            for r in &r_rows {
                                let mut row = l.clone();
                                row.extend(r.clone());
                                let val = self.eval_expr(&cond, &row, None)?;
                                if !val.is_null() && val != Value::Int(0) {
                                    out_rows.push(row);
                                }
                            }
                        }
                    }
                    JoinOp::Left(cond) => {
                        let r_len = if r_rows.is_empty() { 0 } else { r_rows[0].len() };
                        for l in &l_rows {
                            let mut matched = false;
                            for r in &r_rows {
                                let mut row = l.clone();
                                row.extend(r.clone());
                                let val = self.eval_expr(&cond, &row, None)?;
                                if !val.is_null() && val != Value::Int(0) {
                                    out_rows.push(row);
                                    matched = true;
                                }
                            }
                            if !matched {
                                let mut row = l.clone();
                                row.extend(vec![Value::Null; r_len]);
                                out_rows.push(row);
                            }
                        }
                    }
                }
                Ok(out_rows)
            }
        }
    }

    fn eval_expr(
        &self,
        expr: &Expr,
        row: &[Value],
        table: Option<&Table>,
    ) -> Result<Value, MySqlError> {
        match expr {
            Expr::Const(v) => Ok(v.clone()),
            Expr::Param(i) => Ok(self.params.get(*i).cloned().unwrap_or(Value::Null)),
            Expr::Col(i) => Ok(row.get(*i).cloned().unwrap_or(Value::Null)),
            Expr::ColName(name) => {
                if let Some(t) = table
                    && let Some(idx) = t.columns.iter().position(|c| c.name == *name)
                {
                    return Ok(row.get(idx).cloned().unwrap_or(Value::Null));
                }
                Ok(Value::Null) // For simplicity, return Null if column not found or no table context
            }
            Expr::And(exprs) => {
                let mut res = Value::Int(1);
                for e in exprs {
                    let v = self.eval_expr(e, row, table)?;
                    if v.is_null() {
                        res = Value::Null;
                    } else if v == Value::Int(0) {
                        return Ok(Value::Int(0));
                    }
                }
                Ok(res)
            }
            Expr::Or(exprs) => {
                let mut res = Value::Int(0);
                for e in exprs {
                    let v = self.eval_expr(e, row, table)?;
                    if v == Value::Int(1) {
                        return Ok(Value::Int(1));
                    } else if v.is_null() {
                        res = Value::Null;
                    }
                }
                Ok(res)
            }
            Expr::Arith { op, left, right } => {
                let l = self.eval_expr(left, row, table)?;
                let r = self.eval_expr(right, row, table)?;
                eval_arith(*op, l, r)
            }
            Expr::Compare { op, left, right } => {
                let l = self.eval_expr(left, row, table)?;
                let r = self.eval_expr(right, row, table)?;
                eval_compare(*op, l, r)
            }
            Expr::SysVar(name) => {
                if name.eq_ignore_ascii_case("version") {
                    Ok(Value::Text("8.0.33".to_string()))
                } else if name.eq_ignore_ascii_case("version_comment") {
                    Ok(Value::Text("noida-db MySQL 8.0".to_string()))
                } else if name.eq_ignore_ascii_case("max_allowed_packet") {
                    Ok(Value::Int(67108864))
                } else if name.eq_ignore_ascii_case("lower_case_table_names") {
                    Ok(Value::Int(0))
                } else if name.eq_ignore_ascii_case("wait_timeout")
                    || name.eq_ignore_ascii_case("interactive_timeout")
                {
                    // Real MySQL default (seconds); client pools (e.g.
                    // mysql_async's connection setup probe) parse this as
                    // a number, so it can't be the empty-text fallback.
                    Ok(Value::Int(28800))
                } else if name.eq_ignore_ascii_case("socket") {
                    Ok(Value::Text("/tmp/mysql.sock".to_string()))
                } else {
                    Ok(Value::Text("".to_string()))
                }
            }
            _ => Err(MySqlError::unsupported("expr in execution")),
        }
    }

    /// Evaluates a projection expression against one group of rows
    /// (`Plan::Aggregate`'s output). Any `Expr::Agg` found — including
    /// nested inside arithmetic/boolean combinators, e.g. `COUNT(x) + 1`
    /// — is computed over the whole group; every other leaf expression
    /// (a bare grouped column, a literal, `?`, `@@var`) is evaluated
    /// against the group's first row, since a non-aggregated column in a
    /// `GROUP BY` query is only meaningful when it's constant within the
    /// group (matching every real column reference this binder produces:
    /// the `GROUP BY` key columns themselves).
    fn eval_group_expr(
        &self,
        expr: &Expr,
        rows: &[Vec<Value>],
        table: Option<&Table>,
    ) -> Result<Value, MySqlError> {
        match expr {
            Expr::Agg { func, arg } => {
                if matches!(func, AggFunc::CountStar) {
                    return Ok(Value::Int(rows.len() as i64));
                }
                let arg = arg
                    .as_ref()
                    .ok_or_else(|| MySqlError::unsupported("aggregate without argument"))?;
                let vals: Vec<Value> =
                    rows.iter().map(|r| self.eval_expr(arg, r, table)).collect::<Result<_, _>>()?;
                Ok(compute_agg(*func, &vals))
            }
            Expr::Arith { op, left, right } => {
                let l = self.eval_group_expr(left, rows, table)?;
                let r = self.eval_group_expr(right, rows, table)?;
                eval_arith(*op, l, r)
            }
            Expr::Compare { op, left, right } => {
                let l = self.eval_group_expr(left, rows, table)?;
                let r = self.eval_group_expr(right, rows, table)?;
                eval_compare(*op, l, r)
            }
            Expr::And(exprs) => {
                let mut res = Value::Int(1);
                for e in exprs {
                    let v = self.eval_group_expr(e, rows, table)?;
                    if v.is_null() {
                        res = Value::Null;
                    } else if v == Value::Int(0) {
                        return Ok(Value::Int(0));
                    }
                }
                Ok(res)
            }
            Expr::Or(exprs) => {
                let mut res = Value::Int(0);
                for e in exprs {
                    let v = self.eval_group_expr(e, rows, table)?;
                    if v == Value::Int(1) {
                        return Ok(Value::Int(1));
                    } else if v.is_null() {
                        res = Value::Null;
                    }
                }
                Ok(res)
            }
            _ => {
                if let Some(row) = rows.first() {
                    self.eval_expr(expr, row, table)
                } else {
                    Ok(Value::Null)
                }
            }
        }
    }
}

/// Ordering used by `MIN`/`MAX`: numeric values compare numerically, text
/// compares lexically, matching `eval_compare`'s own rules. `None` (e.g.
/// comparing a number against text) means the two aren't ordered against
/// each other — the caller treats that as "keep the earlier value".
fn value_partial_cmp(a: &Value, b: &Value) -> Option<Ordering> {
    match (a, b) {
        (Value::Text(x), Value::Text(y)) => x.partial_cmp(y),
        _ => {
            let as_f64 = |v: &Value| match v {
                Value::Int(i) => Some(*i as f64),
                Value::Float(f) => Some(*f),
                _ => None,
            };
            match (as_f64(a), as_f64(b)) {
                (Some(x), Some(y)) => x.partial_cmp(&y),
                _ => None,
            }
        }
    }
}

/// `COUNT`/`SUM`/`AVG`/`MIN`/`MAX` over one group's evaluated values.
/// `COUNT(*)` is handled by the caller before reaching here (it needs the
/// row count, not evaluated values). NULLs are skipped, matching MySQL;
/// an all-NULL (or empty) group's `SUM`/`AVG`/`MIN`/`MAX` is NULL.
fn compute_agg(func: AggFunc, vals: &[Value]) -> Value {
    let non_null: Vec<&Value> = vals.iter().filter(|v| !v.is_null()).collect();
    match func {
        AggFunc::CountStar => Value::Int(vals.len() as i64),
        AggFunc::Count => Value::Int(non_null.len() as i64),
        AggFunc::Sum => {
            if non_null.is_empty() {
                return Value::Null;
            }
            let all_int = non_null.iter().all(|v| matches!(v, Value::Int(_)));
            let sum: f64 = non_null
                .iter()
                .map(|v| match v {
                    Value::Int(i) => *i as f64,
                    Value::Float(f) => *f,
                    _ => 0.0,
                })
                .sum();
            if all_int { Value::Int(sum as i64) } else { Value::Float(sum) }
        }
        AggFunc::Avg => {
            if non_null.is_empty() {
                return Value::Null;
            }
            let sum: f64 = non_null
                .iter()
                .map(|v| match v {
                    Value::Int(i) => *i as f64,
                    Value::Float(f) => *f,
                    _ => 0.0,
                })
                .sum();
            Value::Float(sum / non_null.len() as f64)
        }
        AggFunc::Min => non_null
            .into_iter()
            .cloned()
            .min_by(|a, b| value_partial_cmp(a, b).unwrap_or(Ordering::Equal))
            .unwrap_or(Value::Null),
        AggFunc::Max => non_null
            .into_iter()
            .cloned()
            .max_by(|a, b| value_partial_cmp(a, b).unwrap_or(Ordering::Equal))
            .unwrap_or(Value::Null),
    }
}

/// Basic integer/float arithmetic. Only defined for the two numeric
/// `Value` variants this engine's literal parser actually produces
/// (`Int`/`Float`) — mixing in a float promotes the result to float,
/// matching MySQL's own numeric-promotion rule for `+ - * /`.
fn eval_arith(op: ArithOp, l: Value, r: Value) -> Result<Value, MySqlError> {
    let as_f64 = |v: &Value| match v {
        Value::Int(i) => Some(*i as f64),
        Value::Float(f) => Some(*f),
        _ => None,
    };
    match (&l, &r) {
        (Value::Int(a), Value::Int(b)) => match op {
            ArithOp::Add => Ok(Value::Int(a + b)),
            ArithOp::Sub => Ok(Value::Int(a - b)),
            ArithOp::Mul => Ok(Value::Int(a * b)),
            // MySQL's `/` on two integers returns a DECIMAL, scaled by
            // `div_precision_increment` (default 4) beyond the operands'
            // scale (0 for an integer) — i.e. always exactly 4 decimal
            // places, not a bare float's shortest representation
            // (`10/4` is "2.5000", never "2.5").
            ArithOp::Div => {
                if *b == 0 {
                    Ok(Value::Null)
                } else {
                    Ok(Value::Text(format!("{:.4}", *a as f64 / *b as f64)))
                }
            }
        },
        _ => {
            let (Some(a), Some(b)) = (as_f64(&l), as_f64(&r)) else {
                return Err(MySqlError::new(
                    1292,
                    "22007",
                    format!("Truncated incorrect DOUBLE value: {:?}", l),
                ));
            };
            match op {
                ArithOp::Add => Ok(Value::Float(a + b)),
                ArithOp::Sub => Ok(Value::Float(a - b)),
                ArithOp::Mul => Ok(Value::Float(a * b)),
                ArithOp::Div => {
                    if b == 0.0 {
                        Ok(Value::Null)
                    } else {
                        Ok(Value::Float(a / b))
                    }
                }
            }
        }
    }
}

/// MySQL's three-valued comparison logic: NULL on either side always
/// yields NULL (never true or false), never an error. Result is 0/1,
/// matching how MySQL represents boolean results.
fn eval_compare(op: CmpOp, l: Value, r: Value) -> Result<Value, MySqlError> {
    if l.is_null() || r.is_null() {
        return Ok(Value::Null);
    }
    let ordering = match (&l, &r) {
        (Value::Text(a), Value::Text(b)) => a.partial_cmp(b),
        _ => {
            let as_f64 = |v: &Value| match v {
                Value::Int(i) => Some(*i as f64),
                Value::Float(f) => Some(*f),
                _ => None,
            };
            match (as_f64(&l), as_f64(&r)) {
                (Some(a), Some(b)) => a.partial_cmp(&b),
                _ => {
                    return Err(MySqlError::new(
                        1292,
                        "22007",
                        format!("Truncated incorrect DOUBLE value: {:?}", l),
                    ));
                }
            }
        }
    };
    let Some(ordering) = ordering else {
        return Ok(Value::Null);
    };
    let result = match op {
        CmpOp::Eq => ordering == Ordering::Equal,
        CmpOp::Ne => ordering != Ordering::Equal,
        CmpOp::Lt => ordering == Ordering::Less,
        CmpOp::Le => ordering != Ordering::Greater,
        CmpOp::Gt => ordering == Ordering::Greater,
        CmpOp::Ge => ordering != Ordering::Less,
    };
    Ok(Value::Int(result as i64))
}
