"""Postgres edge cases for failure_diff.py: each scenario runs on noida-db
and a real Postgres, and every step's rows/error must match."""

A = "a"


def steps(*sqls):
    return [(A, s) for s in sqls]


PG_EDGES = {
    "pg edge: numbers and casts": steps(
        "SELECT 7 / 2, -7 / 2, 7 % -3, -7 % 3, 7.0 / 2, 1 / 3::numeric",
        "SELECT 2147483647 + 1",
        "SELECT 2147483647::bigint + 1, (-2147483648)::int, 32767::smallint + 1::smallint",
        "SELECT 9223372036854775807 + 1",
        "SELECT 1 / 0",
        "SELECT 1.0 / 0",
        "SELECT 'NaN'::numeric, 'Infinity'::float8, '-inf'::float8 < 0, 'nan'::float8 = 'nan'::float8",
        "SELECT round(2.5), round(-2.5), round(2.5::float8), trunc(-2.7), ceil(-0.5), floor(-0.5), round(1234.5678, -2)",
        "SELECT '12abc'::int",
        "SELECT ' 42 '::int, '1e3'::float8::int, 2.5::int, 3.5::int, (-2.5)::int",
        "SELECT 10::numeric(5,2), 123.456::numeric(5,2), 0.1 + 0.2 = 0.3, 0.1::float8 + 0.2::float8 = 0.3::float8",
        "SELECT 12345.678::numeric(4,1)",
        "SELECT abs(-5), sign(-3.2), mod(-7, 3), power(2, 10), sqrt(2::numeric), exp(0), ln(1), log(100), 5 ^ 2, |/ 25, @ -4",
        "SELECT 5 & 3, 5 | 3, 5 # 3, ~5, 1 << 4, 256 >> 2",
        "SELECT greatest(1, NULL, 3), least('b', 'a', NULL), coalesce(NULL, NULL), nullif(1, 1), nullif(1, 2)",
        "SELECT '1'::boolean, 'yes'::boolean, 'off'::boolean, 't'::boolean AND NULL, NULL OR true, NOT NULL::boolean",
        "SELECT 'maybe'::boolean",
    ),
    "pg edge: strings": steps(
        "SELECT length('héllo'), octet_length('héllo'), upper('ß'), lower('AB'), initcap('hello wORLD foo-bar')",
        "SELECT substr('hello', 0, 3), substr('hello', -1, 3), substring('hello' from 2 for 2), substring('abc123' from '[0-9]+'), left('abc', -1), right('abc', -1)",
        "SELECT position('lo' in 'hello'), strpos('hello', 'z'), replace('aaa', 'a', 'bb'), translate('hello', 'el', 'ip'), repeat('ab', 3), repeat('x', -1)",
        "SELECT 'a' || NULL, concat('a', NULL, 'b'), concat_ws(',', 'a', NULL, 'b'), 'abc' || 1 || true",
        "SELECT lpad('x', 5, 'ab'), rpad('hello', 3), btrim('  x  '), ltrim('xxyz', 'x'), trim(both 'x' from 'xxaxx'), reverse('abc'), split_part('a,b,c', ',', 2), split_part('a,b', ',', 5)",
        r"SELECT 'abc' LIKE 'a%', 'ABC' ILIKE 'a_c', 'a_c' LIKE 'a\_c', 'abc' SIMILAR TO 'a(b|x)c', 'abc' ~ '^a.c$', 'ABC' ~* 'abc', 'abc' !~ 'z'",
        "SELECT regexp_replace('a1b22c333', '[0-9]+', '#', 'g'), regexp_matches('foo123bar45', '([a-z]+)([0-9]+)'), regexp_split_to_array('a1b2c', '[0-9]')",
        "SELECT format('%s-%I-%L', 'x', 'my col', 'it''s'), quote_ident('Foo'), quote_literal(NULL), quote_nullable(NULL), md5('abc'), to_hex(255), ascii('A'), chr(66)",
        "SELECT 'abc' < 'abd', 'Z' < 'a', ''::text = ''",
        "SELECT string_agg(x, ',' ORDER BY x DESC) FROM (VALUES ('b'), ('a'), ('c')) t(x)",
        r"SELECT E'a\tb', 'a\tb', $$it's$$, U&'\0041'",
    ),
    "pg edge: dates and times": steps(
        "SELECT '2024-02-29'::date + 365, '2024-01-31'::date + interval '1 month', '2024-03-31'::date - interval '1 month'",
        "SELECT '2023-02-29'::date",
        "SELECT date_trunc('month', timestamp '2024-05-17 13:45:10'), date_trunc('week', timestamp '2024-05-17 13:45:10'), extract(dow from date '2024-05-19'), extract(epoch from timestamp '1970-01-02 00:00:00'), date_part('doy', date '2024-12-31')",
        "SELECT age(timestamp '2024-03-01', timestamp '2023-01-15'), timestamp '2024-01-01' - timestamp '2023-12-25 12:00', interval '1 day 25 hours', interval '90 minutes' * 2, justify_hours(interval '27 hours')",
        "SELECT to_char(timestamp '2024-05-07 09:05:03', 'YYYY-MM-DD HH24:MI:SS Dy Mon'), to_date('07/05/2024', 'DD/MM/YYYY'), make_date(2024, 2, 29), make_interval(days => 3)",
        "SELECT date '2024-01-01' < timestamp '2024-01-01 00:00:01', '2024-01-01'::date = '2024-01-01 00:00'::timestamp, (date '2024-01-10' - date '2024-01-01')",
        "SELECT '24:00:00'::time, 'allballs'::time, 'epoch'::timestamp, 'infinity'::timestamp > '2024-01-01'::timestamp",
        "SELECT generate_series(timestamp '2024-01-01', timestamp '2024-01-03', interval '1 day')",
        "SELECT timestamp '2024-01-01 12:00' AT TIME ZONE 'Asia/Kolkata', timestamptz '2024-01-01 12:00+05:30' AT TIME ZONE 'UTC'",
    ),
    "pg edge: arrays and json": steps(
        "SELECT ARRAY[1,2,3] || 4, array_cat(ARRAY[1], ARRAY[2,3]), array_append(NULL::int[], 1), (ARRAY[1,2,3])[2], (ARRAY[1,2,3])[5], (ARRAY[1,2,3])[2:3], cardinality(ARRAY[[1,2],[3,4]]), array_length(ARRAY[]::int[], 1)",
        "SELECT 2 = ANY(ARRAY[1,2]), 5 = ALL(ARRAY[5,5]), NULL = ANY(ARRAY[1]), 3 = ANY(ARRAY[1, NULL]), ARRAY[1,2] @> ARRAY[2], ARRAY[1,2] && ARRAY[3], array_position(ARRAY['a','b'], 'b'), array_remove(ARRAY[1,2,1], 1)",
        "SELECT unnest(ARRAY[3,1,2]) ORDER BY 1",
        """SELECT array_agg(x ORDER BY x), array_to_string(ARRAY[1,NULL,3], ',', '*'), string_to_array('a,,b', ','), '{1,2,3}'::int[] FROM (VALUES (2), (1)) t(x)""",
        """SELECT '{"a":{"b":[1,2]}}'::jsonb -> 'a' -> 'b' ->> 1, '{"a":1}'::jsonb ? 'a', '{"a":1,"b":2}'::jsonb - 'a', '[1,2,3]'::jsonb - 0, '{"a":1}'::jsonb || '{"b":2}', '{"a":[1]}'::jsonb #> '{a,0}'""",
        """SELECT jsonb_set('{"a":1}', '{b,c}', '2'), jsonb_set('{"a":1}', '{a}', '"x"'), jsonb_insert('[1,2]', '{1}', '9'), '{"a":1}'::jsonb @> '{}', jsonb_typeof('null'), json_typeof('1.5'), '{"b":1,"a":2}'::jsonb::text, '{"b":1,"a":2}'::json::text""",
        """SELECT jsonb_agg(x), jsonb_object_agg(k, x), json_build_object('a', 1, 'b', NULL), to_jsonb(ARRAY[1,2]) FROM (VALUES ('k1', 1)) t(k, x)""",
        """SELECT key, value FROM jsonb_each('{"a":1,"b":"x"}') ORDER BY key""",
        """SELECT '{"a": 1, "a": 2}'::jsonb, '{"a": 1, "a": 2}'::json, '1.0'::jsonb, '1e2'::jsonb, '[1, 2]'::jsonb = '[1,2]'::jsonb""",
        "SELECT 'not json'::jsonb",
    ),
    "pg edge: DML corner cases": steps(
        "CREATE TABLE t (id serial PRIMARY KEY, k text UNIQUE, n int NOT NULL DEFAULT 0, CHECK (n >= 0))",
        "INSERT INTO t (k, n) VALUES ('a', 1), ('b', 2) RETURNING id, k, n",
        "INSERT INTO t (k, n) VALUES ('a', 5) ON CONFLICT (k) DO UPDATE SET n = t.n + excluded.n RETURNING id, n",
        "INSERT INTO t (k, n) VALUES ('a', 5) ON CONFLICT (k) DO NOTHING RETURNING id",
        "INSERT INTO t (k, n) VALUES ('c', -1)",
        "INSERT INTO t (k) VALUES (NULL), (NULL) RETURNING k",
        "UPDATE t SET n = n + 1 WHERE k IS NULL RETURNING id, n",
        "DELETE FROM t WHERE k = 'zzz' RETURNING *",
        "UPDATE t SET n = -5 WHERE k = 'a'",
        "UPDATE t SET k = 'b' WHERE k = 'a'",
        "INSERT INTO t (id, k) VALUES (100, 'x'), (100, 'y')",
        "SELECT count(*) FROM t",
        "WITH d AS (DELETE FROM t WHERE k = 'b' RETURNING id) SELECT count(*) FROM d",
        "INSERT INTO t (k, n) SELECT 'g' || g, g FROM generate_series(1, 3) g RETURNING k",
        "UPDATE t SET n = s.v FROM (VALUES ('g1', 10), ('g2', 20)) s(k, v) WHERE t.k = s.k RETURNING t.k, t.n",
        "DELETE FROM t USING (VALUES ('g3')) s(k) WHERE t.k = s.k RETURNING t.k",
        "SELECT k, n FROM t ORDER BY k NULLS FIRST, n DESC",
        "TRUNCATE t RESTART IDENTITY",
        "INSERT INTO t (k) VALUES ('after') RETURNING id",
    ),
    "pg edge: queries": steps(
        "CREATE TABLE e (id int, dept text, sal numeric)",
        "INSERT INTO e VALUES (1,'a',100),(2,'a',200),(3,'b',150),(4,'b',NULL),(5,NULL,50)",
        "SELECT DISTINCT ON (dept) dept, id, sal FROM e ORDER BY dept, sal DESC NULLS LAST",
        "SELECT dept, count(*), count(sal), sum(sal), avg(sal), max(sal) FILTER (WHERE id > 1) FROM e GROUP BY dept ORDER BY dept NULLS LAST",
        "SELECT dept, sum(sal) FROM e GROUP BY ROLLUP (dept) ORDER BY dept NULLS LAST, 2",
        "SELECT dept, id > 2 AS big, count(*) FROM e GROUP BY CUBE (dept, id > 2) ORDER BY 1 NULLS LAST, 2 NULLS LAST, 3",
        "SELECT dept, count(*) FROM e GROUP BY GROUPING SETS ((dept), ()) ORDER BY 1 NULLS LAST, 2",
        "SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY sal), percentile_disc(ARRAY[0.25, 0.75]) WITHIN GROUP (ORDER BY id DESC), percentile_cont(0.9) WITHIN GROUP (ORDER BY sal) FILTER (WHERE dept = 'a') FROM e",
        "SELECT dept, mode() WITHIN GROUP (ORDER BY sal DESC) FROM e GROUP BY dept ORDER BY 1 NULLS LAST",
        "SELECT percentile_cont(2) WITHIN GROUP (ORDER BY sal) FROM e",
        "SELECT id, rank() OVER w, sum(sal) OVER (w ROWS UNBOUNDED PRECEDING), lag(id) OVER w FROM e WINDOW w AS (PARTITION BY dept ORDER BY sal) ORDER BY id",
        "SELECT x, y FROM generate_series(1,2) x CROSS JOIN LATERAL (SELECT x * 10 AS y) l",
        "SELECT * FROM (VALUES (1, 'a'), (2, NULL)) v(n, s) WHERE s IS DISTINCT FROM 'a'",
        "SELECT id FROM e WHERE sal > ALL (SELECT sal FROM e WHERE dept = 'a') ORDER BY id",
        "SELECT id FROM e WHERE (dept, sal) = ('a', 200)",
        "SELECT id FROM e WHERE dept NOT IN ('a', NULL)",
        "SELECT count(*) FILTER (WHERE sal IS NULL), percentile_cont(0.5) WITHIN GROUP (ORDER BY sal), mode() WITHIN GROUP (ORDER BY dept) FROM e",
        "SELECT CASE WHEN sal > 100 THEN 'hi' WHEN sal IS NULL THEN 'none' END, id FROM e ORDER BY id",
        "SELECT id FROM e ORDER BY sal DESC NULLS FIRST LIMIT 2 OFFSET 1",
        "SELECT id FROM e ORDER BY id FETCH FIRST 2 ROWS ONLY",
        "SELECT 1 UNION SELECT 1.5 UNION SELECT NULL ORDER BY 1",
        "SELECT 'a' UNION SELECT 1",
        "SELECT exists(SELECT 1 FROM e WHERE sal IS NULL), (SELECT max(id) FROM e), (SELECT id FROM e WHERE false)",
        "SELECT dept FROM e GROUP BY dept HAVING count(*) > 1 ORDER BY 1",
        "SELECT id FROM e GROUP BY id HAVING sal > 1",
    ),
}

PG_EDGES.update({
    "pg plpgsql: functions": steps(
        """CREATE FUNCTION add(a int, b int DEFAULT 10) RETURNS int AS $$ BEGIN RETURN a + b; END $$ LANGUAGE plpgsql""",
        "SELECT add(1, 2), add(5), add(NULL, 1)",
        """CREATE FUNCTION sq(x numeric) RETURNS numeric LANGUAGE sql IMMUTABLE AS $$ SELECT x * x $$""",
        "SELECT sq(1.5), sq(NULL)",
        """CREATE FUNCTION fact(n int) RETURNS bigint LANGUAGE plpgsql AS $$
           DECLARE r bigint := 1; i int;
           BEGIN
             IF n < 0 THEN RAISE EXCEPTION 'negative: %', n USING ERRCODE = '22023'; END IF;
             FOR i IN 1..n LOOP r := r * i; END LOOP;
             RETURN r;
           END $$""",
        "SELECT fact(0), fact(5), fact(20)",
        "SELECT fact(-1)",
        """CREATE FUNCTION classify(x int) RETURNS text LANGUAGE plpgsql AS $$
           BEGIN
             CASE WHEN x < 0 THEN RETURN 'neg'; WHEN x = 0 THEN RETURN 'zero'; ELSE RETURN 'pos'; END CASE;
           END $$""",
        "SELECT classify(-3), classify(0), classify(7)",
        """CREATE FUNCTION loopy(n int) RETURNS text LANGUAGE plpgsql AS $$
           DECLARE s text := ''; i int := 0;
           BEGIN
             <<outer>> LOOP
               i := i + 1;
               CONTINUE WHEN i % 2 = 0;
               EXIT outer WHEN i > n;
               s := s || i::text || ',';
             END LOOP;
             WHILE length(s) > 0 AND right(s, 1) = ',' LOOP s := left(s, -1); END LOOP;
             RETURN s;
           END $$""",
        "SELECT loopy(7), loopy(0)",
        "CREATE TABLE acct (id int PRIMARY KEY, bal numeric NOT NULL CHECK (bal >= 0))",
        "INSERT INTO acct VALUES (1, 100), (2, 50)",
        """CREATE FUNCTION transfer(a int, b int, amt numeric) RETURNS text LANGUAGE plpgsql AS $$
           DECLARE n int;
           BEGIN
             UPDATE acct SET bal = bal - amt WHERE id = a;
             GET DIAGNOSTICS n = ROW_COUNT;
             IF n = 0 THEN RAISE EXCEPTION 'no account %', a; END IF;
             UPDATE acct SET bal = bal + amt WHERE id = b;
             RETURN 'ok';
           EXCEPTION
             WHEN check_violation THEN RETURN 'insufficient funds';
           END $$""",
        "SELECT transfer(1, 2, 30)",
        "SELECT transfer(1, 2, 500)",
        "SELECT id, bal FROM acct ORDER BY id",
        "SELECT transfer(9, 2, 1)",
        """CREATE FUNCTION lookup(k int) RETURNS numeric LANGUAGE plpgsql AS $$
           DECLARE v numeric;
           BEGIN
             SELECT bal INTO STRICT v FROM acct WHERE id = k;
             RETURN v;
           EXCEPTION WHEN no_data_found THEN RETURN -1;
           END $$""",
        "SELECT lookup(1), lookup(99)",
        """CREATE FUNCTION evens(n int) RETURNS SETOF int LANGUAGE plpgsql AS $$
           BEGIN FOR i IN 1..n LOOP IF i % 2 = 0 THEN RETURN NEXT i; END IF; END LOOP; END $$""",
        "SELECT * FROM evens(9)",
        """CREATE FUNCTION accts(min numeric) RETURNS TABLE(aid int, abal numeric) LANGUAGE plpgsql AS $$
           BEGIN RETURN QUERY SELECT id, bal FROM acct WHERE bal >= min ORDER BY id; END $$""",
        "SELECT * FROM accts(60)",
        """CREATE FUNCTION nums() RETURNS SETOF int LANGUAGE sql AS $$ SELECT generate_series(1, 3) $$""",
        "SELECT n * 10 FROM nums() AS n",
        "DO $$ DECLARE c int; BEGIN SELECT count(*) INTO c FROM acct; IF c <> 2 THEN RAISE EXCEPTION 'bad'; END IF; END $$",
        "DO $$ BEGIN PERFORM 1 / 0; EXCEPTION WHEN division_by_zero THEN INSERT INTO acct VALUES (3, 0); END $$",
        "SELECT count(*) FROM acct",
        "CREATE PROCEDURE add_acct(i int, b numeric) LANGUAGE plpgsql AS $$ BEGIN INSERT INTO acct VALUES (i, b); END $$",
        "CALL add_acct(4, 40)",
        "SELECT id, bal FROM acct ORDER BY id",
        "DROP FUNCTION add(int, int)",
        "SELECT add(1, 2)",
        "DROP FUNCTION IF EXISTS nosuch(int)",
        "CREATE FUNCTION bad() RETURNS int LANGUAGE plpgsql AS $$ BEGIN RETURN 1 END $$",
        "CREATE FUNCTION noret() RETURNS int LANGUAGE plpgsql AS $$ BEGIN NULL; END $$",
        "SELECT noret()",
    ),
    "pg plpgsql: triggers": steps(
        "CREATE TABLE item (id serial PRIMARY KEY, name text NOT NULL, price numeric, updated_at timestamp, version int NOT NULL DEFAULT 0)",
        "CREATE TABLE audit (id serial PRIMARY KEY, op text, item_id int, old_name text, new_name text)",
        """CREATE FUNCTION touch() RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN NEW.updated_at := '2024-01-01 00:00:00'; NEW.version := OLD.version + 1; RETURN NEW; END $$""",
        """CREATE FUNCTION log_item() RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF TG_OP = 'DELETE' THEN
               INSERT INTO audit (op, item_id, old_name) VALUES (TG_OP, OLD.id, OLD.name);
               RETURN OLD;
             ELSIF TG_OP = 'UPDATE' THEN
               INSERT INTO audit (op, item_id, old_name, new_name) VALUES (TG_OP, NEW.id, OLD.name, NEW.name);
             ELSE
               INSERT INTO audit (op, item_id, new_name) VALUES (TG_OP, NEW.id, NEW.name);
             END IF;
             RETURN NEW;
           END $$""",
        """CREATE FUNCTION check_price() RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF NEW.price < 0 THEN RAISE EXCEPTION 'price % is negative', NEW.price USING ERRCODE = 'check_violation'; END IF;
             IF NEW.name = 'skip' THEN RETURN NULL; END IF;
             NEW.name := trim(NEW.name);
             RETURN NEW;
           END $$""",
        "CREATE TRIGGER a_check BEFORE INSERT OR UPDATE ON item FOR EACH ROW EXECUTE FUNCTION check_price()",
        "CREATE TRIGGER b_touch BEFORE UPDATE ON item FOR EACH ROW EXECUTE FUNCTION touch()",
        "CREATE TRIGGER z_log AFTER INSERT OR UPDATE OR DELETE ON item FOR EACH ROW EXECUTE FUNCTION log_item()",
        "INSERT INTO item (name, price) VALUES ('  apple ', 1.5), ('skip', 2), ('pear', 3) RETURNING id, name, version",
        "INSERT INTO item (name, price) VALUES ('bad', -1)",
        "UPDATE item SET price = price * 2 WHERE name = 'apple' RETURNING name, price, updated_at, version",
        "UPDATE item SET name = 'skip'",
        "SELECT id, name, price, version FROM item ORDER BY id",
        "DELETE FROM item WHERE name = 'pear'",
        "SELECT op, item_id, old_name, new_name FROM audit ORDER BY id",
        """CREATE FUNCTION keep_one() RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN IF (SELECT count(*) FROM item) <= 1 THEN RETURN NULL; END IF; RETURN OLD; END $$""",
        "CREATE TRIGGER guard BEFORE DELETE ON item FOR EACH ROW EXECUTE FUNCTION keep_one()",
        "DELETE FROM item",
        "SELECT count(*) FROM item",
        "CREATE TABLE cnt (n int)",
        "INSERT INTO cnt VALUES (0)",
        """CREATE FUNCTION bump() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN UPDATE cnt SET n = n + 1; RETURN NULL; END $$""",
        "CREATE TRIGGER per_stmt AFTER UPDATE ON item FOR EACH STATEMENT EXECUTE FUNCTION bump()",
        "CREATE TRIGGER only_price AFTER UPDATE OF price ON item FOR EACH ROW WHEN (NEW.price > 100) EXECUTE FUNCTION bump()",
        "UPDATE item SET name = name",
        "UPDATE item SET price = 500",
        "UPDATE item SET price = 1 WHERE false",
        "SELECT n FROM cnt",
        "DROP TRIGGER per_stmt ON item",
        "DROP TRIGGER per_stmt ON item",
        "DROP FUNCTION bump()",
        "CREATE FUNCTION not_trigger() RETURNS int LANGUAGE sql AS 'SELECT 1'",
        "CREATE TRIGGER t BEFORE INSERT ON item FOR EACH ROW EXECUTE FUNCTION not_trigger()",
        "CREATE TABLE rec (n int)",
        "CREATE FUNCTION again() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO rec VALUES (NEW.n + 1); RETURN NEW; END $$",
        "CREATE TRIGGER loop_t AFTER INSERT ON rec FOR EACH ROW WHEN (NEW.n < 5) EXECUTE FUNCTION again()",
        "INSERT INTO rec VALUES (1)",
        "SELECT n FROM rec ORDER BY n",
    ),
})

# Round 3: what applications and ORMs lean on day to day.
PG_EDGES.update({
    "pg edge: enums": steps(
        "CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')",
        "CREATE TABLE person (name text, m mood)",
        "INSERT INTO person VALUES ('a', 'happy'), ('b', 'sad'), ('c', 'ok'), ('d', NULL)",
        "SELECT name, m FROM person ORDER BY m, name",
        "SELECT name FROM person WHERE m > 'sad' ORDER BY name",
        "SELECT max(m), min(m) FROM person",
        "INSERT INTO person VALUES ('e', 'angry')",
        "SELECT enum_range(NULL::mood), enum_first(NULL::mood), enum_last(NULL::mood)",
        "ALTER TYPE mood ADD VALUE 'meh' BEFORE 'ok'",
        "SELECT enum_range(NULL::mood)",
        "INSERT INTO person VALUES ('f', 'meh')",
        "SELECT name FROM person WHERE m < 'ok' ORDER BY m, name",
        "SELECT 'happy'::mood::text || '!', m::text FROM person WHERE name = 'a'",
        "SELECT 'happy'::mood = 'happy'",
        "ALTER TYPE mood ADD VALUE 'ok'",
        "ALTER TYPE mood ADD VALUE IF NOT EXISTS 'ok'",
    ),
    "pg edge: arrays": steps(
        "SELECT ARRAY[1,2,3] || 4, 0 || ARRAY[1,2], ARRAY[1,2] || ARRAY[3], array_append(NULL::int[], 1)",
        "SELECT (ARRAY[10,20,30])[2], (ARRAY[10,20,30])[5], (ARRAY[10,20,30])[2:3], (ARRAY[10,20,30])[:2]",
        "SELECT array_length(ARRAY[1,2,3], 1), cardinality(ARRAY[[1,2],[3,4]]), array_dims(ARRAY[[1,2],[3,4]]), array_length('{}'::int[], 1)",
        "SELECT array_position(ARRAY['a','b','c'], 'b'), array_positions(ARRAY[1,2,1], 1), array_remove(ARRAY[1,2,1], 1), array_replace(ARRAY[1,2,1], 1, 9)",
        "SELECT ARRAY[1,2] @> ARRAY[1], ARRAY[1] <@ ARRAY[1,2], ARRAY[1,2] && ARRAY[2,3], ARRAY[1,2] = ARRAY[1,2], ARRAY[1,2] < ARRAY[1,3]",
        "SELECT 2 = ANY(ARRAY[1,2,3]), 5 > ALL(ARRAY[1,2,3]), 2 = ANY('{}'::int[]), NULL = ANY(ARRAY[1]), 1 = ANY(ARRAY[NULL,1])",
        "SELECT array_to_string(ARRAY['a',NULL,'c'], ','), array_to_string(ARRAY['a',NULL,'c'], ',', '*'), string_to_array('a,b,,c', ','), string_to_array('a,b', ',', 'b')",
        "SELECT unnest(ARRAY[3,1,2]) AS x ORDER BY x",
        "SELECT * FROM unnest(ARRAY['a','b'], ARRAY[1,2,3]) AS t(l, n)",
        "SELECT * FROM unnest(ARRAY['x','y']) WITH ORDINALITY AS t(v, i)",
        "CREATE TABLE tags (id int, t text[])",
        "INSERT INTO tags VALUES (1, '{a,b}'), (2, ARRAY['c']), (3, '{}'), (4, NULL)",
        "SELECT id FROM tags WHERE 'a' = ANY(t) OR t @> '{c}' ORDER BY id",
        "SELECT id, array_length(t, 1), t[1] FROM tags ORDER BY id",
        "UPDATE tags SET t[2] = 'z' WHERE id = 2",
        "UPDATE tags SET t = array_append(t, 'q') WHERE id = 3",
        "SELECT id, t FROM tags ORDER BY id",
        "SELECT array_agg(id ORDER BY id DESC), array_agg(DISTINCT x) FROM tags, unnest(coalesce(t, '{}')) x",
        "SELECT '{1,2,3}'::int[], '{{1,2},{3,4}}'::int[], '{\"a b\",NULL,\"c\\\"d\"}'::text[]",
        "SELECT '{1,2'::int[]",
        "SELECT ARRAY[[1,2],[3]]",
    ),
    "pg edge: jsonb": steps(
        """SELECT '{"a":{"b":[1,2,{"c":3}]}}'::jsonb -> 'a' -> 'b' -> 2 ->> 'c', '{"a":1}'::jsonb ->> 'missing', '[1,2,3]'::jsonb -> -1""",
        """SELECT '{"a":{"b":[1,2]}}'::jsonb #> '{a,b,1}', '{"a":{"b":[1,2]}}'::jsonb #>> '{a,b}'""",
        """SELECT '{"a":1,"b":2}'::jsonb @> '{"a":1}', '{"a":1}'::jsonb <@ '{"a":1,"b":2}', '{"a":1}'::jsonb ? 'a', '{"a":1}'::jsonb ?| array['x','a'], '{"a":1,"b":2}'::jsonb ?& array['a','c']""",
        """SELECT '{"a":1}'::jsonb || '{"b":2}', '{"a":1,"b":2}'::jsonb - 'a', '[1,2,3]'::jsonb - 1, '{"a":{"b":1,"c":2}}'::jsonb #- '{a,b}'""",
        """SELECT jsonb_set('{"a":{"b":1}}', '{a,b}', '2'), jsonb_set('{"a":1}', '{x,y}', '2'), jsonb_set('{"a":1}', '{b}', '2', false), jsonb_insert('{"a":[1,2]}', '{a,1}', '9'), jsonb_insert('{"a":[1,2]}', '{a,1}', '9', true)""",
        """SELECT jsonb_build_object('a', 1, 'b', ARRAY[1,2], 'c', NULL), jsonb_build_array(1, 'x', NULL, true), to_jsonb('he"llo'::text), to_jsonb(1.50), jsonb_typeof('null'), jsonb_typeof('1.5')""",
        """SELECT key, value FROM jsonb_each('{"b":1,"a":"x"}') ORDER BY key""",
        """SELECT * FROM jsonb_each_text('{"a":{"x":1},"b":null}') ORDER BY key""",
        """SELECT jsonb_array_elements('[1,"a",null,{"b":2}]'), jsonb_array_length('[1,2,3]')""",
        """SELECT jsonb_object_keys('{"b":1,"a":2,"c":{"d":3}}')""",
        """SELECT jsonb_agg(x ORDER BY x DESC), jsonb_object_agg('k' || x, x) FROM generate_series(1,3) x""",
        """SELECT jsonb_strip_nulls('{"a":null,"b":{"c":null,"d":1}}'), jsonb_pretty('{"a":[1,2]}')""",
        """SELECT '{"b":1,"a":2,"a":3}'::jsonb, '{"x": 1.0, "y": 1e2}'::jsonb, '[]'::jsonb = '[]'::jsonb, '{"a":1}'::json""",
        """SELECT '{"a":'::jsonb""",
        """CREATE TABLE doc (id int, d jsonb)""",
        """INSERT INTO doc VALUES (1, '{"tags":["x","y"],"n":5}'), (2, '{"tags":["y"],"n":10}'), (3, '{"n":"str"}')""",
        """SELECT id FROM doc WHERE d @> '{"tags":["y"]}' ORDER BY id""",
        """SELECT id, (d->>'n')::int * 2 FROM doc WHERE d ? 'tags' ORDER BY id""",
        """SELECT id, (d->>'n')::int FROM doc ORDER BY id""",
        """UPDATE doc SET d = jsonb_set(d, '{n}', to_jsonb((d->>'n')::int + 1)) WHERE id = 1 RETURNING d""",
        """SELECT d->'tags'->>0 AS first, count(*) FROM doc GROUP BY 1 ORDER BY 1 NULLS FIRST""",
        """SELECT jsonb_path_query_array('{"a":[1,2,3,4]}', '$.a[*] ? (@ > 2)'), jsonb_path_exists('{"a":1}', '$.b')""",
    ),
    "pg edge: set-returning in select list": steps(
        "SELECT generate_series(1, 3)",
        "SELECT generate_series(1, 3) AS a, generate_series(1, 2) AS b",
        "SELECT x, generate_series(1, x) FROM (VALUES (1), (2)) v(x)",
        "SELECT generate_series(1, 10, 3), generate_series(5, 1, -2)",
        "SELECT generate_series('2024-01-01'::date, '2024-01-03'::date, '1 day')::date",
        "SELECT unnest(ARRAY[1,2]) * 10",
        "SELECT count(*) FROM (SELECT generate_series(1, 1000)) s",
        "SELECT generate_series(1, 0)",
        "SELECT regexp_matches('a1b2c3', '[0-9]', 'g')",
        "SELECT generate_series(1, 2) AS g, 'x' ORDER BY g DESC",
    ),
    "pg edge: dates and intervals": steps(
        "SELECT date_trunc('month', '2024-02-29 13:45:12'::timestamp), date_trunc('week', '2024-02-29'::timestamp), date_trunc('quarter', '2024-05-17'::date)",
        "SELECT extract(dow FROM '2024-02-29'::date), extract(doy FROM '2024-12-31'::date), extract(epoch FROM '2024-01-01 00:00:00+00'::timestamptz), extract(isodow FROM '2024-03-03'::date), extract(week FROM '2024-12-30'::date)",
        "SELECT '2024-01-31'::date + interval '1 month', '2024-03-31'::date - interval '1 month', '2024-02-29'::date + 365, '2024-03-01'::date - '2024-02-01'::date",
        "SELECT interval '1 day 2 hours' * 3, interval '90 minutes', interval '1 year 13 months', interval '36 hours' = interval '1 day 12 hours', justify_hours(interval '36 hours'), justify_days(interval '35 days')",
        "SELECT age('2024-03-01'::timestamp, '2023-01-15'::timestamp), age('2024-01-01'::date, '2024-01-01'::date)",
        "SELECT to_char('2024-07-04 15:06:07'::timestamp, 'YYYY-MM-DD HH24:MI:SS'), to_char('2024-07-04'::date, 'Day DD Mon YYYY'), to_char('2024-07-04'::date, 'FMDay, FMMonth DDth'), to_char(1234567.891, '9,999,999.99'), to_char(-5, '000')",
        "SELECT to_date('04 Jul 2024', 'DD Mon YYYY'), to_timestamp('2024-07-04 10:00', 'YYYY-MM-DD HH24:MI'), to_timestamp(0)",
        "SELECT make_date(2024, 2, 29), make_timestamp(2024, 1, 1, 12, 30, 15.5), make_interval(days => 3, hours => 4)",
        "SELECT make_date(2023, 2, 29)",
        "SELECT '2024-02-30'::date",
        "SELECT 'today'::date = current_date, 'epoch'::timestamp, 'infinity'::timestamp > now(), '-infinity'::date",
        "SELECT '2024-03-10 02:30:00'::timestamp AT TIME ZONE 'UTC', '2024-01-01 12:00:00+05:30'::timestamptz AT TIME ZONE 'Asia/Kolkata'",
        "SELECT ('2024-01-01'::date, '2024-02-01'::date) OVERLAPS ('2024-01-15'::date, '2024-03-01'::date)",
        "SELECT date_part('hour', interval '25 hours'), extract(month from interval '14 months'), interval '1 month' / 2",
        "SELECT '2024-01-01'::timestamp + '1 day'::interval * 0.5, '10:00'::time + interval '15 hours', '23:59:59.999999'::time",
    ),
    "pg edge: upserts and returning": steps(
        "CREATE TABLE kv (k text PRIMARY KEY, v int NOT NULL, n int DEFAULT 0, CONSTRAINT v_pos CHECK (v >= 0))",
        "INSERT INTO kv VALUES ('a', 1) ON CONFLICT (k) DO UPDATE SET v = kv.v + EXCLUDED.v, n = kv.n + 1 RETURNING k, v, n, xmax = 0 AS inserted",
        "INSERT INTO kv VALUES ('a', 5) ON CONFLICT (k) DO UPDATE SET v = kv.v + EXCLUDED.v, n = kv.n + 1 RETURNING k, v, n",
        "INSERT INTO kv VALUES ('a', 5) ON CONFLICT (k) DO UPDATE SET v = 100 WHERE kv.v > 1000 RETURNING k, v",
        "INSERT INTO kv VALUES ('a', 5), ('b', 2) ON CONFLICT DO NOTHING RETURNING k",
        "INSERT INTO kv VALUES ('c', 1), ('c', 2) ON CONFLICT (k) DO UPDATE SET v = EXCLUDED.v",
        "INSERT INTO kv VALUES ('d', -1) ON CONFLICT (k) DO NOTHING",
        "INSERT INTO kv VALUES ('a', 1) ON CONFLICT (v) DO NOTHING",
        "INSERT INTO kv VALUES ('a', 7) ON CONFLICT ON CONSTRAINT kv_pkey DO UPDATE SET v = EXCLUDED.v RETURNING *",
        "UPDATE kv SET v = v * 2 WHERE k IN ('a', 'b') RETURNING k, v, v - 1 AS minus",
        "DELETE FROM kv WHERE k = 'b' RETURNING *",
        "WITH moved AS (DELETE FROM kv WHERE k = 'a' RETURNING k, v) INSERT INTO kv SELECT k || '2', v FROM moved RETURNING k, v",
        "WITH up AS (UPDATE kv SET n = n + 10 RETURNING k) SELECT count(*) FROM up",
        "SELECT k, v, n FROM kv ORDER BY k",
        "INSERT INTO kv (k, v) SELECT 'g' || i, i FROM generate_series(1, 3) i RETURNING k",
        "INSERT INTO kv (k, v) VALUES ('h', 1) RETURNING (SELECT count(*) FROM kv)",
    ),
    "pg edge: distinct on, lateral, filter": steps(
        "CREATE TABLE ev (u int, at int, kind text)",
        "INSERT INTO ev VALUES (1, 10, 'a'), (1, 30, 'b'), (2, 20, 'a'), (2, 5, 'c'), (3, 1, 'a')",
        "SELECT DISTINCT ON (u) u, at, kind FROM ev ORDER BY u, at DESC",
        "SELECT DISTINCT ON (kind) kind, u FROM ev ORDER BY kind, u",
        "SELECT DISTINCT ON (u) u, at FROM ev ORDER BY at",
        "SELECT u.u, last.at FROM (SELECT DISTINCT u FROM ev) u CROSS JOIN LATERAL (SELECT at FROM ev e WHERE e.u = u.u ORDER BY at DESC LIMIT 1) last ORDER BY u.u",
        "SELECT u, x FROM (VALUES (1), (2)) v(u) LEFT JOIN LATERAL (SELECT at AS x FROM ev WHERE ev.u = v.u AND at > 15) l ON true ORDER BY u, x",
        "SELECT count(*) FILTER (WHERE kind = 'a'), sum(at) FILTER (WHERE u > 1), array_agg(kind) FILTER (WHERE at > 100) FROM ev",
        "SELECT u, count(*) FILTER (WHERE at > 10) AS late FROM ev GROUP BY u ORDER BY u",
        "SELECT u, string_agg(kind, ',' ORDER BY at) FROM ev GROUP BY u ORDER BY u",
        "SELECT u, at, lag(at) OVER w, lead(at, 1, -1) OVER w, first_value(kind) OVER w, row_number() OVER w FROM ev WINDOW w AS (PARTITION BY u ORDER BY at) ORDER BY u, at",
        "SELECT at, sum(at) OVER (ORDER BY at RANGE BETWEEN 10 PRECEDING AND CURRENT ROW), ntile(2) OVER (ORDER BY at), percent_rank() OVER (ORDER BY at), cume_dist() OVER (ORDER BY at) FROM ev ORDER BY at",
        "SELECT * FROM ev ORDER BY at NULLS FIRST LIMIT 2 OFFSET 1",
        "SELECT * FROM ev ORDER BY at FETCH FIRST 2 ROWS ONLY",
        "SELECT * FROM ev ORDER BY u FETCH FIRST 1 ROWS WITH TIES",
    ),
    "pg edge: sequences and identity": steps(
        "CREATE SEQUENCE s START 10 INCREMENT 5",
        "SELECT nextval('s'), nextval('s'), currval('s')",
        "SELECT setval('s', 100), nextval('s'), setval('s', 1, false), nextval('s')",
        "CREATE SEQUENCE fresh",
        "SELECT currval('fresh')",
        "CREATE SEQUENCE tiny MAXVALUE 2",
        "SELECT nextval('tiny'), nextval('tiny')",
        "SELECT nextval('tiny')",
        "CREATE TABLE ident (id int GENERATED ALWAYS AS IDENTITY, name text)",
        "INSERT INTO ident (name) VALUES ('a'), ('b') RETURNING id",
        "INSERT INTO ident (id, name) VALUES (99, 'x')",
        "INSERT INTO ident (id, name) OVERRIDING SYSTEM VALUE VALUES (99, 'x') RETURNING id",
        "INSERT INTO ident (name) VALUES ('c') RETURNING id",
        "CREATE TABLE ser (id serial PRIMARY KEY, v text)",
        "BEGIN",
        "INSERT INTO ser (v) VALUES ('lost')",
        "ROLLBACK",
        "INSERT INTO ser (v) VALUES ('kept') RETURNING id",
        "SELECT pg_get_serial_sequence('ser', 'id'), currval(pg_get_serial_sequence('ser', 'id'))",
        "ALTER SEQUENCE ser_id_seq RESTART WITH 50",
        "INSERT INTO ser (v) VALUES ('after') RETURNING id",
        "TRUNCATE ser RESTART IDENTITY",
        "INSERT INTO ser (v) VALUES ('reset') RETURNING id",
    ),
    "pg edge: constraints": steps(
        "CREATE TABLE acct (id int PRIMARY KEY, email text UNIQUE, bal numeric CHECK (bal >= 0), kind text DEFAULT 'std' NOT NULL)",
        "INSERT INTO acct (id, email, bal) VALUES (1, 'a@x', 10), (2, NULL, 0), (3, NULL, 5)",
        "INSERT INTO acct (id, email, bal) VALUES (4, 'a@x', 1)",
        "INSERT INTO acct (id, email, bal) VALUES (5, 'b@x', -1)",
        "INSERT INTO acct (id, email, bal, kind) VALUES (6, 'c@x', 1, NULL)",
        "UPDATE acct SET id = id + 1",
        "UPDATE acct SET bal = bal - 6 WHERE id IN (1, 3)",
        "CREATE UNIQUE INDEX one_vip ON acct (kind) WHERE kind = 'vip'",
        "UPDATE acct SET kind = 'vip' WHERE id = 1",
        "UPDATE acct SET kind = 'vip' WHERE id = 2",
        "ALTER TABLE acct ADD CONSTRAINT small CHECK (bal < 100)",
        "ALTER TABLE acct ADD CONSTRAINT tiny CHECK (bal < 1)",
        "ALTER TABLE acct ADD COLUMN created int NOT NULL",
        "ALTER TABLE acct ADD COLUMN created int NOT NULL DEFAULT 7",
        "SELECT id, created FROM acct ORDER BY id",
        "CREATE TABLE parent (id int PRIMARY KEY)",
        "CREATE TABLE child (id int, p int REFERENCES parent DEFERRABLE INITIALLY DEFERRED)",
        "BEGIN",
        "INSERT INTO child VALUES (1, 42)",
        "INSERT INTO parent VALUES (42)",
        "COMMIT",
        "BEGIN",
        "INSERT INTO child VALUES (2, 43)",
        "COMMIT",
        "SELECT * FROM child ORDER BY id",
    ),
    "pg edge: aborted transactions": steps(
        "CREATE TABLE t (id int PRIMARY KEY)",
        "BEGIN",
        "INSERT INTO t VALUES (1)",
        "INSERT INTO t VALUES (1)",
        "SELECT 1",
        "COMMIT",
        "SELECT count(*) FROM t",
        "BEGIN",
        "INSERT INTO t VALUES (2)",
        "SAVEPOINT s1",
        "INSERT INTO t VALUES (2)",
        "ROLLBACK TO SAVEPOINT s1",
        "INSERT INTO t VALUES (3)",
        "RELEASE SAVEPOINT s1",
        "ROLLBACK TO SAVEPOINT s1",
        "ROLLBACK",
        "SELECT count(*) FROM t",
        "COMMIT",
        "SAVEPOINT x",
        "BEGIN",
        "BEGIN",
        "END",
    ),
    "pg edge: full text": steps(
        "SELECT to_tsvector('english', 'The quick brown foxes jumped over the lazy dogs')",
        "SELECT to_tsvector('english', 'running runs ran') @@ to_tsquery('english', 'run'), plainto_tsquery('english', 'quick foxes'), websearch_to_tsquery('english', '\"quick fox\" -lazy or dog')",
        "SELECT to_tsvector('simple', 'Hello, World! hello') ",
        "SELECT ts_rank(to_tsvector('english', 'cat dog cat'), to_tsquery('english', 'cat')) > ts_rank(to_tsvector('english', 'cat dog'), to_tsquery('english', 'cat'))",
        "SELECT ts_headline('english', 'The quick brown fox jumps over the lazy dog', to_tsquery('english', 'fox & dog'))",
        "SELECT to_tsquery('english', 'fat & (rat | cat) & !dog'), to_tsquery('english', 'super:*'), numnode(to_tsquery('english', 'a & b'))",
        "SELECT to_tsquery('english', 'bad syntax &')",
        "CREATE TABLE art (id int, body text, tsv tsvector GENERATED ALWAYS AS (to_tsvector('english', body)) STORED)",
        "INSERT INTO art (id, body) VALUES (1, 'Postgres full text search'), (2, 'Searching texts quickly'), (3, 'Nothing here')",
        "CREATE INDEX art_tsv ON art USING GIN (tsv)",
        "SELECT id FROM art WHERE tsv @@ to_tsquery('english', 'search & text') ORDER BY id",
        "SELECT id, ts_rank(tsv, q) > 0 FROM art, to_tsquery('english', 'search') q WHERE tsv @@ q ORDER BY id",
        "SELECT setweight(to_tsvector('english', 'title words'), 'A') || to_tsvector('english', 'body words')",
    ),
})

PG_EDGES.update({
    "pg edge: window frames": steps(
        "CREATE TABLE w (g text, x int, d date, v numeric)",
        "INSERT INTO w VALUES ('a', 1, '2024-01-01', 1.5), ('a', 2, '2024-01-02', 2), ('a', 2, '2024-01-05', 3), ('a', 5, '2024-01-10', 4), ('a', NULL, NULL, 5), ('b', 10, '2024-02-01', 6), ('b', 20, '2024-03-01', 7)",
        "SELECT x, sum(v) OVER (ORDER BY x RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM w ORDER BY x, v",
        "SELECT x, sum(v) OVER (ORDER BY x DESC RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) FROM w ORDER BY x DESC NULLS LAST, v",
        "SELECT d, count(*) OVER (ORDER BY d RANGE BETWEEN INTERVAL '3 days' PRECEDING AND CURRENT ROW) FROM w ORDER BY d, v",
        "SELECT x, sum(v) OVER (ORDER BY x GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM w ORDER BY x, v",
        "SELECT x, sum(v) OVER (ORDER BY x GROUPS BETWEEN CURRENT ROW AND 1 FOLLOWING) FROM w ORDER BY x, v",
        "SELECT x, last_value(v) OVER (ORDER BY x), first_value(v) OVER (ORDER BY x ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) FROM w ORDER BY x, v",
        "SELECT x, sum(v) OVER (ORDER BY x RANGE CURRENT ROW) FROM w ORDER BY x, v",
        "SELECT g, x, sum(x) OVER (PARTITION BY g ORDER BY x RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM w ORDER BY g, x",
        "SELECT x, sum(v) OVER (ORDER BY x RANGE BETWEEN -1 PRECEDING AND CURRENT ROW) FROM w",
        "SELECT x, sum(v) OVER (ORDER BY x ROWS BETWEEN UNBOUNDED FOLLOWING AND CURRENT ROW) FROM w",
        "SELECT x, nth_value(v, 2) OVER (ORDER BY x ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM w ORDER BY x, v",
        "SELECT v, avg(v) OVER (ORDER BY v RANGE BETWEEN 1.5 PRECEDING AND 0.5 FOLLOWING) FROM w ORDER BY v",
    ),
})

PG_EDGES.update({
    "pg edge: overlaps and srf expressions": steps(
        "SELECT ('2024-01-01'::date, '2024-02-01'::date) OVERLAPS ('2024-02-01'::date, '2024-03-01'::date)",
        "SELECT ('2024-01-01'::date, interval '10 days') OVERLAPS ('2024-01-05'::date, interval '1 day')",
        "SELECT ('2024-03-01'::date, '2024-01-01'::date) OVERLAPS ('2024-02-01'::date, '2024-02-02'::date)",
        "SELECT ('2024-01-01'::timestamp, '2024-01-01'::timestamp) OVERLAPS ('2024-01-01'::timestamp, '2024-01-02'::timestamp)",
        "SELECT (TIME '10:00', TIME '11:00') OVERLAPS (TIME '10:30', TIME '12:00')",
        "SELECT ('2024-01-01'::date, NULL::date) OVERLAPS ('2023-01-01'::date, '2023-02-01'::date)",
        "SELECT upper(unnest(ARRAY['a','b'])) || '!'",
        "SELECT coalesce(unnest(ARRAY[NULL, 2]), 0)",
        "SELECT x, generate_series(1, 2) + x FROM (VALUES (10), (20)) v(x) ORDER BY 1, 2",
        "SELECT (generate_series(1, 3) * 2)::text",
        "SELECT generate_series('2024-01-01'::timestamp, '2024-01-01 02:00'::timestamp, '1 hour')",
    ),
})

PG_EDGES.update({
    "pg edge: ranking and headlines": steps(
        "SELECT ts_rank(to_tsvector('english', 'cat dog cat'), to_tsquery('english', 'cat'))",
        "SELECT ts_rank(to_tsvector('english', 'The quick brown fox jumps over the lazy dog'), to_tsquery('english', 'fox & dog'))",
        "SELECT ts_rank(to_tsvector('english', 'fox dog'), to_tsquery('english', 'fox & dog')), ts_rank(to_tsvector('english', 'fox a b c d e f g dog'), to_tsquery('english', 'fox & dog'))",
        "SELECT ts_rank(to_tsvector('english', 'fox dog'), to_tsquery('english', 'fox | cat'))",
        "SELECT ts_rank(setweight(to_tsvector('english', 'fox'), 'A') || to_tsvector('english', 'dog'), to_tsquery('english', 'fox | dog'))",
        "SELECT ts_rank('{0.1, 0.2, 0.4, 1.0}', to_tsvector('english', 'cats and dogs'), to_tsquery('english', 'cat'))",
        "SELECT ts_rank(to_tsvector('english', 'cat dog cat bird'), to_tsquery('english', 'cat'), 1), ts_rank(to_tsvector('english', 'cat dog cat bird'), to_tsquery('english', 'cat'), 2), ts_rank(to_tsvector('english', 'cat dog cat bird'), to_tsquery('english', 'cat'), 32)",
        "SELECT ts_rank(to_tsvector('english', 'nothing here'), to_tsquery('english', 'cat'))",
        "SELECT ts_headline('english', 'The quick brown fox jumps over the lazy dog', to_tsquery('english', 'fox & dog'), 'StartSel=[, StopSel=]')",
        "SELECT ts_headline('Running runners run', to_tsquery('english', 'run'))",
        "SELECT ts_headline('english', 'no match at all', to_tsquery('english', 'zebra'))",
        "SELECT ts_headline('english', 'x', to_tsquery('english', 'x'), 'MinWords=5, MaxWords=3')",
        "SELECT numnode(to_tsquery('english', 'a & b | !c')), numnode(plainto_tsquery('english', 'the'))",
    ),
})

PG_EDGES.update({
    "pg edge: array element assignment": steps(
        "CREATE TABLE arr (id int, a int[], s text)",
        "INSERT INTO arr VALUES (1, '{1,2,3}', 'x[1]'), (2, NULL, 'y'), (3, '{}', 'z')",
        "UPDATE arr SET a[2] = 20 WHERE id = 1",
        "UPDATE arr SET a[5] = 50, s = 'a[2] = b' WHERE id = 1",
        "UPDATE arr SET a[3] = 7 WHERE id = 2",
        "UPDATE arr SET a[1] = id * 10 WHERE id = 3",
        "SELECT id, a, s, array_lower(a, 1), array_upper(a, 1) FROM arr ORDER BY id",
        "UPDATE arr SET a[0] = -1 WHERE id = 1 RETURNING a",
        "UPDATE arr SET a[NULL] = 1 WHERE id = 1",
        "UPDATE arr SET a[1] = 'x' WHERE id = 1",
    ),
})

J = """'{"a":[1,2,3,4],"b":{"c":"x","d":[{"e":1},{"e":5}]},"s":"Hello","n":null,"f":1.5}'"""
PG_EDGES.update({
    "pg edge: jsonpath": steps(
        f"SELECT jsonb_path_query({J}, '$.a[*] ? (@ > 2)')",
        f"SELECT jsonb_path_query_array({J}, '$.a[1 to 2]'), jsonb_path_query_array({J}, '$.a[last]'), jsonb_path_query_array({J}, '$.a[last - 1, 0]')",
        f"SELECT jsonb_path_query_array({J}, '$.b.d[*].e'), jsonb_path_query_array({J}, '$.b.d.e'), jsonb_path_query_array({J}, 'strict $.b.d[*].e')",
        f"SELECT jsonb_path_query({J}, 'strict $.b.d.e')",
        f"SELECT jsonb_path_query({J}, 'strict $.missing')",
        f"SELECT jsonb_path_query_array({J}, 'lax $.missing'), jsonb_path_exists({J}, '$.missing'), jsonb_path_exists({J}, '$.b.c')",
        f"SELECT jsonb_path_query_array({J}, '$.*'), jsonb_path_query_array({J}, '$.b.*')",
        f"SELECT jsonb_path_query_array({J}, '$.**.e'), jsonb_path_query_first({J}, '$.a[*]')",
        f"SELECT jsonb_path_query_array({J}, '$.a[*] ? (@ > 1 && @ < 4)'), jsonb_path_query_array({J}, '$.a[*] ? (@ == 1 || @ == 4)'), jsonb_path_query_array({J}, '$.a[*] ? (!(@ > 2))')",
        f"SELECT jsonb_path_query_array({J}, '$.b.d[*] ? (@.e > 2)'), jsonb_path_query_array({J}, '$.b.d ? (exists (@.e))')",
        f"SELECT jsonb_path_query_array({J}, '$.s ? (@ like_regex \"^he\" flag \"i\")'), jsonb_path_query_array({J}, '$.s ? (@ starts with \"He\")')",
        f"SELECT jsonb_path_query({J}, '$.a[0] + $.f'), jsonb_path_query({J}, '$.a.size()'), jsonb_path_query({J}, '-$.f')",
        f"SELECT jsonb_path_query_array({J}, '$.a.type()'), jsonb_path_query({J}, '$.b.type()'), jsonb_path_query({J}, '$.n.type()')",
        f"SELECT jsonb_path_query({J}, '$.f.ceiling()'), jsonb_path_query({J}, '$.f.floor()'), jsonb_path_query({J}, '(-$.f).abs()')",
        """SELECT jsonb_path_query('"1.25"', '$.double()'), jsonb_path_query('[1, "2"]', '$[*].double()')""",
        f"SELECT jsonb_path_query({J}, '$.a[*] ? (@ > $min)', '{{\"min\": 2}}')",
        f"SELECT jsonb_path_query({J}, '$.a ? (@ > $nope)')",
        f"SELECT jsonb_path_query({J}, '$.a +')",
        f"SELECT jsonb_path_match({J}, '$.a[0] == 1'), jsonb_path_match({J}, 'exists($.b.c)'), {J}::jsonb @@ '$.f > 1', {J}::jsonb @? '$.a[*] ? (@ > 3)', {J}::jsonb @? '$.zzz'",
        f"SELECT jsonb_path_match({J}, '$.a')",
        f"SELECT jsonb_path_query({J}, 'strict $.a[10]')",
        f"SELECT jsonb_path_query({J}, 'strict $.a[10]', '{{}}', true)",
        f"SELECT jsonb_path_query({J}, '$.a[*] ? (@ == \"1\")'), jsonb_path_query({J}, '$.n ? (@ == null)'), jsonb_path_query_array({J}, '$.a[*] ? (@ != null)')",
        "CREATE TABLE jp (id int, d jsonb)",
        """INSERT INTO jp VALUES (1, '{"tags":["a","b"],"price":10}'), (2, '{"tags":["c"],"price":30}'), (3, '{"price":"n/a"}')""",
        "SELECT id FROM jp WHERE d @? '$.tags[*] ? (@ == \"c\")' ORDER BY id",
        "SELECT id FROM jp WHERE d @@ '$.price > 15' ORDER BY id",
        "SELECT id, jsonb_path_query_first(d, '$.price') FROM jp ORDER BY id",
    ),
    "pg edge: temporary tables are per session": [
        (A, "CREATE TEMP TABLE tt (x int)"),
        (A, "INSERT INTO tt VALUES (1)"),
        ("b", "SELECT * FROM tt"),
        ("b", "CREATE TEMP TABLE tt (y text)"),
        ("b", "INSERT INTO tt VALUES ('b')"),
        (A, "SELECT * FROM tt"),
        ("b", "SELECT * FROM tt"),
        (A, "CREATE TABLE tt (z int)"),
        (A, "SELECT * FROM tt"),
        (A, "SELECT count(*) FROM fdiff.tt"),
        (A, "SELECT * FROM pg_temp.tt"),
        (A, "SELECT relpersistence, count(*) FROM pg_class WHERE relname = 'tt' GROUP BY 1 ORDER BY 1"),
        (A, "SELECT current_schema()"),
        (A, "CREATE TEMP TABLE fdiff.bad (x int)"),
        (A, "CREATE TABLE oc (x int) ON COMMIT DROP"),
        (A, "BEGIN"),
        (A, "CREATE TEMP TABLE ocd (x int) ON COMMIT DROP"),
        (A, "INSERT INTO ocd VALUES (1)"),
        (A, "SELECT * FROM ocd"),
        (A, "COMMIT"),
        (A, "SELECT * FROM ocd"),
        (A, "CREATE TEMP TABLE ocr (x int) ON COMMIT DELETE ROWS"),
        (A, "BEGIN"),
        (A, "INSERT INTO ocr VALUES (1), (2)"),
        (A, "SELECT count(*) FROM ocr"),
        (A, "COMMIT"),
        (A, "SELECT count(*) FROM ocr"),
        (A, "CREATE TABLE pg_temp.pt (x int)"),
        (A, "SELECT relpersistence FROM pg_class WHERE relname = 'pt'"),
        (A, "CREATE TEMP VIEW tv AS SELECT 1 AS one"),
        (A, "SELECT * FROM tv"),
        ("b", "SELECT * FROM tv"),
        (A, ("reconnect",)),
        (A, "SELECT * FROM tt"),
        (A, "SELECT * FROM pt"),
        (A, "SELECT * FROM tv"),
        ("b", "SELECT * FROM tt"),
        (A, "SET search_path = pg_temp, fdiff"),
        (A, "CREATE TABLE stp (x int)"),
        (A, "SELECT relpersistence FROM pg_class WHERE relname = 'stp'"),
        (A, "DROP TABLE tt"),
        (A, "SELECT count(*) FROM pg_class WHERE relname = 'tt'"),
    ],
    "pg edge: datestyle, intervalstyle and zone rules": steps(
        "SET TimeZone = 'America/New_York'",
        "SELECT timestamptz '2026-03-09 12:00:00+00'::text, timestamptz '2026-11-01 05:30:00+00'::text, timestamptz '2001-07-04 23:00:00+00'::text",
        "SET DateStyle = 'Postgres, MDY'",
        "SELECT date '2001-12-27'::text, timestamp '2001-12-27 04:05:06.789'::text, timestamptz '2026-03-09 12:00:00+00'::text, date '0044-03-15 BC'::text",
        "SET DateStyle = 'dmy'",
        "SELECT current_setting('DateStyle'), date '2001-12-27'::text, timestamptz '2001-12-27 04:05:06+00'::text",
        "SET DateStyle = 'SQL'",
        "SELECT current_setting('DateStyle'), date '2001-12-27'::text, timestamptz '2001-12-27 04:05:06+00'::text",
        "SET DateStyle = 'German'",
        "SELECT current_setting('DateStyle'), timestamptz '2001-12-27 04:05:06+00'::text",
        "SET DateStyle = 'sql, german'",
        "SET IntervalStyle = 'postgres_verbose'",
        "SELECT interval '1 year 2 mons 3 days 04:05:06.5'::text, interval '-1 day'::text, interval '1 day -00:00:01'::text, interval '0'::text",
        "SET IntervalStyle = 'sql_standard'",
        "SELECT interval '1 year 2 mons'::text, interval '-3 days -04:05:06'::text, interval '1 year -1 day'::text, interval '0'::text",
        "CREATE TABLE ds_idx (x float8)",
        "INSERT INTO ds_idx SELECT g FROM generate_series(1, 3000) g",
        "CREATE UNIQUE INDEX ON ds_idx (abs(x))",
        "SELECT indexname FROM pg_indexes WHERE tablename = 'ds_idx'",
        "INSERT INTO ds_idx VALUES (-7)",
        "DROP TABLE ds_idx",
        "DROP VIEW no_such_view",
    ),
    "pg edge: statement_timeout": steps(
        "SET statement_timeout = 200",
        "SHOW statement_timeout",
        "SELECT pg_sleep(2)",
        # Slow on any server: a sleep per row, interrupted mid-scan.
        "SELECT count(*) FROM generate_series(1, 10) g WHERE pg_sleep(0.1) IS NOT NULL",
        "SET statement_timeout = '1.5s'",
        "SHOW statement_timeout",
        "SET statement_timeout = '10 x'",
        "SET statement_timeout = -1",
        "BEGIN",
        "SET LOCAL statement_timeout = 100",
        "SELECT pg_sleep(1)",
        "SELECT 1",
        "ROLLBACK",
        "SET statement_timeout = 0",
        "SELECT pg_sleep(0.3)",
    ),
    "pg edge: oversized arrays and strings error instead of crashing": steps(
        "SELECT array_fill(1, array[200000000])",
        "SELECT array_fill(1, array[100000, 100000])",
        "SELECT length(lpad('x', 2000000000))",
        "SELECT array_fill(7, array[2, 2], array[0, -1])::text",
        "SELECT array_fill(1, array[2], array[2147483647])",
        "SELECT array_fill(1, array[2], array[1, 1])",
        "SELECT array_fill(1, array[]::int[])::text, array_fill(1, array[0])::text",
        "SELECT array_fill(1, array[null::int])",
        "CREATE TABLE arr_big (pk int PRIMARY KEY, f1 int[])",
        "INSERT INTO arr_big VALUES (10, '[-2147483648:-2147483647]={1,2}')",
        "UPDATE arr_big SET f1[2147483647] = 42 WHERE pk = 10",
        "UPDATE arr_big SET f1[-2147483646] = 3 WHERE pk = 10",
        "SELECT f1::text FROM arr_big",
        "SELECT count(*) FROM generate_series(1, 5000000)",
    ),
    "pg edge: rails migrations (create database, renames, bare keywords)": steps(
        "CREATE DATABASE fd_x1 ENCODING = 'unicode'",
        "CREATE DATABASE fd_x2 WITH OWNER = postgres TEMPLATE = template0 ENCODING 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C' CONNECTION LIMIT = -1",
        "CREATE DATABASE fd_x3 ENCODING 'bogus'",
        "DROP DATABASE fd_x1",
        "DROP DATABASE fd_x2",
        "CREATE TABLE ra (id bigserial PRIMARY KEY, name varchar)",
        "CREATE INDEX index_ra_on_name ON ra (name)",
        "ALTER TABLE ra RENAME TO rb",
        "SELECT pg_get_serial_sequence('rb', 'id')",
        "ALTER INDEX ra_pkey RENAME TO rb_pkey",
        "ALTER INDEX index_ra_on_name RENAME TO index_rb_on_name",
        "ALTER SEQUENCE ra_id_seq RENAME TO rb_id_seq",
        "INSERT INTO rb (name) VALUES ('x') RETURNING id",
        "SELECT column_default FROM information_schema.columns WHERE table_name = 'rb' AND column_name = 'id'",
        "SELECT pg_get_serial_sequence('rb', 'id')",
        "SELECT conname FROM pg_constraint WHERE conrelid = 'rb'::regclass",
        "ALTER TABLE index_rb_on_name RENAME TO index_rb_name",
        "SELECT indexname FROM pg_indexes WHERE tablename = 'rb' ORDER BY 1",
        "ALTER INDEX no_such_index RENAME TO x",
        "SELECT current_schema, current_catalog, current_role, current_user, session_user, user",
        'CREATE EXTENSION IF NOT EXISTS "plpgsql" SCHEMA "pg_catalog"',
        'CREATE EXTENSION IF NOT EXISTS "pgcrypto"',
        'CREATE EXTENSION "pgcrypto"',
        "SELECT extname FROM pg_extension ORDER BY 1",
        'DROP EXTENSION "pgcrypto"',
        'DROP EXTENSION "pgcrypto"',
        'DROP EXTENSION IF EXISTS "pgcrypto"',
    ),
    "pg edge: a view cycle is an error, not a crash": steps(
        "CREATE TABLE vc_t (a int)",
        "CREATE VIEW vc_2 AS SELECT * FROM vc_t",
        "CREATE VIEW vc_3 AS SELECT * FROM vc_2",
        "CREATE OR REPLACE VIEW vc_2 AS SELECT * FROM vc_3",
        "SELECT * FROM vc_2",
        "SELECT * FROM (SELECT * FROM vc_3) s",
        "WITH c AS (SELECT * FROM vc_2) SELECT * FROM c",
        "SELECT 1",
    ),
    "pg edge: recursive CTEs that terminate": steps(
        "WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM t WHERE n < 1000) SELECT count(*), sum(n) FROM t",
        "WITH RECURSIVE t(n) AS (SELECT 1 UNION SELECT n % 5 + 1 FROM t) SELECT count(*) FROM t",
    ),
    "pg edge: window functions over grouped rows": steps(
        "SELECT y, x, rank() OVER (ORDER BY x DESC), sum(x) OVER (PARTITION BY y) FROM (VALUES (1, 10, 'a'), (2, 20, 'b'), (2, 30, 'c')) v(y, x, z) GROUP BY x, y ORDER BY y, x",
        "SELECT z, count(*), row_number() OVER (ORDER BY z DESC) FROM (VALUES (1, 10, 'a'), (2, 20, 'b'), (2, 30, 'b')) v(y, x, z) GROUP BY z ORDER BY z",
        "SELECT sum(sum(x)) OVER () FROM (VALUES (1), (2)) v(x)",
        "SELECT sum(sum(x) OVER ()) OVER () FROM (VALUES (1)) v(x)",
        "SELECT x, rank() OVER (ORDER BY sum(y) DESC) FROM (VALUES (1, 5), (2, 7), (1, 1)) v(x, y) GROUP BY x ORDER BY x",
        "SELECT x % 2 g, sum(x), sum(sum(x)) OVER (ORDER BY x % 2), avg(count(*)) OVER () FROM generate_series(1, 10) x GROUP BY x % 2 ORDER BY 1",
        "SELECT x, sum(x) OVER (ORDER BY d RANGE BETWEEN '1 day'::interval PRECEDING AND '1 day'::interval FOLLOWING) FROM (VALUES (1, date '2020-01-01'), (2, date '2020-01-02'), (3, date '2020-01-05')) v(x, d) ORDER BY d",
        "SELECT sum(x) OVER (ORDER BY x RANGE BETWEEN 1::int8 PRECEDING AND 2::int2 FOLLOWING) FROM generate_series(1, 5) x",
        "SELECT y, sum(x) FILTER (WHERE x > 10) OVER (ORDER BY y) FROM (VALUES (1, 10), (2, 20)) v(y, x) GROUP BY y, x ORDER BY y",
    ),
    "pg edge: jsonb operator functions and planner settings": steps(
        """SELECT jsonb_contains('{"a":1}', '{"a":1}'), jsonb_contained('{"a":1}', '{"a":1,"b":2}'), jsonb_exists('{"a":1}', 'a'), jsonb_exists_any('{"a":1}', array['x','a']), jsonb_exists_all('{"a":1}', array['x','a'])""",
        """SELECT jsonb_delete('{"a":1,"b":2}', 'a')::text, jsonb_delete('[1,2,3]', 1)::text, jsonb_delete_path('{"a":{"b":1}}', '{a,b}')::text""",
        """SELECT jsonb_delete('{"a":1,"b":2,"c":3}', 'a', 'b')::text""",
        """SELECT jsonb_delete('{"a":1,"b":2}', array['a','b'])""",
        "SET enable_sort = off",
        "SHOW enable_sort",
        "SET enable_hashagg TO false",
        "SHOW enable_hashagg",
        "RESET enable_sort",
        "SHOW enable_sort",
        "SHOW enable_partitionwise_join",
        "SET enable_bitmapscan = maybe",
    ),
    "pg edge: jsonb subscripts": steps(
        """SELECT ('{"a":{"b":[1,2,3]}}'::jsonb)['a']['b'][1], ('[1,2]'::jsonb)[-1], ('{"a":1}'::jsonb)['x'], ('[1]'::jsonb)['a'], ('{"a":1}'::jsonb)[0]""",
        """SELECT ('[1,2]'::jsonb)['1'], ('[1,2]'::jsonb)['x'], ('{"0":5}'::jsonb)[0], ('"s"'::jsonb)['a']""",
        "CREATE TABLE js (id int, j jsonb, arr int[])",
        """INSERT INTO js VALUES (1, '{}', '{1,2}'), (2, NULL, NULL), (3, '[1]', '{}'), (4, '{"a":[1]}', '{5}'), (5, '5', NULL)""",
        "UPDATE js SET j['a'] = '1' WHERE id = 1",
        """UPDATE js SET j['a'][0]['b'] = '"x"' WHERE id = 1""",
        "UPDATE js SET j['k'] = '2' WHERE id = 2",
        "UPDATE js SET j[3] = '9' WHERE id = 3",
        "UPDATE js SET j[-5] = '9' WHERE id = 3",
        "UPDATE js SET j['a'][3] = '7' WHERE id = 4",
        "UPDATE js SET j['a']['b'] = '1' WHERE id = 4",
        "UPDATE js SET j['a'] = '1' WHERE id = 5",
        "UPDATE js SET j['x'][0]['y'] = '1' WHERE id = 4",
        "UPDATE js SET j['a'] = NULL WHERE id = 1",
        "UPDATE js SET j['a'][-1] = '8' WHERE id = 4",
        """UPDATE js SET j['n'] = '{"z": [1,2]}'::jsonb, arr[2] = 9 WHERE id = 1""",
        "UPDATE js SET arr[1] = 7 WHERE id = 2",
        "SELECT id, j::text, arr::text FROM js ORDER BY id",
        "SELECT id FROM js WHERE j['a'][1] = '7'",
    ),
    "pg edge: cursors WITH HOLD": steps(
        "DECLARE c1 CURSOR FOR SELECT 1",
        "DECLARE c2 CURSOR WITH HOLD FOR SELECT g FROM generate_series(1, 5) g",
        "FETCH 2 FROM c2",
        "BEGIN", "DECLARE c3 CURSOR FOR SELECT 1", "DECLARE c4 CURSOR WITH HOLD FOR SELECT 2", "COMMIT",
        "FETCH 1 FROM c3",
        "FETCH 1 FROM c4",
        "BEGIN", "DECLARE c5 CURSOR WITH HOLD FOR SELECT 5", "ROLLBACK",
        "FETCH 1 FROM c5",
        "BEGIN", "FETCH 1 FROM c2", "ROLLBACK", "FETCH 1 FROM c2",
        "CLOSE c2", "CLOSE c4", "CLOSE nope",
    ),
    "pg edge: SET CONSTRAINTS": steps(
        "SET CONSTRAINTS ALL IMMEDIATE",
        "CREATE TABLE scp (id int PRIMARY KEY)",
        "CREATE TABLE scc (pid int REFERENCES scp DEFERRABLE INITIALLY DEFERRED, x int REFERENCES scp DEFERRABLE, y int REFERENCES scp)",
        "BEGIN", "SET CONSTRAINTS ALL IMMEDIATE", "INSERT INTO scc (pid) VALUES (1)", "ROLLBACK",
        "BEGIN", "INSERT INTO scc (pid) VALUES (1)", "SET CONSTRAINTS ALL IMMEDIATE", "ROLLBACK",
        "BEGIN", "SET CONSTRAINTS ALL DEFERRED", "INSERT INTO scc (x) VALUES (1)", "COMMIT",
        "BEGIN", "SET CONSTRAINTS ALL DEFERRED", "INSERT INTO scc (y) VALUES (1)", "ROLLBACK",
        "BEGIN", "SET CONSTRAINTS scc_pid_fkey IMMEDIATE", "INSERT INTO scc (pid) VALUES (1)", "ROLLBACK",
        "BEGIN", "SET CONSTRAINTS nope IMMEDIATE", "ROLLBACK",
        "BEGIN", "SET CONSTRAINTS scc_y_fkey DEFERRED", "ROLLBACK",
        "BEGIN", "SET CONSTRAINTS scc_pid_fkey, scc_x_fkey DEFERRED", "INSERT INTO scc (x) VALUES (1)", "DELETE FROM scc", "COMMIT",
        "BEGIN", "SET CONSTRAINTS ALL DEFERRED", "INSERT INTO scc (x) VALUES (5)", "INSERT INTO scp VALUES (5)", "SET CONSTRAINTS ALL IMMEDIATE", "COMMIT",
        "SELECT count(*) FROM scc",
    ),
    "pg edge: settings are transactional": steps(
        "SET LOCAL timezone = 'Asia/Tokyo'",
        "SHOW timezone",
        "BEGIN", "SET LOCAL timezone = 'Asia/Tokyo'", "SHOW timezone", "COMMIT", "SHOW timezone",
        "BEGIN", "SET timezone = 'Europe/Paris'", "ROLLBACK", "SHOW timezone",
        "BEGIN", "SET timezone = 'UTC'", "SAVEPOINT s1", "SET timezone = 'Asia/Kolkata'", "ROLLBACK TO SAVEPOINT s1", "SHOW timezone", "COMMIT", "SHOW timezone",
        "BEGIN", "SELECT set_config('search_path', 'pg_catalog', true)", "SHOW search_path", "COMMIT", "SHOW search_path",
        "SELECT set_config('DateStyle', 'German', false)",
        "SHOW DateStyle",
        "RESET DateStyle",
    ),
    "pg edge: Django schema-editor and locking clauses": steps(
        "CREATE TABLE dj1 (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(10))",
        "INSERT INTO dj1 (name) VALUES ('b'), ('a')",
        "ALTER TABLE dj1 ALTER COLUMN name DROP IDENTITY",
        "ALTER TABLE dj1 ALTER COLUMN name DROP IDENTITY IF EXISTS",
        "ALTER TABLE dj1 ALTER COLUMN id DROP IDENTITY IF EXISTS",
        "SELECT column_default, is_identity FROM information_schema.columns WHERE table_name = 'dj1' AND column_name = 'id'",
        "ALTER TABLE dj1 ALTER COLUMN id TYPE bigint USING id::bigint, ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
        'ALTER TABLE dj1 ALTER COLUMN name TYPE varchar(20) COLLATE "C"',
        "CREATE INDEX dj1_name ON dj1 (name) TABLESPACE pg_default",
        "CREATE INDEX dj1_name2 ON dj1 (name) INCLUDE (id) TABLESPACE pg_default WHERE id > 0",
        "SELECT name FROM dj1 ORDER BY id FOR NO KEY UPDATE",
        "SELECT a.name FROM dj1 a, dj1 b WHERE a.id = b.id ORDER BY a.id FOR UPDATE OF a, b",
        "SELECT name FROM dj1 ORDER BY 1 FOR KEY SHARE",
    ),
    "pg edge: ADD COLUMN named constraints and ALTER TYPE overflow": steps(
        "CREATE TABLE b1 (id int PRIMARY KEY)",
        "CREATE TABLE n1 (id int PRIMARY KEY, name varchar(255), arr varchar(20)[], num numeric(10,2), t text)",
        "INSERT INTO n1 VALUES (1, repeat('x', 255), ARRAY['abcdefghijklmnopq'], 12345678.5, 'abc')",
        "ALTER TABLE n1 ADD COLUMN b_id integer NULL CONSTRAINT n1_b_fk REFERENCES b1(id) DEFERRABLE INITIALLY DEFERRED, ADD COLUMN u int CONSTRAINT n1_u_uq UNIQUE, ADD COLUMN c int CONSTRAINT n1_c_ck CHECK (c > 0)",
        "SELECT conname, contype FROM pg_constraint WHERE conrelid = 'n1'::regclass ORDER BY 1",
        "ALTER TABLE n1 DROP CONSTRAINT n1_b_fk",
        "ALTER TABLE n1 ALTER COLUMN name TYPE varchar(254)",
        "ALTER TABLE n1 ALTER COLUMN arr TYPE varchar(15)[]",
        "ALTER TABLE n1 ALTER COLUMN num TYPE numeric(5,2)",
        "ALTER TABLE n1 ALTER COLUMN t TYPE int",
        "ALTER TABLE n1 ALTER COLUMN name TYPE varchar(300)",
        "SELECT length(name) FROM n1",
    ),
    "pg edge: pgcrypto digest and hmac": steps(
        "CREATE EXTENSION IF NOT EXISTS pgcrypto",
        "SELECT encode(digest('abc', 'sha1'), 'hex'), encode(digest('abc'::bytea, 'sha224'), 'hex'), digest(NULL::text, 'md5') IS NULL, pg_typeof(digest('a', 'md5'))",
        "SELECT encode(hmac('abc', 'key', 'sha256'), 'hex'), encode(hmac('abc'::bytea, 'key'::bytea, 'MD5'), 'hex')",
        "SELECT encode(sha224('abc'), 'hex'), encode(sha384('abc'), 'hex'), encode(sha512('abc'), 'hex')",
        "SELECT encode(digest('a', 'SHA256'), 'hex')",
        "SELECT digest('a', 'nope')",
    ),
    "pg edge: deferrable unique and primary keys": steps(
        "CREATE TABLE du (id int PRIMARY KEY DEFERRABLE INITIALLY DEFERRED, k int UNIQUE DEFERRABLE, CONSTRAINT du_kk UNIQUE (k, id) DEFERRABLE INITIALLY IMMEDIATE)",
        "INSERT INTO du VALUES (1, 1), (2, 2)",
        "SELECT conname, condeferrable, condeferred FROM pg_constraint WHERE conrelid = 'du'::regclass ORDER BY 1",
        "SELECT constraint_name, is_deferrable, initially_deferred FROM information_schema.table_constraints WHERE table_name = 'du' AND constraint_type <> 'CHECK' ORDER BY 1",
        "BEGIN", "UPDATE du SET id = 3 - id", "COMMIT",
        "SELECT * FROM du ORDER BY id",
        "BEGIN", "INSERT INTO du VALUES (1, 5)", "SELECT count(*) FROM du", "COMMIT",
        "BEGIN", "SET CONSTRAINTS du_k_key DEFERRED", "UPDATE du SET k = 1 WHERE id = 2", "SET CONSTRAINTS du_k_key IMMEDIATE", "ROLLBACK",
        "BEGIN", "SET CONSTRAINTS ALL DEFERRED", "UPDATE du SET k = 1 WHERE id = 2", "UPDATE du SET k = 9 WHERE id = 1", "COMMIT",
        "SELECT * FROM du ORDER BY id",
        "INSERT INTO du VALUES (9, 1)",
    ),
    "pg edge: pg_cursors": steps(
        "BEGIN",
        'DECLARE "_django_curs_1" NO SCROLL CURSOR WITHOUT HOLD FOR SELECT 1 AS x',
        "DECLARE c2 SCROLL CURSOR WITH HOLD FOR SELECT 2",
        "DECLARE c3 BINARY CURSOR FOR SELECT 3",
        "DECLARE a CURSOR FOR SELECT * FROM pg_class",
        'DECLARE "MiXed" CURSOR FOR SELECT count(*) FROM pg_class',
        "SELECT name, is_holdable, is_binary, is_scrollable, creation_time IS NOT NULL FROM pg_cursors ORDER BY name",
        'FETCH 1 FROM "_django_curs_1"',
        'CLOSE "MiXed"',
        "CLOSE mixed",
        "ROLLBACK",
        "BEGIN", "DECLARE c4 CURSOR WITH HOLD FOR SELECT 4", "COMMIT",
        "SELECT name, is_holdable FROM pg_cursors ORDER BY name",
        "CLOSE ALL",
        "SELECT count(*) FROM pg_cursors",
    ),
    "pg edge: DISTINCT ON output names and positions": steps(
        "CREATE TABLE dd (id int, name text)",
        "INSERT INTO dd VALUES (1, 'B'), (2, 'a'), (3, 'b')",
        'SELECT DISTINCT ON ("nAmEAlIaS") lower(name) AS "nAmEAlIaS", id FROM dd ORDER BY "nAmEAlIaS", id',
        "SELECT DISTINCT ON (name_lower) lower(name) AS name_lower, id FROM dd ORDER BY name_lower ASC, id",
        "SELECT DISTINCT ON (2) id, lower(name) FROM dd ORDER BY 2, 1",
        "SELECT DISTINCT ON (3) 1 AS a ORDER BY 1",
        "SELECT DISTINCT ON (a) 1 AS a, 2 AS a",
        "SELECT DISTINCT ON (id) id, name FROM dd ORDER BY id DESC",
        "SELECT DISTINCT ON (name) id FROM dd ORDER BY name, id",
    ),
})
