"""Postgres edge cases for failure_diff.py: each scenario runs on noida-db
and a real Postgres, and every step's rows/error must match."""

A = "a"


def steps(*sqls):
    return [(A, s) for s in sqls]


PG_EDGES = {
    "pg edge: numbers and casts": steps(
        "SELECT 7 / 2, -7 / 2, 7 % -3, -7 % 3, 7.0 / 2, 1 / 3::numeric",
        "SELECT 2147483647 + 1",
        "SELECT 2147483647::bigint + 1, (-2147483648)::int, 32767::smallint + 1::smallint",
        "SELECT 9223372036854775807 + 1",
        "SELECT 1 / 0",
        "SELECT 1.0 / 0",
        "SELECT 'NaN'::numeric, 'Infinity'::float8, '-inf'::float8 < 0, 'nan'::float8 = 'nan'::float8",
        "SELECT round(2.5), round(-2.5), round(2.5::float8), trunc(-2.7), ceil(-0.5), floor(-0.5), round(1234.5678, -2)",
        "SELECT '12abc'::int",
        "SELECT ' 42 '::int, '1e3'::float8::int, 2.5::int, 3.5::int, (-2.5)::int",
        "SELECT 10::numeric(5,2), 123.456::numeric(5,2), 0.1 + 0.2 = 0.3, 0.1::float8 + 0.2::float8 = 0.3::float8",
        "SELECT 12345.678::numeric(4,1)",
        "SELECT abs(-5), sign(-3.2), mod(-7, 3), power(2, 10), sqrt(2::numeric), exp(0), ln(1), log(100), 5 ^ 2, |/ 25, @ -4",
        "SELECT 5 & 3, 5 | 3, 5 # 3, ~5, 1 << 4, 256 >> 2",
        "SELECT greatest(1, NULL, 3), least('b', 'a', NULL), coalesce(NULL, NULL), nullif(1, 1), nullif(1, 2)",
        "SELECT '1'::boolean, 'yes'::boolean, 'off'::boolean, 't'::boolean AND NULL, NULL OR true, NOT NULL::boolean",
        "SELECT 'maybe'::boolean",
    ),
    "pg edge: strings": steps(
        "SELECT length('héllo'), octet_length('héllo'), upper('ß'), lower('AB'), initcap('hello wORLD foo-bar')",
        "SELECT substr('hello', 0, 3), substr('hello', -1, 3), substring('hello' from 2 for 2), substring('abc123' from '[0-9]+'), left('abc', -1), right('abc', -1)",
        "SELECT position('lo' in 'hello'), strpos('hello', 'z'), replace('aaa', 'a', 'bb'), translate('hello', 'el', 'ip'), repeat('ab', 3), repeat('x', -1)",
        "SELECT 'a' || NULL, concat('a', NULL, 'b'), concat_ws(',', 'a', NULL, 'b'), 'abc' || 1 || true",
        "SELECT lpad('x', 5, 'ab'), rpad('hello', 3), btrim('  x  '), ltrim('xxyz', 'x'), trim(both 'x' from 'xxaxx'), reverse('abc'), split_part('a,b,c', ',', 2), split_part('a,b', ',', 5)",
        r"SELECT 'abc' LIKE 'a%', 'ABC' ILIKE 'a_c', 'a_c' LIKE 'a\_c', 'abc' SIMILAR TO 'a(b|x)c', 'abc' ~ '^a.c$', 'ABC' ~* 'abc', 'abc' !~ 'z'",
        "SELECT regexp_replace('a1b22c333', '[0-9]+', '#', 'g'), regexp_matches('foo123bar45', '([a-z]+)([0-9]+)'), regexp_split_to_array('a1b2c', '[0-9]')",
        "SELECT format('%s-%I-%L', 'x', 'my col', 'it''s'), quote_ident('Foo'), quote_literal(NULL), quote_nullable(NULL), md5('abc'), to_hex(255), ascii('A'), chr(66)",
        "SELECT 'abc' < 'abd', 'Z' < 'a', ''::text = ''",
        "SELECT string_agg(x, ',' ORDER BY x DESC) FROM (VALUES ('b'), ('a'), ('c')) t(x)",
        r"SELECT E'a\tb', 'a\tb', $$it's$$, U&'\0041'",
    ),
    "pg edge: dates and times": steps(
        "SELECT '2024-02-29'::date + 365, '2024-01-31'::date + interval '1 month', '2024-03-31'::date - interval '1 month'",
        "SELECT '2023-02-29'::date",
        "SELECT date_trunc('month', timestamp '2024-05-17 13:45:10'), date_trunc('week', timestamp '2024-05-17 13:45:10'), extract(dow from date '2024-05-19'), extract(epoch from timestamp '1970-01-02 00:00:00'), date_part('doy', date '2024-12-31')",
        "SELECT age(timestamp '2024-03-01', timestamp '2023-01-15'), timestamp '2024-01-01' - timestamp '2023-12-25 12:00', interval '1 day 25 hours', interval '90 minutes' * 2, justify_hours(interval '27 hours')",
        "SELECT to_char(timestamp '2024-05-07 09:05:03', 'YYYY-MM-DD HH24:MI:SS Dy Mon'), to_date('07/05/2024', 'DD/MM/YYYY'), make_date(2024, 2, 29), make_interval(days => 3)",
        "SELECT date '2024-01-01' < timestamp '2024-01-01 00:00:01', '2024-01-01'::date = '2024-01-01 00:00'::timestamp, (date '2024-01-10' - date '2024-01-01')",
        "SELECT '24:00:00'::time, 'allballs'::time, 'epoch'::timestamp, 'infinity'::timestamp > '2024-01-01'::timestamp",
        "SELECT generate_series(timestamp '2024-01-01', timestamp '2024-01-03', interval '1 day')",
        "SELECT timestamp '2024-01-01 12:00' AT TIME ZONE 'Asia/Kolkata', timestamptz '2024-01-01 12:00+05:30' AT TIME ZONE 'UTC'",
    ),
    "pg edge: arrays and json": steps(
        "SELECT ARRAY[1,2,3] || 4, array_cat(ARRAY[1], ARRAY[2,3]), array_append(NULL::int[], 1), (ARRAY[1,2,3])[2], (ARRAY[1,2,3])[5], (ARRAY[1,2,3])[2:3], cardinality(ARRAY[[1,2],[3,4]]), array_length(ARRAY[]::int[], 1)",
        "SELECT 2 = ANY(ARRAY[1,2]), 5 = ALL(ARRAY[5,5]), NULL = ANY(ARRAY[1]), 3 = ANY(ARRAY[1, NULL]), ARRAY[1,2] @> ARRAY[2], ARRAY[1,2] && ARRAY[3], array_position(ARRAY['a','b'], 'b'), array_remove(ARRAY[1,2,1], 1)",
        "SELECT unnest(ARRAY[3,1,2]) ORDER BY 1",
        """SELECT array_agg(x ORDER BY x), array_to_string(ARRAY[1,NULL,3], ',', '*'), string_to_array('a,,b', ','), '{1,2,3}'::int[] FROM (VALUES (2), (1)) t(x)""",
        """SELECT '{"a":{"b":[1,2]}}'::jsonb -> 'a' -> 'b' ->> 1, '{"a":1}'::jsonb ? 'a', '{"a":1,"b":2}'::jsonb - 'a', '[1,2,3]'::jsonb - 0, '{"a":1}'::jsonb || '{"b":2}', '{"a":[1]}'::jsonb #> '{a,0}'""",
        """SELECT jsonb_set('{"a":1}', '{b,c}', '2'), jsonb_set('{"a":1}', '{a}', '"x"'), jsonb_insert('[1,2]', '{1}', '9'), '{"a":1}'::jsonb @> '{}', jsonb_typeof('null'), json_typeof('1.5'), '{"b":1,"a":2}'::jsonb::text, '{"b":1,"a":2}'::json::text""",
        """SELECT jsonb_agg(x), jsonb_object_agg(k, x), json_build_object('a', 1, 'b', NULL), to_jsonb(ARRAY[1,2]) FROM (VALUES ('k1', 1)) t(k, x)""",
        """SELECT key, value FROM jsonb_each('{"a":1,"b":"x"}') ORDER BY key""",
        """SELECT '{"a": 1, "a": 2}'::jsonb, '{"a": 1, "a": 2}'::json, '1.0'::jsonb, '1e2'::jsonb, '[1, 2]'::jsonb = '[1,2]'::jsonb""",
        "SELECT 'not json'::jsonb",
    ),
    "pg edge: DML corner cases": steps(
        "CREATE TABLE t (id serial PRIMARY KEY, k text UNIQUE, n int NOT NULL DEFAULT 0, CHECK (n >= 0))",
        "INSERT INTO t (k, n) VALUES ('a', 1), ('b', 2) RETURNING id, k, n",
        "INSERT INTO t (k, n) VALUES ('a', 5) ON CONFLICT (k) DO UPDATE SET n = t.n + excluded.n RETURNING id, n",
        "INSERT INTO t (k, n) VALUES ('a', 5) ON CONFLICT (k) DO NOTHING RETURNING id",
        "INSERT INTO t (k, n) VALUES ('c', -1)",
        "INSERT INTO t (k) VALUES (NULL), (NULL) RETURNING k",
        "UPDATE t SET n = n + 1 WHERE k IS NULL RETURNING id, n",
        "DELETE FROM t WHERE k = 'zzz' RETURNING *",
        "UPDATE t SET n = -5 WHERE k = 'a'",
        "UPDATE t SET k = 'b' WHERE k = 'a'",
        "INSERT INTO t (id, k) VALUES (100, 'x'), (100, 'y')",
        "SELECT count(*) FROM t",
        "WITH d AS (DELETE FROM t WHERE k = 'b' RETURNING id) SELECT count(*) FROM d",
        "INSERT INTO t (k, n) SELECT 'g' || g, g FROM generate_series(1, 3) g RETURNING k",
        "UPDATE t SET n = s.v FROM (VALUES ('g1', 10), ('g2', 20)) s(k, v) WHERE t.k = s.k RETURNING t.k, t.n",
        "DELETE FROM t USING (VALUES ('g3')) s(k) WHERE t.k = s.k RETURNING t.k",
        "SELECT k, n FROM t ORDER BY k NULLS FIRST, n DESC",
        "TRUNCATE t RESTART IDENTITY",
        "INSERT INTO t (k) VALUES ('after') RETURNING id",
    ),
    "pg edge: queries": steps(
        "CREATE TABLE e (id int, dept text, sal numeric)",
        "INSERT INTO e VALUES (1,'a',100),(2,'a',200),(3,'b',150),(4,'b',NULL),(5,NULL,50)",
        "SELECT DISTINCT ON (dept) dept, id, sal FROM e ORDER BY dept, sal DESC NULLS LAST",
        "SELECT dept, count(*), count(sal), sum(sal), avg(sal), max(sal) FILTER (WHERE id > 1) FROM e GROUP BY dept ORDER BY dept NULLS LAST",
        "SELECT dept, sum(sal) FROM e GROUP BY ROLLUP (dept) ORDER BY dept NULLS LAST, 2",
        "SELECT dept, id > 2 AS big, count(*) FROM e GROUP BY CUBE (dept, id > 2) ORDER BY 1 NULLS LAST, 2 NULLS LAST, 3",
        "SELECT dept, count(*) FROM e GROUP BY GROUPING SETS ((dept), ()) ORDER BY 1 NULLS LAST, 2",
        "SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY sal), percentile_disc(ARRAY[0.25, 0.75]) WITHIN GROUP (ORDER BY id DESC), percentile_cont(0.9) WITHIN GROUP (ORDER BY sal) FILTER (WHERE dept = 'a') FROM e",
        "SELECT dept, mode() WITHIN GROUP (ORDER BY sal DESC) FROM e GROUP BY dept ORDER BY 1 NULLS LAST",
        "SELECT percentile_cont(2) WITHIN GROUP (ORDER BY sal) FROM e",
        "SELECT id, rank() OVER w, sum(sal) OVER (w ROWS UNBOUNDED PRECEDING), lag(id) OVER w FROM e WINDOW w AS (PARTITION BY dept ORDER BY sal) ORDER BY id",
        "SELECT x, y FROM generate_series(1,2) x CROSS JOIN LATERAL (SELECT x * 10 AS y) l",
        "SELECT * FROM (VALUES (1, 'a'), (2, NULL)) v(n, s) WHERE s IS DISTINCT FROM 'a'",
        "SELECT id FROM e WHERE sal > ALL (SELECT sal FROM e WHERE dept = 'a') ORDER BY id",
        "SELECT id FROM e WHERE (dept, sal) = ('a', 200)",
        "SELECT id FROM e WHERE dept NOT IN ('a', NULL)",
        "SELECT count(*) FILTER (WHERE sal IS NULL), percentile_cont(0.5) WITHIN GROUP (ORDER BY sal), mode() WITHIN GROUP (ORDER BY dept) FROM e",
        "SELECT CASE WHEN sal > 100 THEN 'hi' WHEN sal IS NULL THEN 'none' END, id FROM e ORDER BY id",
        "SELECT id FROM e ORDER BY sal DESC NULLS FIRST LIMIT 2 OFFSET 1",
        "SELECT id FROM e ORDER BY id FETCH FIRST 2 ROWS ONLY",
        "SELECT 1 UNION SELECT 1.5 UNION SELECT NULL ORDER BY 1",
        "SELECT 'a' UNION SELECT 1",
        "SELECT exists(SELECT 1 FROM e WHERE sal IS NULL), (SELECT max(id) FROM e), (SELECT id FROM e WHERE false)",
        "SELECT dept FROM e GROUP BY dept HAVING count(*) > 1 ORDER BY 1",
        "SELECT id FROM e GROUP BY id HAVING sal > 1",
    ),
}
